### ISSUE TITLE
18.04 dependencies name are messy

### ISSUE THREAD

**Issue by j1warren** [IBBoard/cawbird#1]
When installing cawbird_1.0-1+60.1_amd64.deb on 18.04, apt spits

cawbird : Depends: libgstreamer-plugins-base1.0 but it is not installable
           Depends: libglib2.0 but it is not installable
           Depends: libgspell-1 but it is not installable
           Depends: libgtk-3 (>= 3.20) but it is not installable
           Depends: libjson-glib but it is not installable
           Depends: libsoup2.4 but it is not installable
           Depends: libsqlite3 but it is not installable

Whereas all these libs are installed but having different names

libgstreamer-plugins-base1.0-0/bionic-updates,now 1.14.5-0ubuntu1~18.04.1 amd64 [installed]
libglib2.0-0/bionic-updates,bionic-security,now 2.56.4-0ubuntu0.18.04.4 amd64 [installed]
libgspell-1-1/bionic,now 1.6.1-1 amd64 [installed]
libgtk-3-0/bionic-updates,now 3.22.30-1ubuntu4 amd64 [installed]
libjson-glib-1.0-0/bionic,now 1.4.2-3 amd64 [installed]
libsoup2.4-1/bionic-updates,bionic-security,now 2.62.1-1ubuntu0.1 amd64 [installed]
libsqlite3-0/bionic-updates,bionic-security,now 3.22.0-1ubuntu0.1 amd64 [installed]

After that apt install doesn't work unless you --fix-broken which removes cawbird.
As a workaround had to manually edit Dependencies of cawbird in /var/lib/dpkg/status.

**Comment by IBBoard** [comment]
Ubuntu was the one OS that I hadn't tested. I thought I'd copied the DSC and other files from the standard build, but apparently not. And it seems you can't just remove "-dev" from the end of the package names to get to the main package.

I've copied the "Depends" section from the official "control" file. I'm hoping build 61 will work.

**Comment by j1warren** [comment]
.61 is all good now, thank you.
