### ISSUE TITLE
Fails to play video

### ISSUE THREAD

**Issue by denefi** [IBBoard/cawbird#113]
When I try to play a video I get this error:

![Bildschirmfoto vom 2020-02-17 18-18-22](https://user-images.githubusercontent.com/37028000/74687067-44a38700-51cb-11ea-9352-64d9ac54619c.png)
 I'm on ubuntu 19.10 and using the .deb version 1.0.4-1+12.4

**Comment by IBBoard** [comment]
Can you give me an example tweet? I've never seen "application/x-hls" before, and apparently it's a live-streaming media format.

Installing the GStreamer "bad" plugins *should* fix it, from what I've read.

**Comment by IBBoard** [comment]
I've added GStreamer Bad to the dependencies. I'm assuming that will fix it.
