### ISSUE TITLE
Gnome 200% scaling makes cawbird open images with scrolling.

### ISSUE THREAD

**Issue by j1warren** [IBBoard/cawbird#115]
I've set up a 4k monitor with Gnome 200% scaling.
So now I have some images appear with scrollbar when I click on them in cawbird.

I think I didn't have it on my previous monitor with no scaling.

Might there be an issue?

Screenshot: https://img.techpowerup.org/200312/cawbird.png
Tweet link: https://t.co/OkyQ6NuXnA

**Comment by IBBoard** [comment]
What resolution was your previous monitor?

That image is 1132px high. At 1080p then it would be too tall and show scrollbars (we actually max out at 95% of the monitor). At 4K with 200% scaling then you're basically in the same situation, but scaled.

This may be expected behaviour.

**Comment by j1warren** [comment]
> This may be expected behaviour.
So cawbird doesn't scale the image when clicking on it? If so, then this issue is not a bug.
I just thought it scales big images to fit the screen.

**Comment by IBBoard** [comment]
No. Corebird always scrolled them if they were too large, on the basis that you click on it to view it at full size, and so does Cawbird.

It will scale video, though, because people tend to want to watch the video without scrolling it mid-way through!
