### ISSUE TITLE
glib-networking is already installed but requires install glib-networking

### ISSUE THREAD

**Issue by hellojo011** [IBBoard/cawbird#116]
i'm on ubuntu 18.04 LTS and using version 1.0.4-1+12.6

installed glib-networking from apt but I get a message like this. 

$ cawbird 
GLib-GIO-Message: 01:02:51.110: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.

(cawbird:6472): Gtk-WARNING **: 01:02:51.181: Theme parsing error: style.css:220:16: The 'outline-radius' property has been renamed to '-gtk-outline-radius'

(cawbird:6472): Gtk-WARNING **: 01:02:51.181: Theme parsing error: style.css:226:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(cawbird:6472): Gtk-WARNING **: 01:02:51.181: Theme parsing error: style.css:227:25: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(cawbird:6472): Gtk-WARNING **: 01:02:51.181: Theme parsing error: style.css:232:36: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(cawbird:6472): Gdk-CRITICAL **: 01:02:51.199: gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed

(cawbird:6472): cawbird-CRITICAL **: 01:02:52.729: AccountCreateWidget.vala:59: TLS/SSL support not available; install glib-networking

$ dpkg -l | grep glib-networking
ii  glib-networking:amd64                           2.56.0-1                                            amd64        network-related giomodules for GLib
ii  glib-networking-common                          2.56.0-1                                            all          network-related giomodules for GLib - data files
ii  glib-networking-services                        2.56.0-1                                            amd64        network-related giomodules for GLib - D-Bus services
ii  glib-networking-tests                           2.56.0-1                                            amd64        network-related giomodules for GLib - installed tests

How to fix it?

**Comment by IBBoard** [comment]
[Line 59 of AccountCreateWidget.vala](https://github.com/IBBoard/cawbird/blob/v1.0.4/src/widgets/AccountCreateWidget.vala#L59) just prints an error. That comes from librest, which uses libsoup, which appears to throw that error [when it can't load libgiognutls.so](https://mail.gnome.org/archives/libsoup-list/2014-March/msg00002.html).

My understanding was that glib-network should already pull in gnutls. Can you check that it's there?

**Comment by hellojo011** [comment]
libgiognutls.so is installed in /usr/lib/x86_64-linux-gnu/gio/modules . 

$ ls -l /usr/lib/x86_64-linux-gnu/gio/modules/
total 540
-rw-r--r-- 1 root root    270 Mar 14 01:02 giomodule.cache
-rw-r--r-- 1 root root  52448 Mar 29  2018 libdconfsettings.so
-rw-r--r-- 1 root root  18272 Mar 17  2018 libgiognomeproxy.so
-rw-r--r-- 1 root root 124912 Mar 17  2018 libgiognutls.so
-rw-r--r-- 1 root root  14176 Mar 17  2018 libgiolibproxy.so
-rw-r--r-- 1 root root 116656 Jul  5  2019 libgioremote-volume-monitor.so
-rw-r--r-- 1 root root 211144 Jul  5  2019 libgvfsdbus.so

It can only be run from the terminal with "GIO_MODULE_DIR=/usr/lib/x86_64-linux-gnu/gio/modules cawbird". Is there anything more?

**Comment by IBBoard** [comment]
Which build are you using? Deb from OBS, Snap, Flatpak or something else?

If it works when you set the GIO_MODULE_DIR then it definitely points to an environment problem rather than Cawbird itself.

**Comment by hellojo011** [comment]
I installed it as a deb build through apt. 

I think it is also an environment problem.  However, even if I add a global environment variable in / etc / environment, I am experiencing the same error and having difficulty solving the problem.

**Comment by IBBoard** [comment]
I've got an up-to-date Ubuntu VM and I can't recreate this.

I would look at libgnutls to see if that's why it's failing to load, but the fact that GIO_MODULE_DIR fixes it suggests that it's GIO itself that's broken.

I think you need to ask on the Ubuntu forums about how GIO can get broken like this.

**Comment by hellojo011** [comment]
understood.  Thanks for your answer.

**Comment by IBBoard** [comment]
If you find a cause/solution, could you post it here in case it somehow happens to other people as well? Thanks.

**Comment by hellojo011** [comment]
I solved this problem perfectly. The problem was due to a typo in the environment variable. I accidentally wrote x86_64-linux-gnu as x86-64-linux-gnu. oops!

Add to / etc / environment or ~ / .xinitrc.
> export GIO_MODULE_DIR=/usr/lib/x86_64-linux-gnu/gio/modules/
