### ISSUE TITLE
Tooltip for cropped account names

### ISSUE THREAD

**Issue by philipzae** [IBBoard/cawbird#120]
**Describe the bug**
Unable to see full name of user account when window is small

**To Reproduce**
1. Goto the account of @CodeLutin
2. Shrink width of window
3. Notice that you cant see the full name of the account and hovering over it doesnt show a tooltip
4. Click on one of the tweets
5. Notice you cant see the full name of the account and hovering over it doesnt show a tooltip

**Expected behavior**
Show a tooltip to

**Screenshots**
Account View
![preview](https://imgur.com/2MJKh8T.png)

Tweet View
![preview](https://imgur.com/1btgcLW.png)

**System details:**
 - OS: Linux Mint 19.3
 - Version: cawbird_1.0.4-1+12.1_amd64
 - Package type: Deb

**Comment by philipzae** [comment]
Also in the regular view
![preview](https://imgur.com/cok7cZf.png)

**Comment by IBBoard** [comment]
Okay, Git Master should have that fixed now. And as a bonus, it doesn't truncate the name anywhere near as often anyway!

![Normal width](https://user-images.githubusercontent.com/388582/78596405-9d92b180-7843-11ea-8167-d0f257a57f03.png) ![Narrow with hover](https://user-images.githubusercontent.com/388582/78596382-979cd080-7843-11ea-9471-3b25ffc2a8da.png)
