### ISSUE TITLE
No indicator or appearance of poll

### ISSUE THREAD

**Issue by philipzae** [IBBoard/cawbird#121]
**Describe the bug**
If a tweet is a poll, it only shows the text part and not the poll options

**To Reproduce**
1. Go to @Xubuntu profile
2. The first entry is 'How do you install and manage software on #Linux? Let us know why and which one in the comments. #XubuntuPoll'
3. It is a poll but no poll options or indication appears

**Expected behavior**
That the poll options are there and I can vote in it or atleast an indicator that it is a poll that i can click and visit the website to vote

**Screenshots**
Twitter
![preview](https://imgur.com/Qccqj4n.png)

Cawbird
![preview](https://imgur.com/sKu9B91.png)

**System details:**
 - OS: Linux Mint 19.3
 - Version: cawbird_1.0.4-1+12.1_amd64
 - Package type: Deb

**Comment by IBBoard** [comment]
Please see the [limitations in the README](https://github.com/IBBoard/cawbird#limitations) - unfortunately, Twitter hate third-party clients and don't even provide a flag to show that a tweet is a poll.
