### ISSUE TITLE
Images should centered when moving between them

### ISSUE THREAD

**Issue by philipzae** [IBBoard/cawbird#122]
**Describe the bug**
Scrolling through images in a tweet should always center the images

**To Reproduce**
1. Go to this tweet in cawbird - https://twitter.com/gnome/status/1245259605388607489
2. Click on the first image
3. Click the right arrow to move to the next image
4. Portion of second image appears off the screen

**Expected behavior**
Center the image rather than using the top left position of the previous image as the top left of the new image

**Screenshots**
![preview](https://imgur.com/iUk9iKi.png)

**System details:**
 - OS: Linux Mint 19.3
 - Version: cawbird_1.0.4-1+12.1_amd64
 - Package type: Deb

**Comment by IBBoard** [comment]
Can you test with Git Master? I can't recreate this, so I think it has been fixed as part of #59.

**Comment by philipzae** [comment]
Don't see a .deb for master. Is one coming out soon as the last release is 2 months ago.

**Comment by IBBoard** [comment]
Sorry, don't build packages for master. I keep [my own build](https://build.opensuse.org/package/show/home:IBBoard:desktop/cawbird) closer to master to test things from time-to-time, but that's only for openSUSE Tumbleweed. You'd have to build from source to test it.

**Comment by philipzae** [comment]
Does this tweet also work correctly if the image is larger than your screen resolution?
https://twitter.com/Emirates247/status/1246765878936514560

**Comment by IBBoard** [comment]
Difficult for me to check because nothing gets too big on 1440p (because of Twitter's max image size) but large images should scroll.

**Comment by IBBoard** [comment]
Whether an image scrolls or is scaled is a separate issue from where it is positioned.

I'm going to close this, because I think it's already fixed. If it still happens for you in 1.0.5 then it's some desktop or window manager specific issue and I don't know what we can do.

**Comment by philipzae** [comment]
Sorry for mixing two bugs into a single issue. I upgraded to 1.0.5 and the centering of images issue is still present.

**Comment by IBBoard** [comment]
This could be hard to fix, then. The dialog is modal (i.e. locked to the parent and centred on it). Gnome does the Right Thing™ when the content changes and recentres automatically. It seems that KDE doesn't.

There *might* be something we can do to kick it and make it recentre. But from looking at the code then we only declare the size of the window and let the window manager work out its position.

**Comment by IBBoard** [comment]
Just realised - is this actually KDE or is it a different Linux Mint desktop environment? I'd assumed from the grey and the buttons that it was KDE, but you're following Gnome tweets 🙂

**Comment by philipzae** [comment]
I ran Linux Mint XFCE then, but use Xubuntu now. The KDE image was what I clicked on in the Gnome tweet, but that was just an example of an image as I don't follow Gnome.

**Comment by IBBoard** [comment]
I'm going to close this for now because a) if our current fixes don't work then I've got nothing else, b) it works on GTK, which suggests that it's a window manager oddity and c) #177 may change how we do images anyway.
