### ISSUE TITLE
Ubuntu 20.04 compatible package

### ISSUE THREAD

**Issue by mju7** [IBBoard/cawbird#136]
The existing package for Ubuntu 19.10 doesn't work in Ubuntu 20.04 because of unmet dependencies. The package for 19.10 depends on libgspell-1-1 but 20.04 only has libgspell-1-2

**Comment by IBBoard** [comment]
20.04 isn't released yet and isn't in the Open Build Service target distros list.

As far as I can see, the build step currently depends on libgspell-1-dev but the package does not explicitly depend on libgspell-1-1. Based on that, and the fact that my openSUSE build already depend on libgspell-1-2, then I'm assuming it might just populate itself correctly at build time.

I'll keep an eye on it when I can build the packages.

**Comment by mju7** [comment]
I don't know if you had to do something or if it happened automatically, but the Ubuntu 20.04 package is there now and is working for me, thanks!

**Comment by IBBoard** [comment]
I added 20.04 to the build list and [announced it as it was going](https://twitter.com/CawbirdClient/status/1253986564100759553). The libgspell version resolved itself as part of the build, as I expected it would.
