### ISSUE TITLE
Cawbird can generate too many notifications on first login

### ISSUE THREAD

**Issue by IBBoard** [IBBoard/cawbird#137]
**Describe the bug**
A twitter user said (in Portuguese - translation by Google Translate):

"I installed a twitter app for ubuntu that calls cawbird, at the first login [it] simply displayed all the notifications I had since I did the account, I was scared until now, but the mass is very light"

**To Reproduce**
1. Have an account with lots of existing notifications
2. Add the account to Cawbird
3. Maybe something in the "notifications" settings

**Expected behavior**
Cawbird doesn't spam loads of notifications. If anything, it should probably be silent on that first login.

**Screenshots**
![EVYQN2gX0AUUGjF](https://user-images.githubusercontent.com/388582/79148134-f1aa1280-7dbc-11ea-86bb-91ac99084ba8.jpeg)

**System details:**
 - OS: Unknown
 - Version: Unknown
 - Package type: Unknown

**Comment by philipzae** [comment]
This happened to me as well when i first log into a new account on cawbird and it assumes a number of my DMs hadnt been seen before, etc. and shows alot of notifications.

**Comment by IBBoard** [comment]
Is this still a problem? I'm struggling to recreate this at the moment. I've added and removed my test account (https://twitter.com/IBBTwtr) and I'm not seeing a flood of messages for the @-mentions. I'm still waiting for the DMs to appear.

**Comment by IBBoard** [comment]
Just found some code with a comment that says "Ignore the mention if both accounts are configured in Cawbird". That may be why I wasn't seeing notifications when I added my test account, which only gets mentioned by one of my other accounts that's configured in Cawbird!

**Comment by IBBoard** [comment]
Okay, I can't recreate the mentions issue right now - and I think it's mainly because we already ignore every mention that gets loaded in the first load. Which suggests the user might have been suffering from #9 and the first load failed, we unset the "suppress mentions notifications" flag, and then it tries again and loads all of the mentions and triggers a notification for each one.

The DMs are a little harder. I'm currently fighting against some async code to make it suppress the notifications. But the bigger question is how we handle the initial DMs. Do we pretend the user has seen them all? Because there might be DMs that they haven't seen and they won't know. Or do we keep the unread marker but just suppress the notification? Which is inconsistent (we'll notify *and* show the unread marker in future) but less intrusive.
