### ISSUE TITLE
saved items

### ISSUE THREAD

**Issue by ijann** [IBBoard/cawbird#144]
**Is your feature request related to a problem? Please describe.**
In the drawer menu - on android, there is an item called "Saved Items", I don't see it anywhere in cawbird.

**Describe the solution you'd like**
That is inside the drawer menu,
It seems to me that it should be together with the profile options,
I show an image where it could be,
the red arrow indicates the place

![7d7a7f64-4f91-49e9-b4b9-bfe88db4784f](https://user-images.githubusercontent.com/2209203/80497251-93466d80-8940-11ea-9d36-ca9cdac7e2fb.jpg)

**Describe alternatives you've considered**
none

**Additional context**
I already did it

**Comment by IBBoard** [comment]
Is this the "bookmarks" feature? If so then we can't implement it because Twitter don't supply an API. It's listed in our [Limitations list](https://github.com/IBBoard/cawbird#limitations).

**Comment by ijann** [comment]
thanks, sorry i didn't see that marker
