### ISSUE TITLE
Don't show 'Sorry, you are not authorized to see this status' dialog

### ISSUE THREAD

**Issue by philipzae** [IBBoard/cawbird#153]
Similar to issue #138, it would be good not to display this dialog.
Tweet: https://twitter.com/bratbud/status/1263050689476988930

![image](https://user-images.githubusercontent.com/4412114/82710932-2307df00-9c95-11ea-82a2-15722e9001bc.png)

**Comment by philipzae** [comment]
Oh sorry, I didn't think that fix covered this issue. Thanks.

**Comment by IBBoard** [comment]
It didn't. But it was all in the same code, so I could modify it easily.
