### ISSUE TITLE
AppData validation fails in 1.1.0

### ISSUE THREAD

**Issue by tim77** [IBBoard/cawbird#157]
**Describe the bug**
AppData validation fails after update to 1.1.0. This is already well known issue and you will get this error on Flathub as well. The problem comes from here:
https://github.com/IBBoard/cawbird/blob/master/data/uk.co.ibboard.cawbird.appdata.xml.in#L55
Linter don't like this `<em></em>` stuff. Hope this saves your time a little bit.

**System details:**
 - OS: Fedora 32
 - Version: 1.1.0
 - Package type: RPM, Flatpak

**Comment by IBBoard** [comment]
Ugh, I guess I'll have to go and find out what the allowed tags are in appdata.

**Comment by IBBoard** [comment]
Should be fixed with 781e606, and I've updated the Flathub build file. We'll see whether it works.

**Comment by tim77** [comment]
Woks with this patch!
