### ISSUE TITLE
Display replies below tweet

### ISSUE THREAD

**Issue by IBBoard** [IBBoard/cawbird#16]
Baedert chose to put replies above the tweet in tweet view, so you have to scroll up to see them. This seems odd and is the opposite of what Twitter (and almost every other threaded UI) does.

I should finally get round to making the change to flip it so that it reads the "right" way (scroll up to see previous posts in thread, replies are automatically visible).

(Reported by @jacobmischka as baedert/corebird#369 and backed by me but rejected in Corebird)

**Comment by LennyPenny** [comment]
Any progress on this?

**Comment by IBBoard** [comment]
No, not yet. You'll see commits appear in this ticket or a branch called "bug-16-blah-blah-blah" when I start working on it.

I've looked at it before in the Corebird days but never took it too far because Baedert didn't want it. In some ways it should be quite easy, but in others then I think it needed some reasonable thought to be done properly.

**Comment by IBBoard** [comment]
Okay, I think that branch fixes it. I'm just running it locally for a while to make sure.

Any feedback on it is welcomed (e.g. whether we need more of an indicator that there's "replied to" tweets above, even though the tweet says "in reply to X")

**Comment by j1warren** [comment]
Oh, just remembered what I wanted to ask for a while.

cawbird doesn't load all the replies for a tweet when you open one.

For example, [link](https://twitter.com/NCCGroupInfosec/status/1257980406693072896)
On the twitter.com page it shows 4 replies, however cawbird for me displays only the first 2.
Is that how it supposed to work?

**Comment by IBBoard** [comment]
That's more relevant to #17. 

The short answer is that a) there's no official way to get the replies to a tweet ([limitations](https://github.com/IBBoard/cawbird#limitations)) and b) the best approximation we have uses the search and is limited to 7 days of history and a few other constraints (again, [limitations](https://github.com/IBBoard/cawbird#limitations)!). The time limit isn't relevant here, but I imagine some of the other constraints area. 

Hashtag-Blame-Twitter-API-Again

**Comment by IBBoard** [comment]
Fixed and merged when we merged #17
