### ISSUE TITLE
Group is not there

### ISSUE THREAD

**Issue by jalalsfs** [IBBoard/cawbird#166]
Hello there,
I've just installed the app on my Fedora 32, and it looks awesome.
I was checking for group in the messages tab, but I couldn't see it, is it something which not included to the app, or I just don't know how to figure it out?
Thank you for the your nice work and time.

**Comment by IBBoard** [comment]
Apparently group DMs are not in the API and Twitter don't care and so closed the request:

https://twitterdevfeedback.uservoice.com/forums/921790-twitter-developer-labs/suggestions/37689256-allow-access-to-dm-group-conversations-via-twitter

I'll try to add it to the "limitations" list soon.
