### ISSUE TITLE
Occasional crashes from hires_progress: cairo_surface_destroy: Assertion `CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&surface->ref_count)' failed

### ISSUE THREAD

**Issue by lucaswerkmeister** [IBBoard/cawbird#196]
**Describe the bug**
Since maybe a week or so ago, cawbird occasionally crashes. It seems to be related to media viewing, but I can’t reliably reproduce it yet, sorry. But I figured I’d file a report anyways.

Partial journal output of one crash:
```
uk.co.ibboard.cawbird[10401]: cawbird: cairo-surface.c:955: cairo_surface_destroy: Assertion `CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&surface->ref_count)' failed.
cawbird[10401]: invalid unclassed pointer in cast to 'GtkImage'
cawbird[10401]: gtk_image_set_from_surface: assertion 'GTK_IS_IMAGE (image)' failed
```
Backtrace (from `coredumpctl gdb`):
```
Stack trace of thread 10401:                                                                                                      
#0  0x00007f5a9e63d615 raise (libc.so.6 + 0x3d615)                                                                                
#1  0x00007f5a9e626862 abort (libc.so.6 + 0x26862)                                                                                
#2  0x00007f5a9e626747 __assert_fail_base.cold (libc.so.6 + 0x26747)                                                              
#3  0x00007f5a9e635bf6 __assert_fail (libc.so.6 + 0x35bf6)                                                                        
#4  0x00007f5a9ef49af5 cairo_surface_destroy (libcairo.so.2 + 0x77af5)                                                            
#5  0x0000561acee83c16 hires_progress (cawbird + 0x72c16)                                                                         
#6  0x00007f5a9ecc896a g_signal_emit_valist (libgobject-2.0.so.0 + 0x2f96a)                                                       
#7  0x00007f5a9ecc8ae0 g_signal_emit (libgobject-2.0.so.0 + 0x2fae0)                                                              
#8  0x0000561acee7f0dd emit_media_hires_progress (cawbird + 0x6e0dd)                                                              
#9  0x00007f5a9f97db00 g_main_context_dispatch (libglib-2.0.so.0 + 0x52b00)                                                       
#10 0x00007f5a9f9cf1f9 n/a (libglib-2.0.so.0 + 0xa41f9)                                                                           
#11 0x00007f5a9f97c421 g_main_context_iteration (libglib-2.0.so.0 + 0x51421)                                                      
#12 0x00007f5a9edbdd1e g_application_run (libgio-2.0.so.0 + 0xccd1e)                                                              
#13 0x0000561acee31f94 _vala_main (cawbird + 0x20f94)                                                                             
#14 0x00007f5a9e628152 __libc_start_main (libc.so.6 + 0x28152)                                                                    
#15 0x0000561acee31e6e _start (cawbird + 0x20e6e)                                                                                 
```
I tried doing a debug build but it doesn’t seem to produce much useful information yet (`info locals` still doesn’t show much).

**To Reproduce**
Seems to be related to opening media (image or video), maybe scrolling around. Sometimes seems to happen shortly after closing the media again, too, but not always. That’s all I have so far, sorry.

**System details:**
 - OS: Arch Linux
 - Version: 1.2.0.2.r5.g683a608e-1 (commit 683a608e)
 - Package type: [cawbird-git AUR package](https://aur.archlinux.org/packages/cawbird-git), with `options=(debug !strip)` manually added to the PKGBUILD (might do another rebuild with -O0 later)

**Comment by IBBoard** [comment]
Ugh, I hate C code. I'm a software developer. I want to write programs, not manage memory and references!

At first I was hoping this was a duplicate/related to #195, but you're already testing with the fix and it's in a different area.

I'll see what I can work out from a walk-through of the code. Presumably we're not tracking references correctly somewhere.

**Comment by lucaswerkmeister** [comment]
I tried another build with `-O0`, managed to get another crash fairly quickly, and then *gdb* died with SIGABRT o_O

I’ll let you know if I get any more details

**Comment by IBBoard** [comment]
Is this happening with GIFs or with images?

And if it is happening with images, is it happening with large images where we load the "thumbnail" and then load the higher-res version? (Right-click > Open in browser will tell you the full res - if it is more than 680×680 then we do a fake "progressive" load)

**Comment by lucaswerkmeister** [comment]
It might be related to high-res images, I can’t say for sure. (I don’t seem to have a lot of gifs in my timeline at the moment. Videos with sound might be unproblematic.)

With `-O0`, the error message looks a bit different:
```
cawbird[7001]: invalid unclassed pointer in cast to 'CbMediaImageWidget'
kernel: cawbird[7001]: segfault at 100000016 ip 00007fefbbccdc3c sp 00007ffd85c8ed50 error 4 in libgobject-2.0.so.0.6600.0[7fefbbca7000+2e000]
```
As does the backtrace:
```
Stack trace of thread 7001:                                                                                                       
#0  0x00007fefbbccdc3c g_type_check_instance_cast (libgobject-2.0.so.0 + 0x34c3c)                                                 
#1  0x000055b198e24c5b hires_progress (cawbird + 0xb6c5b)                                                                         
#2  0x00007fefbbcc896a g_signal_emit_valist (libgobject-2.0.so.0 + 0x2f96a)                                                       
...
```

**Comment by lucaswerkmeister** [comment]
The error happens on this source code line:
```c
gtk_image_set_from_surface (GTK_IMAGE (self->image), media->surface_hires);
```
Where `GTK_IMAGE` (from `/usr/include/gtk-3.0/gtk/gtkimage.h`) is defined as:
```c
#define GTK_IMAGE(obj)                  (G_TYPE_CHECK_INSTANCE_CAST ((obj), GTK_TYPE_IMAGE, GtkImage))
```
So the `self->image` is not a `GtkImage`, apparently. (But it’s not a null pointer, either, at least not in gdb.)

**Comment by IBBoard** [comment]
Ah, that's interesting. I'm managing to trigger it by quickly opening and closing an image. From that debug info, I wonder whether it happens when hires_progress gets called when the image widget has been disposed or some other kind of race condition.

If only C could tell you what type of object was in a variable, like any sane and sensible helpful modern programming language!

**Comment by lucaswerkmeister** [comment]
Yeah, there seem to be some helper GLib/GObject-gdb-integration things installed, but they’re not quite working properly:

```
Core was generated by `/usr/bin/cawbird --gapplication-service'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fefbbccdc3c in g_type_check_instance_cast () from /usr/lib/libgobject-2.0.so.0
[Current thread is 1 (Thread 0x7fefb84a2980 (LWP 7001))]
(gdb) up 1
#1  0x000055b198e24c5b in hires_progress (media=0x55b19bd6ac30, user_data=0x55b199a6caa0) at ../src/CbMediaImageWidget.c:98
warning: Source file is more recent than executable.
98        gtk_image_set_from_surface (GTK_IMAGE (self->image), media->surface_hires);
(gdb) p self
$1 = 0x55b199a6caa0
(gdb) p self->image
$2 = 0x55b19d5fbfa0
(gdb) p self->image->parent_instance
$3 = {g_type_instance = {Python Exception <class 'gdb.error'> No type named TypeNode.: 
g_class = }, ref_count = 2640297632, qdata = 0x55b19d5fbe80}
(gdb) p self->image->parent_instance->g_type_instance
$4 = {Python Exception <class 'gdb.error'> No type named TypeNode.: 
g_class = }
(gdb) p self->image->parent_instance->g_type_instance->g_class
Python Exception <class 'gdb.error'> No type named TypeNode.: 
$5 = 
```

(Member chain obtained with a bunch of `ptype`s.)

**Comment by lucaswerkmeister** [comment]
Patch for debugging:
```diff
diff --git a/src/CbMediaImageWidget.c b/src/CbMediaImageWidget.c
index 08359ee4..be122f62 100644
--- a/src/CbMediaImageWidget.c
+++ b/src/CbMediaImageWidget.c
@@ -95,6 +95,9 @@ hires_progress (CbMedia *media, gpointer user_data) {
     return;
   }
   CbMediaImageWidget *self = CB_MEDIA_IMAGE_WIDGET(user_data);
+  if (!GTK_IS_IMAGE (self->image)) {
+    self->image = gtk_image_new ();
+  }
   gtk_image_set_from_surface (GTK_IMAGE (self->image), media->surface_hires);
   cairo_surface_destroy(self->image_surface);
   self->image_surface = NULL;
```
(The content of the `if` is arbitrary nonsense because I don’t know what I’m doing.) With `b ../src/CbMediaImageWidget.c:99`:
```
Thread 1 "cawbird" hit Breakpoint 1, hires_progress (media=0x55555882d400, user_data=0x555555f0a710) at ../src/CbMediaImageWidget.c:99
99      ../src/CbMediaImageWidget.c: No such file or directory.
(gdb) p self->image
$1 = 0x5555584099e0
(gdb) p self->image->parent_instance
$2 = {g_type_instance = {g_class = <error reading variable: Cannot access memory at address 0x0>}, ref_count = 0, qdata = 0x0}
(gdb) p (void*)self->image->parent_instance
$3 = (void *) 0x0
```
So the `self->image` is still valid memory, but its `parent_instance` became null.

**Comment by IBBoard** [comment]
Which fits for a "triggered after closing" or "triggered before setup is complete" race condition. Obviously I'm doing something wrong.

…

*lightbulb* Huh. CbMediaWidget hooks in to `hires-progress` events *before* setting the image's Cairo surface. That's to make sure that we don't miss a quick loading that was triggered by the MediaDialog's attempts to pre-load the entire set of images (which would leave us showing a low-res image when the high-res image had been loaded independently). But I wonder if that means that it can get into a race condition where the widget isn't parented properly yet.

**Comment by lucaswerkmeister** [comment]
I suspected that `cb_media_image_widget_new` might add the hook before `cb_media_image_widget_init` has initialized the image, but that doesn’t seem to be the case:

```
Lucas: cb_media_image_widget_new                                                                                                                  
Lucas: cb_media_image_widget_init                                                                                                                 
Lucas: cb_media_image_widget_init: set self->image                                                                                                
Lucas: cb_media_image_widget_new: connected hires-progress                                                                                        
Lucas: hires_progress                                                                                                                             
Lucas: hires_progress                                                                                                                             
Lucas: hires_progress                                                                                                                             
Lucas: hires_progress                                                                                                                             
```
(There are a *lot* of `hires_progress` messages after that.) And then eventually, with no other debug message except more ` hires_progress`, `gdb` hits the breakpoint:
```c
g_print("Lucas: hires_progress: self->image is not GtkImage, returning\n");
```
So it looks to me like it’s more likely in teardown than setup.

<details>
<summary>Debug patch</summary>

```diff
diff --git a/src/CbMediaImageWidget.c b/src/CbMediaImageWidget.c
index 08359ee4..e87c073e 100644
--- a/src/CbMediaImageWidget.c
+++ b/src/CbMediaImageWidget.c
@@ -79,7 +79,9 @@ cb_media_image_widget_class_init (CbMediaImageWidgetClass *klass)
 static void
 cb_media_image_widget_init (CbMediaImageWidget *self)
 {
+  g_print("Lucas: cb_media_image_widget_init\n");
   self->image = gtk_image_new ();
+  g_print("Lucas: cb_media_image_widget_init: set self->image\n");
   gtk_container_add (GTK_CONTAINER (self), self->image);
 
   self->drag_gesture = gtk_gesture_drag_new (GTK_WIDGET (self));
@@ -91,10 +93,15 @@ cb_media_image_widget_init (CbMediaImageWidget *self)
 
 void
 hires_progress (CbMedia *media, gpointer user_data) {
+  g_print("Lucas: hires_progress\n");
   if (!media->loaded_hires) {
     return;
   }
   CbMediaImageWidget *self = CB_MEDIA_IMAGE_WIDGET(user_data);
+  if (!GTK_IS_IMAGE (self->image)) {
+    g_print("Lucas: hires_progress: self->image is not GtkImage, returning\n");
+    return; // not the right thing to do but better than nothing?
+  }
   gtk_image_set_from_surface (GTK_IMAGE (self->image), media->surface_hires);
   cairo_surface_destroy(self->image_surface);
   self->image_surface = NULL;
@@ -107,6 +114,8 @@ cb_media_image_widget_new (CbMedia *media, GdkRectangle *max_dimensions)
   int win_width;
   int win_height;
 
+  g_print("Lucas: cb_media_image_widget_new\n");
+
   g_return_val_if_fail (CB_IS_MEDIA (media), NULL);
   g_return_val_if_fail (!media->invalid, NULL);
   g_return_val_if_fail (media->surface != NULL, NULL);
@@ -123,6 +132,7 @@ cb_media_image_widget_new (CbMedia *media, GdkRectangle *max_dimensions)
     double scale_width = media->width * 1.0 / media->thumb_width;
     double scale_height = media->height * 1.0 / media->thumb_height;
     g_signal_connect(media, "hires-progress", G_CALLBACK(hires_progress), self);
+    g_print("Lucas: cb_media_image_widget_new: connected hires-progress\n");
     self->image_surface = cairo_image_surface_create(cairo_image_surface_get_format(media->surface), media->width, media->height);
     cairo_t *ct = cairo_create(self->image_surface);
     cairo_scale(ct, scale_width, scale_height);
@@ -154,4 +164,4 @@ cb_media_image_widget_new (CbMedia *media, GdkRectangle *max_dimensions)
   atk_object_set_description(gtk_widget_get_accessible(GTK_WIDGET(self)), media->alt_text == NULL ? "" : media->alt_text);
 
   return GTK_WIDGET (self);
-}
\ No newline at end of file
+}
```

</details>

**Comment by lucaswerkmeister** [comment]
(If I hit `c` and let the process continue with the early return, the breakpoint is hit three more times, then cawbird returns to the regular timeline. That seems like a suspiciously large volume of calls to `hires_progress`.)

**Comment by lucaswerkmeister** [comment]
Yup, `hires_progress` is being called after teardown of the surrounding widget:
```
Lucas: cb_media_image_widget_init, self = 0x555555f0adf0
Lucas: cb_media_image_widget_init: set self->image
Lucas: cb_media_image_widget_new, self = 0x555555f0adf0
Lucas: cb_media_image_widget_new: connected hires-progress
Lucas: cb_media_image_widget_finalize, self = 0x555555f0adf0
Lucas: hires_progress, self = 0x555555f0adf0
Lucas: hires_progress: self->image is not GtkImage, returning
```

**Comment by IBBoard** [comment]
Cool, thanks for tracking that down. Hopefully it'll be an easy fix to remove the hook (when I get to it)!

Is your `hires_progress` logging after the "is hires loaded" check? libsoup does load in chunks, so we should get multiple calls but only one (but we might get a "progress" value of 100% twice - one when loading finishes and one when we then call the "completed" function to make sure there wasn't a rounding error) that passes. If not then I need to work out what's hooking multiple events.

**Comment by lucaswerkmeister** [comment]
> Is your `hires_progress` logging after the "is hires loaded" check?

That logging was before the check, at least when it was a lot of lines being printed. (I later moved it down, below the `self` assignment, so I could print the pointer.)

---

I now tried out this patch:
```diff
diff --git a/src/CbMediaImageWidget.c b/src/CbMediaImageWidget.c
index 08359ee4..154a6839 100644
--- a/src/CbMediaImageWidget.c
+++ b/src/CbMediaImageWidget.c
@@ -28,6 +28,8 @@ cb_media_image_widget_finalize (GObject *object)
     cairo_surface_destroy(self->image_surface);
   }
 
+  g_signal_handler_disconnect (self->media, self->hires_progress_id);
+
   G_OBJECT_CLASS (cb_media_image_widget_parent_class)->finalize (object);
 }
 
@@ -122,7 +124,8 @@ cb_media_image_widget_new (CbMedia *media, GdkRectangle *max_dimensions)
   else {
     double scale_width = media->width * 1.0 / media->thumb_width;
     double scale_height = media->height * 1.0 / media->thumb_height;
-    g_signal_connect(media, "hires-progress", G_CALLBACK(hires_progress), self);
+    self->media = media;
+    self->hires_progress_id = g_signal_connect(media, "hires-progress", G_CALLBACK(hires_progress), self);
     self->image_surface = cairo_image_surface_create(cairo_image_surface_get_format(media->surface), media->width, media->height);
     cairo_t *ct = cairo_create(self->image_surface);
     cairo_scale(ct, scale_width, scale_height);
diff --git a/src/CbMediaImageWidget.h b/src/CbMediaImageWidget.h
index 9017c3e8..bfcdbc5e 100644
--- a/src/CbMediaImageWidget.h
+++ b/src/CbMediaImageWidget.h
@@ -39,6 +39,9 @@ struct _CbMediaImageWidget
 
   gulong hadj_changed_id;
   gulong vadj_changed_id;
+
+  CbMedia *media;
+  gulong hires_progress_id;
 };
 typedef struct _CbMediaImageWidget CbMediaImageWidget;
 
```

It *seems* to get rid of the “`hires_progress` called when `self->image` is not a `GtkImage`” error case – the breakpoint is no longer hit. It also prints some suspicious messages, though:

```
(cawbird:13788): GLib-GObject-WARNING **: 14:39:07.068: invalid (NULL) pointer instance

(cawbird:13788): GLib-GObject-CRITICAL **: 14:39:07.068: g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
```

(Side note, I also noticed the `hadj_changed_id` and `vadj_changed_id` in `struct _CbMediaImageWidget` are unused since 4ddcf1c1254cac8f808180eed939a60ce8115d3a.)

**Comment by IBBoard** [comment]
> I now tried out this patch:
> …
> It seems to get rid of the “hires_progress called when self->image is not a GtkImage” error case – the breakpoint is no longer hit.

Yeah, I was looking at the GObject signal docs and it says in "[memory management](https://developer.gnome.org/gobject/stable/gobject-Signals.html#signal-memory-management)" that we should use `g_signal_handler_disconnect`. That's probably the solution 🙂 Although slightly annoying that we need to track the media with it as well.

> It also prints some suspicious messages, though…

That might be from when it doesn't fall through to the `else`. Before disconnecting, check whether it is zero. If it is then there's nothing to disconnect in the finalize method.

If that fixes the warnings and the rest of the patch fixes the bug then submit a pull request and I'll merge your fix.

> (Side note, I also noticed the hadj_changed_id and vadj_changed_id in struct _CbMediaImageWidget are unused since 4ddcf1c.)

I hadn't seen any warnings about it, but yeah, it probably isn't. We always load at the top now.

**Comment by IBBoard** [comment]
Trying to work out why we need to track and manually disconnect here and not in other places.

I *think* it's because of the line about:

> While signal handlers are automatically disconnected when the object emitting the signal is finalised, they are not automatically disconnected when the signal handler user data is destroyed. 

The `CbMedia` isn't destroyed, but the `user_data` is the widget in this case, and it *does* get finalised/destroyed, so the auto-disconnect doesn't happen and we trigger it when we're in an invalid state.

Meanwhile, the other all of the other connections (except to the network monitor in `CbUserStream` are probably on GObjects that get disposed before the user data, and so it automatically disconnects without causing problems.

**Comment by lucaswerkmeister** [comment]
Checking the handler ID / media seems to fix the warnings, yes. (I wasn’t sure which would be better so I’m checking both.) Uploaded #197.
