### ISSUE TITLE
Unstable debian/ubuntu builds are incomplete

### ISSUE THREAD

**Issue by j1warren** [IBBoard/cawbird#198]
They are 4.3 kB

```
$ dpkg-deb -c cawbird-unstable_1.2.0-1+45.1_amd64.deb 
drwxr-xr-x root/root         0 2020-09-17 22:42 ./
drwxr-xr-x root/root         0 2020-09-17 22:42 ./usr/
drwxr-xr-x root/root         0 2020-09-17 22:42 ./usr/share/
drwxr-xr-x root/root         0 2020-09-17 22:42 ./usr/share/doc/
drwxr-xr-x root/root         0 2020-09-17 22:42 ./usr/share/doc/cawbird-unstable/
-rw-r--r-- root/root      3121 2020-09-17 22:42 ./usr/share/doc/cawbird-unstable/changelog.Debian.gz
```

**Comment by IBBoard** [comment]
Ugh, I didn't check the details, just that it built. It's mainly Open Build Service magic to convert RPM spec files to DEB files, so I'll have to see what I've done wrong in the renaming.

**Comment by IBBoard** [comment]
Apparently the end of the `DESTDIR` variable in the `override_dh_auto_install` command has to match the name of the project. Because that's obvious and necessary 🙄

One of the builds appears to be correct now (480KB) and the others should be done soon.
