### ISSUE TITLE
Auto Scroll not working anymore

### ISSUE THREAD

**Issue by mfauvain** [IBBoard/cawbird#205]
Since last upgrade (1.2.1) auto scroll on new tweets does not work anymore.
I don't see any obvious errors in the logs though..

**Comment by IBBoard** [comment]
So v1.2.0 was fine but v1.2.1 doesn't scroll up any more?

**Comment by mfauvain** [comment]
yes sir

**Comment by IBBoard** [comment]
I've just tested Master and it seems to be working for me.

1. Enabled Settings > Interface > Auto scroll on new tweets
1. Scroll to top of list
1. Wait for new tweet to come in
1. Tweet is now in view

**Comment by mfauvain** [comment]
On my side I did not change the setting and it is still as you say.
![20201102_133254](https://user-images.githubusercontent.com/14844435/97910855-f65df600-1d0f-11eb-8b87-6b396a844158.jpg)

However, scrolling up to the latest tweet and waiting a few minutes I see
![20201102_133632](https://user-images.githubusercontent.com/14844435/97911414-d3801180-1d10-11eb-9ce1-24922378cbf5.jpg)

however, tweets were received (i see the scrollbar on the right being lower)
and if I scroll again up I see
![20201102_133648](https://user-images.githubusercontent.com/14844435/97911541-0924fa80-1d11-11eb-9f1c-949c591c35fe.jpg)

**Comment by mfauvain** [comment]
Also adding that I have the same issue on two different machines.

**Comment by IBBoard** [comment]
Okay. What OS and desktop environment is this? I don't recognise the theme.

Can you build and test a debug version? There's not going to be anything in the code to help debug this at the moment, but I can make a branch with temporary debugging in it if you can compile and run it to test.

**Comment by mfauvain** [comment]
Arch (kernel 5.9.3) and gnome 3.38 with my own theme. I can certainly build a debug version, where do I find it?

**Comment by IBBoard** [comment]
I'll create a branch and put some debugging in.

And just to check, you're using [Cawbird](https://www.archlinux.org/packages/community/x86_64/cawbird/) from Arch, not [Cawbird-git](https://aur.archlinux.org/packages/cawbird-git/) from AUR (which is 1.2.1 plus any later changes)?

**Comment by mfauvain** [comment]
ah, good point, cawbird-git indeed...

**Comment by IBBoard** [comment]
I altered some logic recently to prevent an extra call on the API. I've swapped the logic order now so that auto-scroll takes priority. That should fix it.

(And I *wasn't* using full master - just my own dev version that's normally close to master, which is why I didn't see it at first)

**Comment by mfauvain** [comment]
Thx for the help. I moved back to plain cawbird and it works.
