### ISSUE TITLE
gpg: invalid key resource url '/etc/apt/trusted.gpg.d/home:ibboard:cawbird.gpg'

### ISSUE THREAD

**Issue by jwhowarth** [IBBoard/cawbird#206]
The current instructions for installing the cawbird repo on Xubuntu 20.04 results in the installation of a broken gpg file which blocks any further keys being installed until the bad cawbird key is removed.

**To Reproduce**
1. Install Ubuntu 20.04 and follow the recommended steps for enabling the cawbird repo from https://software.opensuse.org/download.html?project=home%3AIBBoard%3Acawbird&package=cawbird for Xubuntu 20.04...
```
echo 'deb http://download.opensuse.org/repositories/home:/IBBoard:/cawbird/xUbuntu_20.04/ /' | sudo tee /etc/apt/sources.list.d/home:IBBoard:cawbird.list
curl -fsSL https://download.opensuse.org/repositories/home:IBBoard:cawbird/xUbuntu_20.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home:IBBoard:cawbird.gpg > /dev/null
```
2. Now in a terminal execute...
`sudo apt-key list`
and you will find the cawbird key is not listed in the installed keys despite the presence of the home:IBBoard:cawbird.gpg file in /etc/apt/trusted.gpg.d.

3. The next time you try to add a new key for any another repository, this will fail, due to the bad cawbird key, with the error...

gpg: invalid key resource url '/etc/apt/trusted.gpg.d/home:ibboard:cawbird.gpg'

4. One has to remove the offending /etc/apt/trusted.gpg.d/home:ibboard:cawbird.gpg key file for additional keys for other repos to be installed.

**System details:**
 - OS: Ubuntu 20.04
 - Version: N/A
 - Package type: N/A

**Additional context**

Running `sudo apt-key list` can give useful debug output.

**Comment by IBBoard** [comment]
We have no control over those instructions. They're auto-generated by OBS.

What's in the file? Is it a key or is it some other content? What steps do you actually take to get it to install on Xubuntu? (Because presumably you need a key from somewhere to check the signatures)

**Comment by IBBoard** [comment]
No-one else has reported having this problem, and I'd have thought that Ubuntu 20.04 would have a reasonable number of users.

Until someone can recreate it and give me more info then I'm going to close this.
