### ISSUE TITLE
missing 'Reply' icon in tweets

### ISSUE THREAD

**Issue by mfauvain** [IBBoard/cawbird#208]
I am missing the reply icon as below
![20201104_151342](https://user-images.githubusercontent.com/14844435/98168877-de71a800-1eb0-11eb-9fdc-96058a856969.jpg)
Can you tell me the name of the icon it is pointing to?

**Comment by IBBoard** [comment]
Apparently it is "mail-replied-symbolic" - https://github.com/IBBoard/cawbird/blob/master/ui/tweet-list-entry.ui#L92

I don't know whether it's standardised. It's what baedert used. It probably makes sense to bundle it, though.

**Comment by mfauvain** [comment]
thx
