### ISSUE TITLE
Application settings unavailable and open out of reach if using shortcut

### ISSUE THREAD

**Issue by arsenicks** [IBBoard/cawbird#209]
**Describe the bug**
I just want to check the settings of the application and the gear just doesn't show in the bar.

**To Reproduce**
1. Open the app
2. Autorize witter account
3. Look for settings gear next to the username, not there
4. Trying using the shortcut CRTL+SHIFT+P, I see the windows goes off focus but no window open in view. I see the window has been open off screen, I can't reach it.

**Expected behavior**
I expect to see the gear to access settings like here: https://cdn.fosslinux.com/wp-content/uploads/2020/01/20105659/cawbird_if.png

Get a popup when using the shortcut key: CRTL+SHIFT+P a popup seems to open but it's out of my screens.

**Screenshots**

**System details:**
 - OS: Ubuntu 18.04.5 LTS
 - 4 monitors setup
 - Version: 1.2.1-1+7.4 AMD64
 - Package type: Installed from repo using this:
echo 'deb http://download.opensuse.org/repositories/home:/IBBoard:/cawbird/xUbuntu_18.04/ /' | sudo tee /etc/apt/sources.list.d/home:IBBoard:cawbird.list
curl -fsSL https://download.opensuse.org/repositories/home:IBBoard:cawbird/xUbuntu_18.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home:IBBoard:cawbird.gpg > /dev/null
sudo apt update
sudo apt install cawbird

**Additional context**

ROutput of running with `G_MESSAGES_DEBUG=cawbird`:

```
(cawbird:329): cawbird-DEBUG: 09:41:54.090: Cawbird.vala:266: startup

(cawbird:329): cawbird-WARNING **: 09:41:54.097: Utils.vala:87: Failed to open file '/home/USERNAME/.config/cawbird/accounts/157888888_small.png': No such file or directory

(cawbird:329): cawbird-WARNING **: 09:41:54.097: Utils.vala:87: Failed to open file '/home/USERNAME/.config/cawbird/accounts/157888888.png': No such file or directory

(cawbird:329): cawbird-WARNING **: 09:41:54.097: Cawbird.vala:435: Could not add window for account 'screen_name'

(cawbird:329): Gdk-CRITICAL **: 09:41:54.102: gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed
(cawbird:329): cawbird-DEBUG: 09:41:54.222: Creating stream for TWITTERUSER
(cawbird:329): cawbird-DEBUG: 09:41:54.226: Loading timeline tweets on start
(cawbird:329): cawbird-DEBUG: 09:41:54.226: Loading timeline tweets
(cawbird:329): cawbird-DEBUG: 09:41:54.227: Loading mention tweets on start
(cawbird:329): cawbird-DEBUG: 09:41:54.227: Loading mention tweets
(cawbird:329): cawbird-DEBUG: 09:41:54.227: Loading favourited tweets on start
(cawbird:329): cawbird-DEBUG: 09:41:54.227: Loading favourited tweets
(cawbird:329): cawbird-DEBUG: 09:41:54.227: Loading DMs on start
(cawbird:329): cawbird-DEBUG: 09:41:54.227: Loading DM tweets
(cawbird:329): cawbird-DEBUG: 09:41:54.227: Adding timeout for timeline
(cawbird:329): cawbird-DEBUG: 09:41:54.227: Adding timeout for mentions
(cawbird:329): cawbird-DEBUG: 09:41:54.227: Adding timeout for favourites
(cawbird:329): cawbird-DEBUG: 09:41:54.227: Adding timeout for DMs

(cawbird:329): Gtk-WARNING **: 09:41:54.253: ../../../../gtk/gtkwidget.c:8584: widget not within a GtkWindow
(cawbird:329): cawbird-DEBUG: 09:41:54.590: Got 0 mention tweets
(cawbird:329): cawbird-DEBUG: 09:41:54.606: Account.vala:518: Add 1 disabled_rts ids
(cawbird:329): cawbird-DEBUG: 09:41:54.608: Account.vala:318: Using http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png to update the avatar(old: http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png)
(cawbird:329): cawbird-DEBUG: 09:41:54.663: Account.vala:487: Add 2 blocked ids
(cawbird:329): cawbird-DEBUG: 09:41:54.677: Account.vala:456: Add 0 muted ids

(cawbird:329): cawbird-CRITICAL **: 09:41:54.692: Account.vala:340: Unrecognized image file format

(cawbird:329): cawbird-CRITICAL **: 09:41:54.696: main_window_account_info_changed: assertion 'small_avatar != NULL' failed

(cawbird:329): cawbird-CRITICAL **: 09:41:54.696: __lambda143_: assertion 'nop != NULL' failed
(cawbird:329): cawbird-DEBUG: 09:41:54.793: Got 28 timeline tweets
(cawbird:329): cawbird-DEBUG: 09:41:55.048: Got 0 DMs
(cawbird:329): cawbird-DEBUG: 09:41:55.053: Got 28 favourited tweets
```

**Comment by arsenicks** [comment]
FYI, I was able to get the setting back on screen using: ALT + spacebar  and maximise the window, then replace. But I still don't see the gear icon to get there.

**Comment by IBBoard** [comment]
What desktop are you using? And do you see the other buttons?

We had this before in the Flatpak build (#75) and I just put it down to Flatpak doing something wrong (again).

The first couple of warnings aren't important and probably just mean that we've not cached your avatar. However this seems odd:

```
(cawbird:329): cawbird-WARNING **: 09:41:54.097: Cawbird.vala:435: Could not add window for account 'screen_name'

(cawbird:329): Gdk-CRITICAL **: 09:41:54.102: gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed
```

It should just mean that there's an account in the auto-start list that's now not configured (and we've not cleared it out).

Can you try the [debugging steps](https://github.com/IBBoard/cawbird/issues/75#issuecomment-575780789) and see whether the button is completely missing again?

**Comment by IBBoard** [comment]
Can you test the `bug209-missing-settings-button` branch as well and see what it logs about the app menu?

**Comment by IBBoard** [comment]
With the window opening out of reach, Baedert wrote it so that we save the position of the settings dialog. I don't know why. You said you've got four monitors. This may not work now that you've managed to get it on to a visible screen, but what do you get when you run `gsettings get uk.co.ibboard.cawbird settings-geometry`?

It could be that something got rearranged and the last position of your settings window is now WAY off-screen.

**Comment by arsenicks** [comment]
Hi thanks for the reply @IBBoard, the issue is now resolved but unfortunetely, I won't be able to provide details... The only thing I can say is that I've completed the upgrade from ubuntu 18.04 to 20.04.1 and after that it worked. I didn't even noticed it before seeing your reply and looking at it.

So I guess it came from a lib or my specific setup before the upgrade.. Sorry I didn't saw the reply before upgrading.. I'm not sure if I was using xorg or wayland before, but I tink it was xorg too.

here's where I'm right now:
 loginctl show-session 2 -p Type
Type=x11

For what is woth here's the output of gsettings:
$ gsettings get uk.co.ibboard.cawbird settings-geometry
(1180, 473, 500, 300)

**Comment by IBBoard** [comment]
I've just inverted the `Gtk.Settings.get_default ().gtk_shell_shows_app_menu` check in `MainWindow.vala` and I can recreate the "no button" part of the bug. But as I don't know how to make a platform have `Gtk.Settings.get_default ().gtk_shell_shows_app_menu == true` then I can't tell whether it's expected behaviour and the menu was just elsewhere all along.

Until someone can create the problem then I'm going to assume that the settings being off-screen was a local geometry issue.

I'll close this until someone can give me a reproducible environment to check more details in. If it affected Ubuntu 18.04 but not 20.04 then I suspect it's going to become less and less of a problem anyway.
