### ISSUE TITLE
Please add a feature to modify text size.

### ISSUE THREAD

**Issue by dsancheznet** [IBBoard/cawbird#210]
On some screens ( specially hiDPI screens ) the text is tiny and very difficult to read. 

Please add a feature to select another font size for the tweeds or alternatively ( like telegram doas ) allow to choose a default zoom level for the whole interface.

Best Regards
D.Sánchez

**Comment by IBBoard** [comment]
This is already covered in #33. We use the system theme, so if the font size is too small then for now please adjust your theme. There is also a command that uses environment variables for GTK etc to adjust the font scaling.
