### ISSUE TITLE
question: possible to use read only?

### ISSUE THREAD

**Issue by lonix1** [IBBoard/cawbird#216]
Question.

Is it possible to use the app in "read only" mode? i.e. without logging in?

Twitter is usable even by those who don't have accounts.

**Comment by CodedOre** [comment]
**Quick answer:** No.

**Long answer:**
Technically yes, as the Twitter API theoretically allows for API-Calls made over an token created for the app.

However this token authentication only allows for a very small set of actions before the rate limit kicks in. At the end it is supposed for non-interactive use, such as programs analyzing tweets, not to be a "do not log in"-option.

**Comment by IBBoard** [comment]
Duplicate of #146
