### ISSUE TITLE
Cawbirds failed on --help

### ISSUE THREAD

**Issue by Symbian9** [IBBoard/cawbird#246]
**Describe the bug**

Seems like Cawbird failed to show help info for `--help`

**To Reproduce**

1. Open terminal;
2. Type `$ cawbird --help`
3. See error

**Expected behavior**

Cawbird CLI should provide output for `--help`, same as for `-h`.

**Screenshots**

![pic](https://i.imgur.com/pPk8U8t.png)

**System details:**

 - OS: Debian 10/Xfce4 (MX Linux MX-19.x)
 - Version: `1.2.1`
 - Package type: MX Linux MX-19 distro package

**Additional context**

Running `G_MESSAGES_DEBUG=cawbird cawbird` can give useful debug output.

**Comment by IBBoard** [comment]
Huh. Not a clue what even handles that. I think we just hand it all off to GTK and other libraries to deal with.

**Comment by IBBoard** [comment]
From a quick bit of testing, `--help` works for me. BUT only when the app is closed.

If the app is already running then `cawbird --help` (or `cawbird -h`) return the DBus error and Cawbird then dumps the help info to the console that launched Cawbird (or into the void if you started it from a shortcut etc).
