### ISSUE TITLE
Can't compile with video disabled

### ISSUE THREAD

**Issue by leyhline** [IBBoard/cawbird#273]
**Describe the bug**
I build cawbird myself without video support to avoid the GStreamer dependency. But since version 1.3.* I get an error when running `ninja`.

**To Reproduce**
1. Don't have GStreamer installed, I guess.
2. I edited `meson_options.txt` in this way: `option('video',      type: 'boolean', value: 'false')`
3. `meson build` works
4. `ninja -C build` throws a compilation error:

```
../src/util/Utils.vala:121.18-121.20: error: The symbol `Gst' could not be found
    var sink = ((Gst.Bin)playbin).get_by_name("sink");
                 ^^^
../src/util/Utils.vala:122.5-122.7: error: The symbol `Gst' could not be found
    Gst.Sample sample;
    ^^^
../src/util/Utils.vala:131.13-131.15: error: The symbol `Gst' could not be found
    unowned Gst.Structure structure = sample_caps.get_structure(0);
            ^^^
Compilation failed: 3 error(s), 0 warning(s)
ninja: build stopped: subcommand failed.
```

**Expected behavior**
Seems like there is some Vala module for GStreamer that needs to be present even when video is disabled. But it should compile completely without GStreamer.

**System details:**
 - OS: Gentoo Linux
 - Version: 5.4.80-gentoo-r1
 - Package type: Git Repo, tried tag v1.3 and v1.3.1

By the way, I never really understood where to pass `--disable-video` like it's mentioned in the README. :sweat_smile: 

Anyway, great work. I have been using cawbird throughout last year and really enjoyed it.

**Comment by IBBoard** [comment]
Sorry, my oversight when I added in the "upload videos" functionality.

It should now be fixed, and as a bonus feature it will now open videos in the default browser rather than unhelpfully opening a media window with the thumbnail image that never gets beyond the greyed out "loading" state.

I've also updated the documentation.

**Comment by leyhline** [comment]
So fast! Thank you.
