### ISSUE TITLE
Open tweet by searching for tweet URL

### ISSUE THREAD

**Issue by philipzae** [IBBoard/cawbird#275]
It would be nice to be able to easily jump to a tweet which i've copied its URL from twitter by clicking the search tab and then pasting the URL. This is somewhat related to #245, which is to jump to the tweet on launching of cawbird.

![image](https://user-images.githubusercontent.com/4412114/104608677-9bdfff00-569b-11eb-96a5-e47960583595.png)

**Comment by IBBoard** [comment]
#245 wasn't just about opening it at launch (although the command-line was one way that we were going to allow people to open URLs). But I think that handling this special case may be useful.

It's probably worth noting that searching a tweet URL finds all the tweets that quote-tweet that URL, though. So we shouldn't completely override the search behaviour - just make sure that that tweet is in the list.

Probably best to keep this as part of #245 and incorporate it into the "what UI do we need that is obvious to people" discussion.
