### ISSUE TITLE
some tests fail when ~/.config doesn't exist

### ISSUE THREAD

**Issue by paper42** [IBBoard/cawbird#276]
**Describe the bug**
`friends` and `usercounter` tests fail when `~/.config` doesn't exist. This can happen in build systems.

```
%: ./friends
# random seed: R02S12591e2953fe3146e9906ea33b7c9758
# GLib-GIO-DEBUG: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ?gio-vfs?
Bail out! cawbird-FATAL-CRITICAL: Dirs.vala:62: Error creating directory /tmp/.config/cawbird: No such file or directory(/tmp/.config/cawbird/)

(./friends:19033): cawbird-CRITICAL **: 18:21:49.499: Dirs.vala:62: Error creating directory /tmp/.config/cawbird: No such file or directory(/tmp/.config/cawbird/)
Trace/breakpoint trap (core dumped)
```

**To Reproduce**
1. change home to a temporary directory without `~/.config`
1. run `meson test`

**Expected behavior**
tests run without problems

**System details:**
 - OS: Void Linux
 - Version: 1.3.1
 - Package type: custom build

**Comment by IBBoard** [comment]
That's annoying. I've not looked, but I suspect it'll be hard to avoid that, because some of our tests need the database, which we store in the config dir. We might just have to create `~/.config` if it doesn't exist, but that feels ugly.

In the mean time, I guess people's build spec files need to create `~/.config` manually at some point before running `meson test`.

**Comment by IBBoard** [comment]
I've just checked [the code](https://github.com/IBBoard/cawbird/blob/master/src/util/Dirs.vala) and it looks like we're (correctly) using the home directory or the user config dir. The user config dir is [$XDG_CONFIG_HOME](https://developer.gnome.org/glib/stable/glib-Miscellaneous-Utility-Functions.html#g-get-user-config-dir).

I think it's fairly normal to assume that the `XDG_…` variables exist. Which makes me think that this is something that the build environment should be setting and isn't our bug. If you point apps to XDG directories that don't exist then they're going to fail!

**Comment by paper42** [comment]
It's not guaranteed in build systems, but it's easy to fix. Thanks.

**Comment by IBBoard** [comment]
It may not be guaranteed by default, but I think it's a reasonable thing to assume is correct when you're working with a desktop app 🙂
