### ISSUE TITLE
Error performing TLS handshake

### ISSUE THREAD

**Issue by Brog33** [IBBoard/cawbird#278]
**Describe the bug**
Getting a lot of these "Error performing TLS handshake" the last days. Pressing retry or repeating the action usually fixes it.

![image](https://user-images.githubusercontent.com/1303537/104702423-47c63080-5716-11eb-9dd9-474722a4c1bc.png)

**To Reproduce**
Like a tweet, open a tweet, do most actions that communicates with the server. Happens regularly but not all the time.

**System details:**
 - OS: Ubuntu 20.04
 - Version: 1.3.1
 - Package type: Snap

**Comment by IBBoard** [comment]
That looks like #9, which is a GnuTLS problem that we put in workarounds for and they fixed a while back.

The Snap is a community maintained package. This looks like it's most likely diddlesnaps/cawbird#2
