### ISSUE TITLE
Suggestion: always position opened images at the top left

### ISSUE THREAD

**Issue by siebenmann** [IBBoard/cawbird#28]
Normally, Cawbird silently attempts to position an over-large image (one that you'll have to scroll around in) based on where in the image you clicked in your timeline view. I find this to be completely unpredictable and irritating behavior, because I don't precisely control where I click in timeline images; I just click somewhere on the image, wherever is convenient given my mouse position at the time. Thus I think it would be more predictable and less surprising (and puzzling) to always position over-large images at the top left.

**Comment by IBBoard** [comment]
Double-checked the size. Twitter scales to 1200px max, hence why I haven't seen scrolling on a 1440p monitor!

I've now removed all of the scrolling code for images (I think!).
