### ISSUE TITLE
Account name characters appearing outside of area

### ISSUE THREAD

**Issue by philipzae** [IBBoard/cawbird#289]
I saw scrolling through my timeline and noticed something not right with a person's account name.
![image](https://user-images.githubusercontent.com/4412114/104861250-80e5e700-5948-11eb-8539-3b38ba770c43.png)

How it looks on twitter.
![image](https://user-images.githubusercontent.com/4412114/104861186-3fedd280-5948-11eb-8127-34c30719cb48.png)

Here is the tweet https://twitter.com/omgubuntu/status/1350507465796964358

**Comment by IBBoard** [comment]
That's JWZ screwing around with multiple overlapping Unicode combining characters. Pango controls text rendering. I can't say whether the Pango approach is right or the Firefox/Chrome approach. Either way, we have no control over it.

If you want it fixed then you'll have to report it to Pango and see what they think the correct behaviour is (and whether they can be bothered fixing it or whether it's too much of a corner case).
