### ISSUE TITLE
On Mobian when try to play video there is an exception and error. Cawbird 1.3.2-1

### ISSUE THREAD

**Issue by m0jek** [IBBoard/cawbird#291]
**Describe the bug**
View a story in Twitter that has a video embedded.
Touch the video and it goes to try and play, but all one sees in the screen is one of the errors below;

(cawbird:3588): cawbird-CRITICAL **: 18:52:58.922: ../sys/v4l2codecs/gstv4l2codech264dec.c(939): gst_v4l2_codec_h264_dec_ensure_output_buffer (): /GstPlayBin:video/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0/v4l2slh264dec:v4l2slh264dec2

or

(cawbird:3588): cawbird-CRITICAL **: 18:52:58.923: ../gst-libs/gst/video/gstvideodecoder.c(1246): gst_video_decoder_sink_event_default (): /GstPlayBin:video/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0/v4l2slh264dec:v4l2slh264dec2:
no valid frames found

Touching screen takes you back to Cawbird, so at least there is no app crash.

**To Reproduce**
1. Go to 'view any tweet with video'
2. Click on 'on the video'
3. Scroll down to 'It will try to play but will then print teh error described above.'
4. See error: (cawbird:3588): cawbird-CRITICAL **: 18:52:58.922: ../sys/v4l2codecs/gstv4l2codech264dec.c(939): gst_v4l2_codec_h264_dec_ensure_output_buffer (): /GstPlayBin:video/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0/v4l2slh264dec:v4l2slh264dec2

**Expected behavior**
The video is expected to play

**Screenshots**

**System details:**
 - OS: Mobian based on Debian GNU/Linux bullseye/sid
 - Version: bullseye/sid
 - Package type: bistro package  http://repo.mobian-project.org mobian/main arm64 Packages

**Additional context**

Running `G_MESSAGES_DEBUG=cawbird cawbird` can give useful debug output.
Please see attached debug_log.txt
[debug_log.txt](https://github.com/IBBoard/cawbird/files/5839147/debug_log.txt)

**Comment by IBBoard** [comment]
That generally means that you're missing one of the video dependencies, like `libav`. You're definitely getting a lot of errors from `gst_v4l2_codec_h264_dec_ensure_output_buffer()`, and we just pass GStreamer a URL to play, so I think it's out of our control at that point. You might have more luck with the Mobian packager.

**Comment by m0jek** [comment]
thank you, I will follow up the mobian packager and/or build my own 
from source.

**Comment by m0jek** [comment]
I can add that videos play perfectly in firefox on mobian pinephone.
I know it is a different method ...

**Comment by IBBoard** [comment]
Yeah, Firefox will have its own codecs etc and I'm fairly sure that it doesn't use GStreamer because Firefox is cross-platform (my openSUSE package mentions nothing about it in the dependencies).

Building your own package shouldn't make much difference if you don't have the right dependencies. And because of the way that GStreamer and various packaging systems work, there's no convenient way to specify our codec dependencies in a way that Meson/Ninja or packaging systems can automatically use. So we just end up saying "you probably forgot libav" since that's what it normally is that used to be in GStreamer Bad but is now its own package.

**Comment by m0jek** [comment]
I have done more digging and as you said it does look like a GStreamer issue on my platform (Pinephone with mobian). I have checked that all libs and plugins and everything appears to be there.  Using the CLI was interesting. if do something like gst-play-1.0 <some media file> works a treat, however, if I do a gst-launcher-1.0 playbin uri=file:///<some media file> / location  see exactly the same errors I see from Cawbird.
I need to investigate this further. As this is a gstreamer issue, I will close this issue.

**Comment by IBBoard** [comment]
It's odd that gst-play would work but gst-launch doesn't, but then we recently had a video corruption bug (#279) where gst-play was fine but `gst-play-1.0 --videosink=gtksink …`  showed the corruption!

Good luck sorting the libraries.

**Comment by m0jek** [comment]
Hi,

Thank you for following up. Yes, the number of libs is daunting!

Just to start from a level playing field, Have set up a vanilla but latest Debian bullseye/sid VM. Installed Cawbird from OBS, and tested. Works perfectly. Okay, so architectures are different, but I see that the Debian VM has far less gstreamer related libs.

The next step is to build a virgin mobian image and then see what happens …

Kind Regards,

André Skarzynski, M0JEK
e: andresk@me.com / m0jek@me.com
EchoLink Node: 467471
RSGB | EPC #7975 | FH #2272 | DMC #2311 | BARTG #8283 | ERC #0396

**Comment by m0jek** [comment]
I would like to add to this thread that playing videos from tweets in Cawbird on my Pinephone running mobian is working now. I updated the Linux Kernel 5.11-sunxi64, and now all videos play as expected. I must also add that I am running mobian unstable, however, until now not using the 5.11 kernel.
