### ISSUE TITLE
Cawbird not opening links in default browser

### ISSUE THREAD

**Issue by philipzae** [IBBoard/cawbird#295]
I have Opera set as my default browser but when clicking links it still opens in Firefox.

Using `exo-open http://www.google.com/` opens in Opera.

**Comment by IBBoard** [comment]
What happens when you run `xdg-open https://www.google.com`? Is it Firefox or Opera?

Cawbird just calls `Gtk.show_uri_on_window`, which uses GIO/gvfs to find the appropriate app, which I think falls back to the Freedesktop default behaviour.

**Comment by philipzae** [comment]
It opens Opera.

**Comment by IBBoard** [comment]
Huh. I'll need to look in to what GIO/gvfs does and where it gets its settings from, then.

I'm fairly sure it's an external problem and not our issue. We've definitely not hard-coded a shell call to Firefox (even if it is the right browser to use 😉)

**Comment by philipzae** [comment]
I use 3 browsers. 1 for work, 1 for xfce work and 1 for xubuntu work. :smile:

Quite a strange behaviour as I have set it on one pc with Opera and it works fine, but on another pc it doesn't work. Both running Xubuntu 20.04 and in both I went to the settings and changed it back and forth from Opera to Firefox to see if that would fix it, but still didn't work.

**Comment by IBBoard** [comment]
Okay, what happens when you run `gio mime x-scheme-handler/http` and `gio mime x-scheme-handler/https`. Presumably those will represent what GTK does through GIO better than `xdg-open`!

I get:

```
Default application for “x-scheme-handler/http”: firefox.desktop
Registered applications:
	firefox.desktop
	chromium-browser.desktop
Recommended applications:
	firefox.desktop
	chromium-browser.desktop
```

(Source: [Someone trying to fix xfce](https://russellstinnett.com/2018/01/26/really-really-setting-default-browser-xfce/))

**Comment by philipzae** [comment]
![image](https://user-images.githubusercontent.com/4412114/105408067-ee935b00-5c47-11eb-9339-a5ff13a2a4a1.png)

**Comment by philipzae** [comment]
I filed a bug with xfce, as I presume this would be something that can be fixed from cawbird's side.
https://gitlab.xfce.org/xfce/xfce4-settings/-/issues/267

**Comment by IBBoard** [comment]
Yeah, if that's what `gio mime` reports then that's expected behaviour from the Cawbird side and nothing we can do. Something in your desktop isn't setting your preferred browser correctly (at least as far as gio is concerned)
