### ISSUE TITLE
Russian language not working in Flatpak on Arch

### ISSUE THREAD

**Issue by IBBoard** [IBBoard/cawbird#297]
**Describe the bug**
The Russian translation doesn't appear to be working in the Flatpak builds, but does in native (Arch AUR) builds.

**To Reproduce**
1. Install the Flatpak
2. `flatpak run --env=LC_ALL=ru_RU.utf8 uk.co.ibboard.cawbird`
3. Wait for Flatpak Cawbird to load
4. Install from native package repos (e.g. OBS or AUR)
5. `LC_ALL=ru_RU.utf8 uk.co.ibboard.cawbird`
6. Wait for native Cawbird to load

**Expected behavior**
Cawbird has a Russian language translation (now at ~100% completeness) and should show in Russian when opening the Flatpak (step 3), not just the native build (step 6)

**Screenshots**
https://twitter.com/GrawlCore/status/1351827193035452416

**System details:**
 - OS: Arch
 - Version: 1.3.2
 - Package type: Flatpak

**Additional context**

https://gist.github.com/Grawl/71a3eb980deffdc86f010b910a160e54

**Comment by IBBoard** [comment]
@p1u3o @CodedOre - any ideas?

Interestingly, there's an old ticket about Corebird(!) and problems with languages in that Flatpak (https://github.com/flatpak/flatpak/issues/1504). But I don't know why it would need custom commands to set up the language. Isn't Flatpak supposed to be user-friendly and just do that kind of thing?

**Comment by CodedOre** [comment]
So, this is what I can say for now:
Flatpak only loads the languages you use, not anyone. You can set that `flatpak config` to check it and `flatpak config --set extra-languages` to add languages.

That is at least the theory. Tried to check this here on my system, but it surprisingly worked only in the terminal and in the GTK-Inspector, not in Cawbird itself.

I suspect that I have done something wrong, as other flatpaks shown the same behavior and flatpak did load the language packs, so I do a try with a virtual machine set to Russian to confirm...

**Comment by IBBoard** [comment]
But they're saying that it works for other apps, which suggests that they *should* have Flatpak set up right for their language? https://twitter.com/GrawlCore/status/1351823236435214336

(Why it can't just be like "lang" packages, which have all the languages and load the right ones, I don't know!)

**Comment by CodedOre** [comment]
> (Why it can't just be like "lang" packages, which have all the languages and load the right ones, I don't know!)

Well, because you only use a few languages normally and why load a language set you don't use anyway? But you could activate all languages with `flatpak config --set languages all`.

---

Alright, here is the result of my Russian VM:

![Bildschirmfoto von 2021-01-20 21-42-03](https://user-images.githubusercontent.com/47981497/105232421-ad784980-5b68-11eb-917e-ed0a0e8a26f9.png)

Can confirm that the flatpak fails to load the translation. But it seems to install and run the right languages, as seen with the terminal. Also checked with my real system again and noticed that it not used my system language (which is German).

So somewhere in Cawbird it fails to load the languages when it is sandbox. At least I suspect that it has to do with the sandbox, given that the native packages works.

**Comment by IBBoard** [comment]
> So somewhere in Cawbird it fails to load the languages when it is sandbox. At least I suspect that it has to do with the sandbox, given that the native packages works.

Okay, that's interesting. At least we know it's consistent!

Who knows about Flatpak language handling and why we might not be loading them correctly? Is it because or languages are all "<lang-name>.po" whereas some systems have "<lang-name>/app.po" or similar? Or is it something we're not specifying correctly (or are specifying correctly, but Flatpak doesn't handle correctly)?

**Comment by CodedOre** [comment]
@alexlarsson and @barthalion, you are working on Flatpak, maybe you can help with this issue?

**Comment by Grawl** [comment]
Hello, I am here as translator and bug reporter from twitter.

Last time I work with translations on Transifex [I cannot save one of pluralized items](https://twitter.com/GrawlCore/status/1345951549735006211), even if I copied original text to translate. Now its translated and does not show me an error. But in last time, I checked other translations for similar errors and found them. I don't remember all of them but one of them was in the similar item I cannot save in Russian translate.

Maybe this info will be helpful.

**Comment by IBBoard** [comment]
Thanks for the comment. It's not the Transifex problem that is causing this. I fixed that and we have the full Russian translation available, but Flatpak doesn't appear to be loading *any* translations correctly.

(The translation problem was that we didn't have "%d" in the singular translation, but Transifex wasn't making it clear that that's what the problem was. I removed the "%d" for just the singular and it worked).

**Comment by barthalion** [comment]
Does it happen only with Cawbird or other apps too? What does `locale` and `locale -a` return for you on the host and in the sandbox? (The latter can be tested with `flatpak run --command=bash --filesystem=/etc/tlp.d org.freedesktop.Platform//20.08`.)

**Comment by CodedOre** [comment]
> Does it happen only with Cawbird or other apps too?

If you look at the image of my previous test with the "russian VM", there I installed Cawbird and Lollypop as Flatpak, with Lollypop using the right language and Cawbird not.

> What does `locale` and `locale -a` return for you on the host and in the sandbox? (The latter can be tested with `flatpak run --command=bash --filesystem=/etc/tlp.d org.freedesktop.Platform//20.08`.)

Will try to give you this data soon...

**Comment by CodedOre** [comment]
> What does `locale` and `locale -a` return for you on the host and in the sandbox?

Alright, on my system the output of `locale` is that it is set to german, and `locale -a` returns a bunch of languages that are installed on Fedora.

`locale` under the Freedesktop Runtime returns the same, with `locale -a` only the languages I set to install, as expected...

Maybe @Grawl as the original bug reporter could try this out as well, but I doubt it will show different results. The interesting thing is that the Cawbird flatpak does use localization in the shell, but not in the app itself...

**Comment by IBBoard** [comment]
I'm wondering whether it's to do with us having all of our language files as just `po/lang.po`. I've seen `po/lang/appname.po` in other apps. But I can't find any good references for how to get xgettext to work that way.

It should be equivalent to have them named as we do, and it works fine outside Flatpak, but it's the only obvious difference that I can see.

**Comment by barthalion** [comment]
Good catch, that must be it. Flatpak splits locales into extensions by matching files' names and paths. @IBBoard can you try adding `separate-locales: true` in the manifest? It's a top level key.

**Comment by IBBoard** [comment]
I'm not setup to build Flatpaks, so it's probably easier/more effective for someone else to test it rather than have me commit it on a bug branch and then wait for someone to test it.

Although, [the docs](https://docs.flatpak.org/en/latest/flatpak-builder-command-reference.html) suggest that the default value is "true" anyway. So shouldn't it be doing this already? Is there any easy way to check? And maybe some commands to compare how CodedOre's "correct" apps have their locale vs how we have it?

**Comment by CodedOre** [comment]
> I'm not setup to build Flatpaks, so it's probably easier/more effective for someone else to test it rather than have me commit it on a bug branch and then wait for someone to test it.

I can test this tomorrow.

**Comment by barthalion** [comment]
Yeah, I meant setting it to `false`. Not my day.

**Comment by CodedOre** [comment]
Alright, I have tested `separate-locales: false`, but it does not affect the end result... We still have an localized console output, but the UI is till not localized...

**Comment by CodedOre** [comment]
@IBBoard, I do think the problems is somewhere in the code of Cawbird, the locales are installed "correctly" (using Flatpak's definition of "correctly"), and the console works...

So it is probably a problem somewhere in the UI-Code? Maybe GTK not correctly initializing?

Looking further into it...

**Comment by CodedOre** [comment]
Okay, so far I am at the following point:

- [x] flatpak is set to the language the system is set to
- [x] flatpak installes the right langpacks to support it
- [x] Cawbird detects the right language when running
- [x] GTK detects the right language when running
- [x] Cawbird translates the output from the terminal
- [ ] Cawbird translates the UI from GTK

Basically everything seems to work, apart from Gtk... So, I guess it has to do with it. The question now is: Is this a bug in GTK or do we have outdated code in Cawbird preventing Gtk to translate?

**Comment by IBBoard** [comment]
Some strings in the GUI (such as building the "replying to" line) are direct calls to gettext. Do they work?

The fact that the console translates correctly suggests that they should. But it would be good to check.

I thought GTK and gettext was magic that just happened. But maybe it's the init calls required for Gstreamer that are breaking it?

**Comment by CodedOre** [comment]
> Some strings in the GUI (such as building the "replying to" line) are direct calls to gettext. Do they work?
> 
> The fact that the console translates correctly suggests that they should. But it would be good to check.

Nope, they are not translated...

> I thought GTK and gettext was magic that just happened. But maybe it's the init calls required for Gstreamer that are breaking it?

Then it should work when we disable video on build, but no, it does not work, it would be too easy...

> Edit: the docs suggest we might be missing calls. Unless Vala does them automatically. Although it's weird that native seems to work fine without it! https://developer.gnome.org/glib/stable/glib-I18N.html

We are already using the `_()` macro from there, so probably not? Also other Vala projects also not seems to need it added.

**Comment by IBBoard** [comment]
> > Some strings in the GUI (such as building the "replying to" line) are direct calls to gettext. Do they work?
> > The fact that the console translates correctly suggests that they should. But it would be good to check.
> 
> Nope, they are not translated...

That's interesting. That suggests that something in GTK is intentionally setting it back to English.

But the command-line translation happens [*within* the main Gtk.Application](https://github.com/IBBoard/cawbird/blob/master/src/Cawbird.vala#L136-L146), so I'd have expected the same behaviour.

> > I thought GTK and gettext was magic that just happened. But maybe it's the init calls required for Gstreamer that are breaking it?
> 
> Then it should work when we disable video on build, but no, it does not work, it would be too easy...

Maybe, maybe not. I was on my phone for that last message so I didn't really check the code. It looks like we only init X and GStreamer. I thought it might be that we didn't initialise GTK correctly. Building without GStreamer support still does the XInit, but that's too low level for what we care about here.

> > Edit: the docs suggest we might be missing calls. Unless Vala does them automatically. Although it's weird that native seems to work fine without it! https://developer.gnome.org/glib/stable/glib-I18N.html
> 
> We are already using the `_()` macro from there, so probably not? Also other Vala projects also not seems to need it added.

Again, I was on my phone so I just skimmed a few bits. I didn't pay attention to the fact that that's where we get `_()` from. I guess that is lower GLib stuff, though, so maybe `Cawbird` extending `Gtk.Application` in `Cawbird.vala` is enough.

Annoyingly, it looks like you can set the text domain etc but not query them - https://valadoc.org/glib-2.0/GLib.Intl.html

But I've just found that we DO [manually configure them](https://github.com/IBBoard/cawbird/blob/master/src/Cawbird.vala#L266-L269)! We may have a lead! 🙂

**Comment by IBBoard** [comment]
As far as I can tell, [Cawbird.vala line 266](https://github.com/IBBoard/cawbird/blob/master/src/Cawbird.vala#L266) is setting the locale wrong. That's [supposed to be a string like "da_DK"](https://man7.org/linux/man-pages/man3/setlocale.3.html) for Danish, but Baedert passed a path. Maybe native is ignore it an Flatpak is choking on it?

If I remove all of it then it throws lots of errors because of bad characters (it must default to something other than UTF-8).

If I just keep `GLib.Intl.bind_textdomain_codeset()` then I get some valid translations but not all (it looks like it's probably things that call `_()` manually that work, but not GTK Builder).

If I put the `bindtextdomain` and `textdomain` calls back and just remove `GLib.Intl.setlocale` then it still works in native.

If removing that line doesn't fix the Flatpak, maybe try setting the second parameter to `""`. From the [setlocale docs](https://man7.org/linux/man-pages/man3/setlocale.3.html#DESCRIPTION):

> If locale is an empty string, "", each part of the locale that
> should be modified is set according to the environment variables.

**Comment by CodedOre** [comment]
> As far as I can tell, [Cawbird.vala line 266](https://github.com/IBBoard/cawbird/blob/master/src/Cawbird.vala#L266) is setting the locale wrong. That's [supposed to be a string like "da_DK"](https://man7.org/linux/man-pages/man3/setlocale.3.html) for Danish, but Baedert passed a path. Maybe native is ignore it and Flatpak is choking on it?

That's probably then (finally!).

Will test this tomorrow.

**Comment by IBBoard** [comment]
That's what I'm hoping. Although I don't understand why it doesn't affect native builds as well.

**Comment by CodedOre** [comment]
Well, I guess the set path is configured for the location of the locales on a native system, which is `/usr/share/` or (Config.DATADIR).

Flatpak on the other hand has a (semi-working) shortcut there, but the real files are in `/var/lib/flatpak/runtime/uk.co.ibboard.Cawbird.Locale`.

So I guess as it is set to only search at the specific location it does not find it there.

**Comment by CodedOre** [comment]
Still no success here...

Tried around with modifying the existing lines you mentioned, but it is every time the same result... But I did noticed that text directly coming from GTK (for example in the About Dialog) are translated...

I don't have any idea where our problem is...

**Comment by IBBoard** [comment]
Well, that's frustrating!

One thing that I can see is that Lollypop seems to do the binding outside the main application. I've just pushed a branch that *might* fix it. I'm optimistic because I'd noticed in my testing with `"LC_ALL=ab_CD` that the settings menu wasn't translated. But now it is. So _maybe_ it needs to be initialised outside the `Gtk.Application`. Hopefully.

**Comment by CodedOre** [comment]
> One thing that I can see is that Lollypop seems to do the binding outside the main application. I've just pushed a branch that _might_ fix it. I'm optimistic because I'd noticed in my testing with `"LC_ALL=ab_CD` that the settings menu wasn't translated. But now it is. So _maybe_ it needs to be initialised outside the `Gtk.Application`. Hopefully.

Well, I already tested that with no result, but to be sure let's test this again...

Wait a minute...

![german](https://user-images.githubusercontent.com/47981497/109861298-73b65a80-7c5f-11eb-9bb1-d2b727fefbce.png)

**It works! Finally!**... Sort of.

One thing I had to change this:
```c#
GLib.Intl.bindtextdomain (Config.GETTEXT_PACKAGE, "/app/share/locale");
```

to this:

```c#
GLib.Intl.bindtextdomain (Config.GETTEXT_PACKAGE, null);
```

As the locale directory has a different path we need to specify that. I would used meson to set this (see this example with [Gnome Games](https://gitlab.gnome.org/GNOME/gnome-games/-/blob/master/meson.build), but I don't got it to work with Cawbird's `config.h`, so that is up to you.

**Comment by IBBoard** [comment]
Huzzah!

I guess it makes sense that we need to pass it a path, since the [GLib docs](https://developer.gnome.org/glib/stable/glib-I18N.html) show it passing a path and the [bindtext docs](https://linux.die.net/man/3/bindtextdomain) say it returns the path, which suggests that it's important.

I'm guessing that using `Config.DATADIR + "/locale"`  for bindtextdomain wouldn't work (which is what was supplied to setlocale) 😕 I'll work something out with some changes to config and meson and extra build options.

**Comment by IBBoard** [comment]
Okay, I think that works.

The only problem at the moment is that I've got to run `meson build -Dprefix=/usr` to pick up the package-installed language files. Which feels ugly. But I don't know how to make it just pick up the local files (which it seemed to do with "null").

**Comment by CodedOre** [comment]
> The only problem at the moment is that I've got to run `meson build -Dprefix=/usr` to pick up the package-installed language files. Which feels ugly. But I don't know how to make it just pick up the local files (which it seemed to do with "null").

Can't say for sure, but I think this is "working as intended", as you could run meson and ninja for a local build (which would result in `~/.local` being the prefix?). I saw at least some apps who said "add `--prefix=/usr` for installing it globally...

Not sure about this though...

**Comment by IBBoard** [comment]
I think it is working as intended, because it would be fine once I installed it. But it's annoying that "intended" means that you've got to install it to run it and can't just run it with translations from the build dir. We've found the workaround for making schema changes work without installation. I might have to put an override switch in to meson for local language loading for when you're debugging.

**Comment by IBBoard** [comment]
Can someone test the Flatpak builds with the latest changes? It seems to work with native builds. If we're happy that it works then I can merge it and (hopefully) ship an update soon!

**Comment by CodedOre** [comment]
A local build worked flawless, but I would test it a flathub-build as well.

**Comment by CodedOre** [comment]
Testbuild is complete, the flathub packages provide translation as well!

From the translation standpoint we should be clear.

**Comment by IBBoard** [comment]
Okay, that's all merged now. Thanks for all the debugging and testing 🙂
