### ISSUE TITLE
Use a smily face icon and tooltip for emoji button

### ISSUE THREAD

**Issue by philipzae** [IBBoard/cawbird#298]
The emoji icon is a penguin which always confuses me and I think I want to click the heart icon and unfortunately the button also doesn't have a tooltip to help.
![image](https://user-images.githubusercontent.com/4412114/105395661-6b1e3d80-5c38-11eb-8b85-1afb2be90c4f.png)

**Comment by IBBoard** [comment]
We should have a tooltip. I didn't realise that we were missing one. But I'm inclined to keep the penguin.

1) Penguins are cool.
2) It's a Linux app, so it's good to involve penguins.
3) Penguins are cool.

It does highlight that the heart may not be clear, though. We almost need it as a drop-down part on the "Add media" button. I don't know if Gnome moved away from them, but there used to be buttons where a press did the default (pick a file) but the right-hand edge was a button that made a menu appear that let you pick related options (pick a file, or pick a favourite).

**Comment by philipzae** [comment]
Penguins are definitely cool, but unless the emojis are penguin looking, it doesn't really lend to what the button does. Also on a dark theme, its hard to see the penguin.

**Comment by IBBoard** [comment]
You could always try not using a dark theme 😉

But you've probably got a point. A smiley would be more in-keeping with other UI (e.g. mobile keyboards). And it's a one-line patch that I can put back in to my custom build anyway 🙂
