### ISSUE TITLE
& replaced by &amp; in tweet link

### ISSUE THREAD

**Issue by lucaswerkmeister** [IBBoard/cawbird#305]
**Describe the bug**
Clicking the link in [this tweet](https://twitter.com/aharoni/status/1354054288310497280) opens [this URL](https://en.wikipedia.org/w/index.php?title=Ehud_Manor&amp;amp;type=revision&amp;amp;diff=1002880213&amp;amp;oldid=1000831694&amp;amp;diffmode=visual) rather than [this one](https://en.wikipedia.org/w/index.php?title=Ehud_Manor&type=revision&diff=1002880213&oldid=1000831694&diffmode=visual).

```diff
- https://en.wikipedia.org/w/index.php?title=Ehud_Manor&type=revision&diff=1002880213&oldid=1000831694&diffmode=visual
+ https://en.wikipedia.org/w/index.php?title=Ehud_Manor&amp;type=revision&amp;diff=1002880213&amp;oldid=1000831694&amp;diffmode=visual
```

(Note: I’ve had to escape the `&amp;` one more time so that the “this URL” link would actually link to the wrong URL in GitHub Flavored Markdown. The link opened by Cawbird has `&amp;`, not `&amp;amp;`.)

**To Reproduce**
1. Open [this tweet](https://twitter.com/aharoni/status/1354054288310497280) in Cawbird, e.g. by searching for `@aharoni`’s account (it’s currently his latest tweet).
2. Click the link in it, or right click and copy link address.

**Expected behavior**
The browser opens a visual diff page (or the URL for that page, with `&diffmode=visual`, is copied).

**Screenshots**
Not really applicable, I think. (The title / hover text of the link has the correct `&` characters.)

**System details:**
 - OS: Arch Linux
 - Version: 1.3.2.r39.g9695fe49-1, i.e. built from commit 9695fe49
 - Package type: [cawbird-git](https://aur.archlinux.org/packages/cawbird-git) AUR package

**Additional context**
Running `G_MESSAGES_DEBUG=cawbird cawbird` includes the following line:

```
(cawbird:29902): cawbird-DEBUG: 15:23:44.831: TweetUtils.vala:890: Activating 'https://en.wikipedia.org/w/index.php?title=Ehud_Manor&amp;type=revision&amp;diff=1002880213&amp;oldid=1000831694&amp;diffmode=visual'
```

No other debug output seems related (this is the only line containing the word “visual”).

**Comment by IBBoard** [comment]
Huh. We appear to be double-encoding the URL somewhere. That's annoying. Slightly better than the point we weren't encoding some ampersands and GTK refused to show the text because of invalid HTML

**Comment by IBBoard** [comment]
Okay, I *think* that fixed it. If you could give it a test as well then that would be great.

**Comment by lucaswerkmeister** [comment]
Yup, looks fixed to me. Thanks a lot!

**Comment by IBBoard** [comment]
It's all the other places that we deal with entities that I'm worried about 😄 cec292b was one bit where I suddenly went "ooops, that problem again - not as simple as I thought"!

**Comment by lucaswerkmeister** [comment]
Yeah, but I’m not sure how to test those bits :D but so far it looks okay to me (I sent myself a DM with some entities and markup and that looked fine)

**Comment by IBBoard** [comment]
I think it's good. I'll call it closed.
