### ISSUE TITLE
Image and video border

### ISSUE THREAD

**Issue by philipzae** [IBBoard/cawbird#306]
Would be good to add a border around images and likely videos, so you can see its dimension, irrespective of which theme you are using.

![image](https://user-images.githubusercontent.com/4412114/106011710-2a10a800-60d4-11eb-9fdb-6895ab0c6a2d.png)

**Comment by IBBoard** [comment]
A border or a drop shadow might work. We'll have to think about what we can do to make it work across themes, because not all themes will have an appropriate colour exported.

**Comment by philipzae** [comment]
If the inversion of the theme background color is possible, then that would likely do the trick.

**Comment by IBBoard** [comment]
Inverted colours would only work for a very narrow range of themes. And even then it wouldn't be great.

On light and dark themes then it would work, but it would be too light/dark and would stand out as being out of place.

On mid-grey themes it wouldn't necessarily be strong enough.

And on any theme with a hint of colour then it would look REALLY odd, as if something was wrong. Anything with hints of green would have a slightly pink border. Anything blue-ish would go a bit yellow.

**Comment by CodedOre** [comment]
We could add shadows with css.
We just need to add a style class with the shadow and apply it to the images.

**Comment by IBBoard** [comment]
The difficulty might be in adding a shadow in a colour that makes sense across all themes. I've used `@borders` because it's the CSS colour for widget borders. But I don't know how well that would work for shadows. And we can't just put in dark grey because it won't show well on dark themes.

**Comment by CodedOre** [comment]
I did not know we could set the color of an shadow (tells how much I know about css)...

But I would just set it to `black`, because...\
*Who would colorize a shadow?*

**Comment by IBBoard** [comment]
"drop shadow" also covers putting a white glow around things and many other options 🙂

Black seems like a bad choice because a) it's very harsh on light themes and b) it's not visible on dark themes.
