### ISSUE TITLE
Cannot build on Arch: Creation method of abstract class cannot be public

### ISSUE THREAD

**Issue by lucaswerkmeister** [IBBoard/cawbird#31]
Both the `cawbird` and `cawbird-git` AUR packages fail to build for me with the following error:

```
../src/DefaultTimeline.vala:51.3-51.24: error: Creation method of abstract class cannot be public.
  public DefaultTimeline (int id) {
  ^^^^^^^^^^^^^^^^^^^^^^
```

I have Vala 0.46.0 installed. This seems to be a relatively new error; the two other occurrences I found are from August 3rd (pdfpc/pdfpc#446) and 8th (ueno/libkkc#23).

**Comment by IBBoard** [comment]
openSUSE Tumbleweed is still on 0.44.7 (despite being an "up to date" rolling distro), so I hadn't seen that yet. Thanks.
