### ISSUE TITLE
Error 429 Too Many Requests on startup

### ISSUE THREAD

**Issue by IBBoard** [IBBoard/cawbird#310]
We occasionally get hit by [Error 429 - Too Many Requests](https://twitter.com/CawbirdClient/status/1347870311803482114) on the Mentions and Likes timelines. Twitter being Twitter, it doesn't give you any more information. We already only poll every 2 minutes to keep under the "15 requests every 15 minutes" [limit on the home timeline](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/timelines/api-reference/get-statuses-home_timeline). We poll the other timelines at the same rates and the [mentions limit is up at 75 requests every 15 minutes](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/timelines/api-reference/get-statuses-mentions_timeline), so we should be *miles* off the cap for a user.

BUT after it just happened again but was okay with some different keys, I noticed the following in the docs:

> Important notice: On June 19, 2019, we began enforcing a limit of 100,000 requests per day to the /statuses/mentions_timeline endpoint. This is in addition to existing user-level rate limits (75 requests / 15-minutes). This limit is enforced on a per-application basis, meaning that a single developer app can make up to 100,000 calls during any single 24-hour period.

Doing a quick bit of maths, we do 30 requests per hour. That's 720 requests per day. That's the equivalent of just under 140 users running Cawbird 24/7 (or 420 users running it for eight hours of the "office" day, or any other breakdown that you can think of).

So, we're currently HUGELY hobbled on how many concurrent users we can have.

I can see two options:
1) Reduce the mentions polling time
2) Create new keys and have "Cawbird (Official)" built on OBS, and others using other keys.

The first option won't scale well. If we drop it to five minutes then we get two and a half times as many users BUT everyone gets a worse experience. And the only way to add more users is to slow it down even further.

The second option requires the cooperation of @p1u3o and others (Flatpak), @diddledan (Snap), @danct12 (Alpine), @schmittlauch (Nix), the team Fedora and others (think I got those names right) to migrate to their own keys. And it'll break any pre-existing accounts, so people will have to remove and re-add them.

I'm not even sure how something like Flatpak would edit its GSettings schema to specify different default keys. I think I could do it on OBS for RPM and assume it would cascade through to DEB, but I don't know how Flatpak or Snap etc would customise config files.

Anything that changes the keys is going to need some app-level notification to the users to say "sorry, going to have to re-authenticate".

**Comment by schmittlauch** [comment]
In principle I am open to build the Nix package with my own key. But do you know the Twitter terms about API key abuse?
Right now the Cawbird API credentials – which are probably linked to your Twitter account – are lying in plain sight in the code repo, the same will be true about the credentials I would provide for the Nix packages then.
What are the implications of someone getting these credentials and miss-using them for their own stuff? I am not fond of getting my whole account banned just because some other project "stole" my credentials.

**Comment by IBBoard** [comment]
In theory, Twitter says that keys and tokens "must be guarded very carefully" ([Authentication Best Practice](https://developer.twitter.com/en/docs/authentication/guides/authentication-best-practices)). In practice, that's basically impossible in open source software and barely any better in proprietary software.

We could obfuscate them with base64 or ROT13 or something, but the keys are still there. We could encrypt them with GPG and add a whole extra level of complexity. But we need to include the encryption key with the app, so people can just use that to decrypt it themselves.

Open Source is more prone to this because it's good to let people just compile it and go without setting up stuff in Twitter. But Closed Source still has exactly the same "we're going to secure this thing in a very secure box… but also give you the key to unlock it so that you can use it when you need to" problem.

The only people who *can* protect their keys are those who run servers rather than client apps.

But given the complete lack of vetting that Twitter do with apps such as letting users make [Mobile App 9.2 and Web App 9.1](https://twitter.com/conspirator0/status/1351687150882988032), [blank name bots](https://twitter.com/conspirator0/status/1344129157819723777) and [Twitter for Android6 and Twitter for {insert-manufacturer-and-model}](https://twitter.com/conspirator0/status/1335347461863448584) (yes, no space, and yes there's [other numbers too](https://www.twitlonger.com/show/n_1siicdb)) then I don't think Twitter credential theft is a big issue. People just create their own developer account and abuse it until Twitter (may or may not) do something. All we've ever had in the last two years was a temporary block of some permissions (#117) when I spammed "Test" to myself a dozen times very quickly in DMs to actually have some DMs to fetch through the API!

**Comment by IBBoard** [comment]
The "use your own keys" builds appear to be working. I've used custom builds to configure accounts [using "Cawbird Unstable" keys](https://twitter.com/IBBoard/status/1369379176009064459) (but there's a separate ["Twitter aren't showing the app name" issue](https://twittercommunity.com/t/my-app-doesn-t-have-an-app-name-when-posting-tweets/150896) with that) while keeping existing accounts on their default credentials. And I can run both accounts at the same time with different app secrets from a single installation.

I think this is the best we can do for now, and it's just up to people to pick new keys (or for a future "official" build to migrate to a "New Cawbird" key).

**Comment by schmittlauch** [comment]
Could you elaborate on the per-user-keys, are these also compile-time variables?

**Comment by IBBoard** [comment]
No, its all stored in the database. Each account now stores the application secrets as well as the user's account secrets.

Any existing accounts take the default Cawbird secrets (unless the user had overridden the key in DConf - which almost no-one will have done). This happens on the first load after upgrade, when we migrate account details.

Any new keys will use either the compiled keys (which may be the default Cawbird ones, or they may be ones like my Cawbird Unstable keys) *or* they'll use the keys in DConf if they're set. So old migrated accounts carry on working, but new accounts will use new keys. It solves the "but if we change the keys then we force people to log in to all of their accounts again" problem (but it does mean that people who don't re-authenticate are still using the old keys).

In theory, you can keep changing the DConf settings and every new account will then be created for that new application. In practice, people won't bother setting it and they'll just use the compiled keys!

In the long term we _might_ add the ability to supply keys as an advanced option during account creation.

(Secrets/keys is interchangeable here - it's the application secret and key!)

(Note: We still only allow one instance of each account, so you can't have five copies of your account posting from five different "applications"!)
