### ISSUE TITLE
'Failed to commit changes to dconf' on attempts to change several settings

### ISSUE THREAD

**Issue by robinhood2014** [IBBoard/cawbird#311]
**Describe the bug**
When I attempt to change some settings in Cawbird, the change I make reverts automatically. Running Cawbird from a terminal gives more details why the settings change failed, thus:
`(cawbird:3): dconf-WARNING **: xx:xx:xx.xxx: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown`
where `xx:xx:xx.xxx` happens to be the time of day when the warning was thrown.

**To Reproduce**
1. Run Cawbird from a terminal (in my example, I installed the Cawbird flatpak, so I ran `flatpak run uk.co.ibboard.cawbird`
2. (If necessary) Request a PIN; this will launch your default Web browser where you can log in to Twitter. You'll receive a seven-digit PIN which you will copy and paste back into Cawbird.
3. Click on the button with a gear on it
4. Click on 'Settings'
5. Click on such settings as 'Interface > Use dark theme,' 'Interface > Auto scroll on new tweets,' 'Tweets > Round avatars,' etc.
6. The setting will switch on and immediately switch off, and the above dconf-WARNING will appear in the terminal window.

**Expected behavior**
The setting should have switched on and stayed on. In the cases I have outlined above, Cawbird should have switched to a dark mode; the auto-scroll function should have enabled, and avatars should have changed from square to round.

**System details:**
 - OS: Gentoo
 - Version: 1.3.2
 - Package type: Flatpak

**Comment by robinhood2014** [comment]
Will attempt to duplicate the error on Ubuntu. Stand by.

**Comment by IBBoard** [comment]
Odd. I've not heard anything else about people having problems with settings in the Flatpak.

Based on some searching, there was a problem in 2018 where Flatpak needed some weird extra options for DConf to work ([1](https://github.com/flathub/net.sf.VICE/commit/84cb43cc02c7160bdade43b4ca54803af2b3b469), [2](https://github.com/flathub/com.github.fabiocolacio.marker/pull/4/files))

But it looks like [we shouldn't need that now](https://docs.flatpak.org/en/latest/sandbox-permissions.html#dconf-access).

I'll see what your Ubuntu results are, and whether @p1u3o and @CodedOre have seen anything like this before.

**Comment by CodedOre** [comment]
It does work under my system (Fedora 33), so I guess the problem lies more on your local system.

Normally, flatpak should create a configuration file under `.var/app/uk.co.ibboard.cawbird/config/glib-2.0/settings/keyfile` when the first setting is changed. Since `startup-accounts` should be added after you logged in (@IBBoard correct me if I am wrong) this file should exist, if not, this could be the error.
Second point could be that dconf can't be called, would probably by an old version of `xdg-desktop-portal`, or a missing package, but this should result in other errors as well, so might or might not be the problem.

Or it is just a error I do not know the answer to... I am not an expert, just find it quite useful.

**Comment by robinhood2014** [comment]
Confirmed. Problem does not resurface in Ubuntu. Will return to Gentoo and investigate further.

**Comment by robinhood2014** [comment]
OK. Checked `~/.var/app/uk.co.ibboard.cawbird/config` on my Gentoo system, and there isn't even a `glib-2.0` directory, so it can't even create `settings/keyfile` in a directory that doesn't exist. So I'm clearly missing a package in Gentoo -- but the big problem I have now is... what package is it? Uuuuuuuuugh...

**Comment by IBBoard** [comment]
I don't know Flatpak, but based on CodedOre's comments and the bits that I found, what version of the core Flatpak runtime etc are you using? It might be that the Flatpak is built assuming later versions and so things fail (or I could be misunderstanding how Flatpak works!)

**Comment by p1u3o** [comment]
Does Gentoo even ship with dbus?

**Comment by CodedOre** [comment]
> [...] but the big problem I have now is... what package is it? Uuuuuuuuugh...

Can you check if you have the package `xdg-desktop-portal-gtk` installed? This should be the package responsible for the dconf integration, as far as I can tell.

**Comment by robinhood2014** [comment]
Yes, `xdg-desktop-portal-gtk` and `dbus` are both installed. I have Flatpak 1.10.

**Comment by CodedOre** [comment]
Alright, sorry for the late reply...

But I would assume the problem then lies somewhere with `dconf` not set up and `flatpak-portal` correctly tries to call it, but without response.

Could you test this command:

```sh
dbus-send --print-reply --dest=org.freedesktop.DBus  /org/freedesktop/DBus org.freedesktop.DBus.ListNames | grep ca.desrt.dconf
```

If there is not output, then the problem should be that the dconf bus is not set up.

**Comment by robinhood2014** [comment]
Getting the following output: `string "ca.desrt.dconf` but that's it.

**Comment by CodedOre** [comment]
> Getting the following output: `string "ca.desrt.dconf"` but that's it.

That was to be expected, as I wanted to see if the "dconf dbus" is there...

So... `dconf` seems to work, Cawbird seems to work (until proven otherwise), so I guess the problem lies somewhere inside the Flatpak-portal.

I would suggest you ask in the [repo of `xdg-desktop-portal-gtk`](https://github.com/flatpak/xdg-desktop-portal-gtk) if this is familiar to them.

**Comment by robinhood2014** [comment]
Okay. So, seeing as the problem is not with Cawbird, would it be a good idea to close this issue?

**Comment by IBBoard** [comment]
Yeah, I'll close it because we should be doing the right things and it's working for other people. Re-open it with extra information if the xdg-desktop-portal-gtk people say that we're doing something wrong.
