### ISSUE TITLE
Plural form for "%d new Messages from %s"

### ISSUE THREAD

**Issue by gunchleoc** [IBBoard/cawbird#320]
**Describe the bug**
Slavic Languages and Scottish Gaelic (I just started translating) need plural form treatment for "%d new Messages from %s"

Can be fixed by calling `ngettext`to fetch translations for the string.

**To Reproduce**
I don't know where it is in the UI yet

**Expected behavior**

- 2 new messages... = 2 theachdaireachd ùr...
- 3 new messages... = 3 teachdaireachdan ùra...

**Comment by IBBoard** [comment]
We already do that - https://github.com/IBBoard/cawbird/blob/master/src/DMThreadsPage.vala#L246-L247

And the translation files are showing plurals - https://github.com/IBBoard/cawbird/blob/master/po/cawbird.pot#L142-L145

I've just added "Gaelic, Scottish" on Transifex and it seems to be showing 1, 2, few, other.

![Screenshot_2021-02-20 Cawbird Transifex Editor](https://user-images.githubusercontent.com/388582/108592297-1c61e180-7365-11eb-8367-e10476848f0b.png)

**Comment by gunchleoc** [comment]
Thanks! I was working off the `pot` file from this repo while waiting for the language to be added to Transifex. It's OK there :)
