### ISSUE TITLE
HTMLEntities in URL

### ISSUE THREAD

**Issue by gunchleoc** [IBBoard/cawbird#322]
**Describe the bug**
When clicking on a URL in a tweet, `&` is replaced by `&amp;`.

**To Reproduce**
Click on the link in this tweet: https://twitter.com/LeughLeabhar/status/1364198586620198912

**Expected behavior**
* `https://gaelicbooks.org/index.php?route=product/product&product_id=1742&search=steall+06` should be opened in Firefox
* `https://gaelicbooks.org/index.php?route=product/product&amp;product_id=1742&amp;search=steall+06` is opened instead

**Screenshots**
![cawbird_url](https://user-images.githubusercontent.com/4095570/108886785-4b947f00-7601-11eb-97cc-8d04f475d3cf.png)

**System details:**
 - OS: Linux Mint 20.01
 - Version: 1.3.2
 - Package type: Flatpak

**Comment by IBBoard** [comment]
I can't recreate this on Master. It should be fixed by #305. It will be fixed in the next release.

**Comment by gunchleoc** [comment]
Yep, looks like a dupe.
