### ISSUE TITLE
Notification area!

### ISSUE THREAD

**Issue by sallyahaj** [IBBoard/cawbird#331]
Hello there,
I would like to see the "Notification" on the app, which show the all notifications on the web or twitter app, like: follow by someone, reply to your tweet, like your tweet, retweet your tweet ..etc.

Thank you so much the the efforts.

**Comment by IBBoard** [comment]
Unfortunately Twitter doesn't provide an API for anything other than mentions.

https://github.com/IBBoard/cawbird#limitations
