### ISSUE TITLE
Rounded corners missing

### ISSUE THREAD

**Issue by maymage** [IBBoard/cawbird#332]
Hi all, 

as you can see in the screenshot below, Cawbird doesn't exhibit rounded corners on the bottom, which is however standard in GNOME, cf. Fractal to the left.

![cawbird](https://user-images.githubusercontent.com/36572014/109964837-7ca23d00-7cee-11eb-81b2-1d4f7743e798.png)

---

Related

* https://github.com/IBBoard/cawbird/issues/177

**Comment by IBBoard** [comment]
Interesting. I don't know of anything that we specifically do that would stop Gnome rounding the corners

However, a quick look at Nautilus, Books, Tweaks, Settings, Rhythmbox, Videos, and Image View (eog) shows a distinct lack of rounded corners on Gnome 3.38 for me.

**Comment by maymage** [comment]
Yeah, that's true.. infact apart from nautilus and settings the apps you listed are somewhat undermaintained.. and while settings gets a refresh,  nautilus nightly already has rounded corners 

![nautilus](https://user-images.githubusercontent.com/36572014/110017571-a37c6580-7d26-11eb-911d-b09491b78a06.png)

**Comment by IBBoard** [comment]
They might not be actively developed, but you can't get much more Gnome than default Gnome apps!

From what I've read, rounded corners appear to be a libhandy thing. If that's the case then we should get them automatically when we move to libhandy and we don't need a separate ticket for it.

**Comment by maymage** [comment]
Yes, you're probably right. Then just view this as a head up for getting libhandy implemented \o/

**Comment by maymage** [comment]
Not sure anymore, if this is automatic from libhandy, cf. 

* https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/1190

* https://gitlab.gnome.org/GNOME/gnome-control-center/-/merge_requests/929

**Comment by IBBoard** [comment]
Using Handy widgets doesn't mean they're using Handy Window.

e.g. https://github.com/elementary/photos/issues/581 specifically links rounded corners to the Window class

**Comment by IBBoard** [comment]
Also, [libhandy blog](https://blogs.gnome.org/alexm/category/libhandy/#gallery-1) seems to support it being a HdyWindow feature as does [the documentation](https://gnome.pages.gitlab.gnome.org/libhandy/doc/1.0/HdyWindow.html#HdyWindow.description). So we'll get it "for free" with the redesign. So there's no need for a separate ticket.
