### ISSUE TITLE
Add option to disable "Inappropiate" Image Filter

### ISSUE THREAD

**Issue by volfco** [IBBoard/cawbird#341]
I would love for a toggle in settings to disable the "This tweet contains images marked as inappropriate" warning on tweets across the board, so I don't have to click "Show anyways" every time.

**Comment by IBBoard** [comment]
Already got it - Settings > Tweets > Hide inappropriate content

![Screenshot from 2021-03-22 19-17-06](https://user-images.githubusercontent.com/388582/112046125-8a0b5400-8b43-11eb-803b-ff36ecadeb34.png)

**Comment by volfco** [comment]
I have absolutely no idea how I missed that. Derp
