### ISSUE TITLE
No Valid Frames Found

### ISSUE THREAD

**Issue by andhaniawan** [IBBoard/cawbird#347]
Hello,

I am experiencing a problem while playing video in Cawbird. But it's not happen to all video. This particular problem occurs for just for a video. I think it's codec related problem. I am not an expert or someone knows about coding and Linux. I hope this would be a helpful report and can be fixed for better experience in near future. Thank you very much

**Screenshots**
![Cawbird_Error](https://user-images.githubusercontent.com/73820415/112730724-b66d0900-8f65-11eb-9b68-42dc04f64f8a.png)

**System details:**
 - OS: Ubuntu 20.04.2 LTS
 - Version: 1.3.2
 - Package type: Snap

**Comment by IBBoard** [comment]
I can't debug it without an example tweet with video that fails.

However, I suspect it's either #113 or (more likely) #338.

**Comment by andhaniawan** [comment]
> I can't debug it without an example tweet with video that fails.
> 
> However, I suspect it's either #113 or (more likely) #338.

Here is the tweet https://twitter.com/JVLEHA/status/1373492677581283338

**Comment by IBBoard** [comment]
Works for me in the latest Master. Looks like it's #338.
