### ISSUE TITLE
build fails on UNIX or other system without AppStream

### ISSUE THREAD

**Issue by despair86** [IBBoard/cawbird#35]
related issue but on Linux: https://github.com/bilelmoussaoui/nautilus-git/issues/25
this appears to be the cause https://github.com/mesonbuild/meson/issues/1565
```
[3/43] Generating uk.co.ibboard.cawbird.appdata.xml_data_merge with a custom command.
FAILED: data/uk.co.ibboard.cawbird.appdata.xml
/usr/bin/meson --internal msgfmthelper ../data/uk.co.ibboard.cawbird.appdata.xml.in data/uk.co.ibboard.cawbird.appdata.xml xml ../data/../po/
msgfmt: cannot locate ITS rules for ../data/uk.co.ibboard.cawbird.appdata.xml.in
```
otherwise works fine on my Sun 🎉

**Comment by IBBoard** [comment]
What version of Meson are you using?

I've got builds running on Ubuntu, Fedora, CentOS and openSUSE and never seen that message. And if I'm reading the Meson bug correctly then it should "just work" since 2017!

**Comment by despair86** [comment]
meson 0.51.2 on
```
$ uname -a
SunOS sun-pc 5.11 illumos-e7b6645677 i86pc i386 i86pc
```
distribution does not package appstream or appstream-glib

**Comment by IBBoard** [comment]
Odd. I have libappstream4 installed, but not appstream-glib or the devel package. The package only provides the .so file, news and license, so I've not got the "its" rules either (only fontconfig, gschema and gtk4builder under `/usr/share/gettext/its/`) but it builds without issue.

I'll have to look in to it a bit more and see what can be done.
