### ISSUE TITLE
Strings missing from Transifex

### ISSUE THREAD

**Issue by gunchleoc** [IBBoard/cawbird#351]
**Describe the bug**
The current unstable build is missing some translations, e.g. this one:

```
ui/modify-filter-dialog.ui:                <property name="label" translatable="Yes">Regular Expression:</property>
```

It's not on Transifex, so there are 2 possible reasons:

* Not included in the translation file
* New version hasn't been pushed to Transifex yet

### Some more examples:

Search screen: "Loading..."
Filter screen:
* "You can block users in their profile"
-> Add new filter: "Regular Expression:", "Test:"

I'll wait with further translation testing until this issue has been looked at.

**Comment by IBBoard** [comment]
Well, that was simple but annoying! Who makes a boolean field case-sensitive?! 😄

**Comment by gunchleoc** [comment]
Somebody who never makes any typos? An evil anal-retentive proofreader? :P

Thanks for fixing - my translation is back at 100% on Transifex. Would you create a new unstable build for me? :pleading_face:

**Comment by IBBoard** [comment]
Probably someone who assumes it's all done by tools rather than edited by hand, and then assumes that all tools do it the same way.

I've just put the new patch on Unstable, so it should be building now.
