### ISSUE TITLE
Not so much an issue report, but a report on another platform it works on

### ISSUE THREAD

**Issue by ZachBacon** [IBBoard/cawbird#36]
So thanks to the power of msys2 
running pacman -S mingw-w64-x86_64-vala mingw-w64-x86_64-gstreamer mingw-w64-x86_64-gspell mingw-w64-x86_64-libsoup mingw-w64-x86_64-gtk3 

I managed to get cawbird running on windows

![cawbird](https://user-images.githubusercontent.com/8948676/66089708-6b2f9100-e54e-11e9-8627-61515c190618.png)

**Comment by ZachBacon** [comment]
The only thing that didn't seem to quite work would be attaching images to a tweet. But I'd figured I'd at least report, albeit an unsupported platform, works without any code changes

**Comment by IBBoard** [comment]
Wow. That's quite impressive! Although Adwaita windows on Windows looks a bit odd.

Is that using the WSL layer, then, since it's using Pacman?

When were you testing the uploads? And what errors were you getting? Because Twitter had some [significant issues yesterday](https://twitter.com/TwitterSupport/status/1179251401886748672) and was giving me "Service Unavailable" or similar (when it wasn't giving me the bug #9 TLS issues).

**Comment by ZachBacon** [comment]
No wsl layer, msys2. It's a cygwin fork that creates packages, the developers quite a number of mingw compiled packages for native development. And it could of been around the time twitter having server issues. But I think it was reported at the time to be resolved. 

I'll have to try again at some point. But anyways I'll have to give it another go. Currently I'm on linux side doing some package updates there.

**Comment by ZachBacon** [comment]
@IBBoard so it looks like it's determining a png file is not an image. Despite it being an image. 
Shell provides ComposeTweetWindow.vala:315: Loading C:\Users\ZachBacon\Documents\cawbird.png But I can't make heads or tails about why it's not recognizing the file, could be simple as a gstreamer issue, or not. When I have more time I'll see if can debug it properly through gdb since there's also a segfault on app closure too and I'll see if I can see what's going on.

Also I do apologize if that doesn't come out right. I worked an 12 hour graveyard shift and I should be hitting the sack. 

To simplify it, I'll investigate further when I wake up.

**Comment by IBBoard** [comment]
Okay, no problem. I'm happy to include fixes where Windows/msys2 needs them (as long as it's not some crazily complex workaround that just complicates things and leads to Linux issues!)

If it's not seeing PNGs as images then that's odd, but a GLib on Windows problem. I was definitely having upload issues and web page loading issues after the tweet suggesting that it was all fixed, though.
