### ISSUE TITLE
Accessing Settings crashes on unstable with gd locale

### ISSUE THREAD

**Issue by gunchleoc** [IBBoard/cawbird#361]
**Describe the bug**
Accessing the Settings via GUI or keyboard shortcut will crash Cawbird in the `gd` locale. `en_GB` is fine.

**To Reproduce**
1. Set the system to GD locale in Linux Mint
2. Reboot
3. Start Cawbird
4. Click on Gear Icon
5. Click on "Roghainnean" -> crash

**Additional context**
I went through the translations on Transifex and I can't spot any placeholder errors there. The only QA error on a placeholder I get there is a false hit.

Running `G_MESSAGES_DEBUG=cawbird cawbird` gives the following output:

```
<snip>
(cawbird:1823): cawbird-DEBUG: 13:00:56.245: Message with type 34 on stream @<username>
Segmentation fault (core dumped)
```

Second try:

```
<snip>
(cawbird:1889): cawbird-DEBUG: 13:04:48.077: Message with type 34 on stream @<username>
free(): invalid pointer
Aborted (core dumped)
```
Not very informative - is there anything I can do to get you more information?

**Comment by IBBoard** [comment]
More info requires `gdb` and the coredump file. On openSUSE (which uses systemd) I can run `coredumpctl gdb -1` to drop me straight into a debug session of the last crash. If you've got the debug symbols for it then you should be able to run that, press `q` to skip all of the paging of debug symbols, and then run `bt` to get a back-trace (stack trace) and then `quit` to quit. You can poke around in the variables as well, but it gets a bit more confusing from there.

What I get is:

```
(gdb) bt
#0  0x00007fa20658a959 in ?? () from /lib64/libc.so.6
#1  0x000055915d311ee0 in ?? ()
#2  0x00007fa20658a491 in ?? () from /lib64/libc.so.6
#3  0x0000000000000007 in ?? ()
#4  0x000020000000004b in ?? ()
#5  0x00007ffebc99f010 in ?? ()
#6  0x00007fa207a2b0c9 in g_free (mem=0xffffffffffffff88) at ../glib/gmem.c:199
#7  0x000055915cbc4bb7 in cb_text_entity_free (e=0x55916012c080) at ../src/CbTypes.c:55
#8  0x000055915cbbaf0e in settings_dialog_construct (object_type=94082866578736, application=0x55915d19b130) at ../src/window/SettingsDialog.vala:170
#9  0x000055915cbbb684 in settings_dialog_new (application=0x55915d19b130) at ../src/window/SettingsDialog.vala:61
#10 0x000055915cb25cbf in cawbird_show_settings_activated (self=0x55915d19b130) at ../src/Cawbird.vala:244
#11 0x000055915cb23382 in _cawbird_show_settings_activated_gsimple_action_activate_callback (action=0x55915d2f3cf0, parameter=0x0, self=0x55915d19b130)
    at ../src/Cawbird.vala:35
#12 0x00007fa206d1b0a2 in ?? () from /usr/lib64/libgobject-2.0.so.0
#13 0x00007fa206d1e6a0 in ?? () from /usr/lib64/libgobject-2.0.so.0
#14 0x0000000000000000 in ?? ()
```

Which should be something I can work from.

**Comment by IBBoard** [comment]
Oddly, it does seem to only be Gaelic that it crashes with. I've just tested Russian, Italian, Danish and Dutch and it's fine!

…

Wait. I bet it's the tweet. "Text entities" are how we handle objects within tweets that we need to linkify (usernames, links, hashtags, etc). I wonder whether everything always matched up until now!

**Comment by gunchleoc** [comment]
Fix confirmed :)
