### ISSUE TITLE
Strings missing for translation on edit list screen

### ISSUE THREAD

**Issue by gunchleoc** [IBBoard/cawbird#362]
**Describe the bug**
When editing a list in current unstable, some strings are still in English

**To Reproduce**
1. Use a locale not English
2. Click on 'Lists'
3. Click on an existing, empty list
4. The contents of "Mode" and "No entries found" are in English

**Screenshots**
![cawbird-edit-empty-list](https://user-images.githubusercontent.com/4095570/114178037-11730880-9935-11eb-829a-4ae87ed7c3cd.png)

**Comment by gunchleoc** [comment]
P.S: Spelling right-click menus (language / Spelling Suggestions) also have untranslatable English strings in them.

**Comment by IBBoard** [comment]
Looks like Private/Public is going to be tricky because Baedert used it as both the value and the string. It can be done, but we still need to pass "private" or "public" to Twitter.

"No entries found" was trying to be translatable, but it got missed out of the "translate these files" list.

**Comment by IBBoard** [comment]
Can I have a screenshot of the spelling suggestions? I *think* it might be out of our control. I can't find "Spelling" anywhere in the code base, and it's almost certainly added by gspell automatically.

**Comment by gunchleoc** [comment]
I can't get a screenshot because it is blocking the print screen button. To reproduce, compose a new tweet, type some nonsense and right-click on it.

**Comment by IBBoard** [comment]
> I can't get a screenshot because it is blocking the print screen button. To reproduce, compose a new tweet, type some nonsense and right-click on it.

That's inconvenient! I tend to use Glimpse in those situations and do a time-delayed screenshot. (Other image editors and/or screenshot tools may be available 😉)

> gspell is only 76 words, so I've done the translation and the next Gnome update should fix it.

Just to confirm, is "Spelling Suggestions…" in there? If so then I'll close this until we find bugs.

> Let's put this on low priority.

It wasn't too bad in the end. I'll update Unstable so that you can test 03210f7.

**Comment by gunchleoc** [comment]
Dug, I could have taken a time delayed screenshot with GIMP.  "Spelling Suggestions…" is part of the gspell package, so let's consider this one solved.

"No entries found" is still in English.

**Comment by gunchleoc** [comment]
I have found a final untranslatable string, `Custom` in the translation engine list. Settings -> Tweets

![cawbird-custom-se](https://user-images.githubusercontent.com/4095570/114380239-c7cb2d80-9b81-11eb-99c9-1e36dd5ef686.png)

**Comment by IBBoard** [comment]
"No entries found" is working for me. Maybe I didn't get the patch sorted properly.

I've just added "Custom" (and the other sites, just in case) as translatable. Thanks for being so thorough with the checks!

**Comment by gunchleoc** [comment]
Your screenshot for "No entries found" is of the search function, and for slightly different strings too (No user/tweet found). I was on the list screen, after creating a new, empty list and then selecting that list. The string is on Transifex and I translated it 3 days ago. It's still missing from unstable deb version `1.3.2-1+95.1`.

**Comment by IBBoard** [comment]
That's interesting, because they both use the `ListBox` object, so it *should* be the same message! The string isn't anywhere else in the source code. I'll have more of a look.

**Comment by gunchleoc** [comment]
Yep, it's strange. Try calling `reset_placeholder_text()` to see whether that fixes it?

**Comment by IBBoard** [comment]
SearchPage doesn't seem to call the reset, so it would be odd if that fixed it. Putting some debug in beside the two references to "No entries found" and it only ever shows that the translation returns the English. Even on the search page, which definitely shows Gaelic!

**Comment by IBBoard** [comment]
Or it's really trivial and when Gettext has a "fuzzy" string then it defaults to the original text (English in this case) rather than showing a potentially incorrect translation. #facepalm

Fixed by #373

**Comment by gunchleoc** [comment]
Thanks for fixing! :tada:
