### ISSUE TITLE
meson.build:218:0: ERROR: Assert failed: Must specify `consumer_key_base64` and `consumer_secret_base64`

### ISSUE THREAD

**Issue by tim77** [IBBoard/cawbird#377]
**Describe the bug**
Can't compile v1.4.

**System details:**
 - OS: Fedora 34
 - Version: 1.4
 - Package type: Official RPM

**Additional context**
```meson
meson.build:218:0: ERROR: Assert failed: Must specify `consumer_key_base64` and `consumer_secret_base64`
```

[Full build log](https://kojipkgs.fedoraproject.org//work/tasks/4992/67044992/build.log).

**Comment by IBBoard** [comment]
It's part of our fix for #310 and Twitter's API limits. Please see the [readme](https://github.com/IBBoard/cawbird#preparation).

**Comment by tim77** [comment]
@IBBoard thanks. Was rushed and no time to dig into this. :) Built, updated and [ready for Testing](https://bodhi.fedoraproject.org/updates/?search=cawbird).

**Comment by IBBoard** [comment]
The API limits are most likely to be hit through use on big distros (like Fedora). If there is a way that you can make some "Cawbird on Fedora" keys to distribute the user base and micro-fork your versions then that would be useful. Although I've not seen the HTTP 429 for a while.

**Comment by tim77** [comment]
> The API limits are most likely to be hit through use on big distros (like Fedora).

Yep, but in same time seems like not much users prefer Fedora build. Mostly Flathub, but not sure and doesn't have clear numbers.

So basically i should register new account and build with this custom (Fedora) keys? OK, i'll try to look into this ASAP.

**Comment by IBBoard** [comment]
It's an option so that we can spread users out a bit and give better experience. And I will try to move the Flatpak build over to its own keys at some point.

Actually, I need to update the build anyway, because I didn't bump it to v1.4 because it's not native packaging and so I forgot about it!
