### ISSUE TITLE
Can't play videos on Ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by damionx7** [IBBoard/cawbird#384]
I installed Cawbird from snap. I can't play videos it shows this error
`(cawbird:58787): cawbird-CRITICAL **: 16:48:39.277: gstbaseparse.c(1370): gst_base_parse_sink_event_default (): /GstPlayBin:video/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0/GstMpeg4VParse:mpeg4vparse0`

How to solve this issue ?

**Comment by IBBoard** [comment]
The Snap packages are a community build - https://github.com/diddlesnaps/cawbird.

From the error message, it looks like a problem with the GStreamer dependency, but as I'm not familiar with Snap then I can't say much more than that. You'll have to ask the maintainer.

**Comment by j1warren** [comment]
I sometime have problems playing videos, latest stable stand-alone package on 20.04
[latest example](https://t.co/V6PVkNtPES)

> gstvideodecoder.c(1138): gst_video_decoder_sink_event_default (): /GstPlayBin:video/GstURIDecodeBin:uridecodebin7/GstDecodeBin:decodebin7/avdec_mpeg2video:avdec_mpeg2video3:
no valid frames found

**Comment by IBBoard** [comment]
What version number is "latest"? And which source is "stand-alone package"? The official OBS builds or the Ubuntu builds or something else?

"No valid frames found" means that GStreamer fetched the URL but didn't get a valid video, which was fixed for a new variant of URL that Twitter uses in #338. That URL works fine for me.

**Comment by j1warren** [comment]
> What version number is "latest"?

1.4.1 from OBS.

**Comment by IBBoard** [comment]
This is a separate issue, so we need to move it over to #338 and I'll re-open the ticket if there's anything that we can do (rather than it being a Twitter/network issue)
