### ISSUE TITLE
Add option to remove Twitter source label

### ISSUE THREAD

**Issue by IBBoard** [IBBoard/cawbird#388]
(From @20NE)

First of all, I love cawbird, great job.
[features needed]
1. ~~vim-like shortcuts, like j for down, k for up, etc.~~
2. for privacy and security, is there a way to hide twitter source label ?

My words seem rude, excuse me,  my English is poor.
Have a good day.

**Comment by IBBoard** [comment]
I don't see how showing the Twitter source label affects privacy and security. All it tells you is what other people posted it with.

Unless you mean that you don't want your tweets showing up to everyone else as being from Cawbird?

Source labels are part of the Twitter API. They're based on the client tokens that you use. A UI might choose not to show them but they're always there (e.g. [on Twitter Web](https://twitter.com/CawbirdClient/status/1226131529279078402)). The only way you can disguise that you're using Cawbird is to create a [developer account](https://developer.twitter.com/en), create your own app and use those keys with Cawbird. Then you can name it whatever you want and only you will know what that client app actually is.

But I don't see that as any more of a privacy and security issue than every website that you visit knowing which browser you use, and everyone you email knowing which email client you use.

**Comment by 20NE** [comment]
>  The only way you can disguise that you're using Cawbird is to create a [developer account](https://developer.twitter.com/en), create your own app and use those keys with Cawbird.

Great, thx for your patience
