### ISSUE TITLE
Ubuntu 19.04 repo release key invalid?

### ISSUE THREAD

**Issue by jdrch** [IBBoard/cawbird#39]
I tried following the instructions for Ubuntu 19.04 [here](https://software.opensuse.org/download.html?project=home%3AIBBoard%3Acawbird&package=cawbird#manualUbuntu), but get an invalid key error message.

Any ideas?

**Comment by IBBoard** [comment]
I had some issues with testing the Ubuntu packages, but @j1warren reported that the 18.04 ones were okay, so I put it down to my unfamiliarity with Ubuntu.

Can you post the exact error that you're getting?

**Comment by jdrch** [comment]
> 18.04 ones were okay

I'm not sure about that, either. [As recently as 2 hours ago](https://www.omgubuntu.co.uk/2019/10/cawbird-twitter-client-for-linux#comment-4638713641), it seems other users are also having the invalid release key problem with that particular repo.

> Can you post the exact error that you're getting?

I will later when I have access to that machine again.

**Comment by hackazaq** [comment]
Err:11 http://download.opensuse.org/repositories/home:/IBBoard:/cawbird/xUbuntu_18.04  InRelease
  Las siguientes firmas no fueron válidas: B48735C3602F75FC122E34CCC7860C4E2C6C1E09

W: Error de GPG: http://download.opensuse.org/repositories/home:/IBBoard:/cawbird/xUbuntu_18.04  InRelease: Las siguientes firmas no fueron válidas: B48735C3602F75FC122E34CCC7860C4E2C6C1E09
E: El repositorio «http://download.opensuse.org/repositories/home:/IBBoard:/cawbird/xUbuntu_18.04  InRelease» no está firmado.

**Comment by jdrch** [comment]
That's the exact same error message I get, but in English. Repo may be
incorrectly configured.

**Comment by IBBoard** [comment]
I *think* I've found the cause of this, thanks to owncloud/client#5055!

My OBS key is ten years old (due to expire in 2 years). It's only a 1024bit key. That's considered weak these days. I'm going to try regenerating it as a 2048bit key.

Would have been nice if Ubuntu made that clearer, if that is the cause.

**Comment by jdrch** [comment]
Fascinating. Thanks for looking into that for us. Let us know when the new key is operative so we can try again :)

**Comment by IBBoard** [comment]
Well, that was a bit of a fight. I've now beaten OBS into submission and regenerated my key. https://build.opensuse.org/projects/home:IBBoard/public_key is reporting 2048 bits now.

I've triggered rebuilds for Ubuntu now, so hopefully it should sign with the new key. You'll probably have to remove the old one, though.

**Comment by IBBoard** [comment]
Okay, seems to work for me now once I've reimported the (new, stronger) key.

Thank you to Ubuntu for being unhelpful in its error message, and to the Open Build Service for having a ten year old key and not giving me a web-based way to recreate it!

**Comment by jdrch** [comment]
> Thank you to Ubuntu for being unhelpful in its error message, and to the Open Build Service for having a ten year old key and not giving me a web-based way to recreate it!

Gotta love the magic of open source, LOL. I got it working myself just now too. Thanks for fixing the issue as quickly as you did.
