### ISSUE TITLE
OpenGL renderer window still in window list after reading a video

### ISSUE THREAD

**Issue by liZe** [IBBoard/cawbird#394]
**Describe the bug**
After reading a video in Cawbird, an invisible window called "OpenGL renderer" is still open and can’t be closed. It’s listed in GNOME’s window list (using `alt-tab`). Each time a new video is read, a new window is added. Closing cawbird is the only way I’ve found to close these windows.

**To Reproduce**
1. Read a video
2. Hit `alt-tab` to list open windows
3. A new "OpenGL renderer" has been added to the list

**Expected behavior**
The "OpenGL renderer" video should be closed after the video is played.

**Screenshots**
![Capture d’écran de 2021-08-08 10-23-27](https://user-images.githubusercontent.com/952243/128625916-9145fab4-461d-4342-986e-831c07d9c3cb.png)

**System details:**
 - OS: Gentoo
 - Cawbird version: 1.4.1
 - Package type: distro package (that means custom build on Gentoo)
 - GStreamer: 1.18.4 (didn’t happen with 1.16.x)

**Additional context**
I’m using Wayland (don’t know if it’s related).

(And nothing’s interesting in debug logs.)

**Comment by IBBoard** [comment]
This must be a Wayland issue, because I'm not seeing it in openSUSE Tumbleweed with Gnome 40.3. Or it's a Gentoo-specific GStreamer bug, since we just load their widget.

Are there any relevant messages if you run Cawbird from a console? Any warnings or errors about not being able to dispose of something properly?

**Comment by liZe** [comment]
> Are there any relevant messages if you run Cawbird from a console? Any warnings or errors about not being able to dispose of something properly?

Nothing interesting :/.

> This must be a Wayland issue, because I'm not seeing it in openSUSE Tumbleweed with Gnome 40.3. Or it's a Gentoo-specific GStreamer bug, since we just load their widget.

You’re right, it might be a GStreamer bug with wayland. Actually, I’ve tried [this pull request](https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/-/merge_requests/1226), and… it fixes the bug :smile:.

Sorry for the noise, and thanks a lot for maintaining Cawbird :heart:.
