### ISSUE TITLE
Provide Snap build

### ISSUE THREAD

**Issue by IBBoard** [IBBoard/cawbird#40]
People [on OMGUbuntu](https://www.omgubuntu.co.uk/2019/10/cawbird-twitter-client-for-linux) are asking about Snaps. As per #24, if someone can make it then we can include it, but my focus is on native packaging and the "official" repos on the Open Build Service.

**Comment by pizzadude** [comment]
It looks like there is already a snap build https://snapcraft.io/cawbird

(I don't use it, I use the official repo version in Fedora KDE but I thought you should know)

**Comment by IBBoard** [comment]
Cool.

Does anyone know if it's possible to get usage numbers out of the website? There's a map, but no numbers.
