### ISSUE TITLE
Emoji button still unavailable on Fedora rpm package

### ISSUE THREAD

**Issue by medeotl** [IBBoard/cawbird#401]
**Describe the bug**
 emoji chooser button is still unavailable on Cawbird 1.4.2 on my Fedora 34

**To Reproduce**
1. Open Cawbird
2. Try to send a tweet with an emoji

**Expected behavior**
Have the emoji button available to click

**Screenshots**
![FAtAhQ9XMAQJF8z](https://user-images.githubusercontent.com/1864684/135766865-56c9869f-4c31-4aaa-8db4-28c8a7e89a6d.png)

**System details:**
 - OS: Fedora 34
 - Version: 1.4.2
 - Package type: Official RPM

**Additional context**
everithing is ok with Flatpak version

--- medeo:[~] G_MESSAGES_DEBUG=cawbird cawbird
(cawbird:10844): cawbird-DEBUG: 20:38:05.693: Cawbird.vala:277: startup

(cawbird:10844): cawbird-WARNING **: 20:38:05.701: Cawbird.vala:444: Could not add window for account ''
(cawbird:10844): cawbird-DEBUG: 20:38:05.806: Creating stream for medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:05.806: REST: GET 1.1/account/verify_credentials.json
(cawbird:10844): cawbird-DEBUG: 20:38:05.806: REST: GET 1.1/friendships/no_retweets/ids.json
(cawbird:10844): cawbird-DEBUG: 20:38:05.807: REST: GET 1.1/blocks/ids.json
(cawbird:10844): cawbird-DEBUG: 20:38:05.807: REST: GET 1.1/mutes/users/ids.json
(cawbird:10844): cawbird-DEBUG: 20:38:06.530: Account.vala:520: Add 0 disabled_rts ids
(cawbird:10844): cawbird-DEBUG: 20:38:06.784: Account.vala:489: Add 4 blocked ids
(cawbird:10844): cawbird-DEBUG: 20:38:06.785: Account.vala:458: Add 4 muted ids
(cawbird:10844): cawbird-DEBUG: 20:38:06.785: Loading timeline tweets on start
(cawbird:10844): cawbird-DEBUG: 20:38:06.786: Loading timeline tweets
(cawbird:10844): cawbird-DEBUG: 20:38:06.786: REST: GET 1.1/statuses/home_timeline.json
(cawbird:10844): cawbird-DEBUG: 20:38:06.786: Loading mention tweets on start
(cawbird:10844): cawbird-DEBUG: 20:38:06.786: Loading mention tweets
(cawbird:10844): cawbird-DEBUG: 20:38:06.786: REST: GET 1.1/statuses/mentions_timeline.json
(cawbird:10844): cawbird-DEBUG: 20:38:06.786: Loading favourited tweets on start
(cawbird:10844): cawbird-DEBUG: 20:38:06.786: Loading favourited tweets
(cawbird:10844): cawbird-DEBUG: 20:38:06.786: REST: GET 1.1/favorites/list.json
(cawbird:10844): cawbird-DEBUG: 20:38:06.786: Loading DMs on start
(cawbird:10844): cawbird-DEBUG: 20:38:06.786: Loading DM tweets for cursor none
(cawbird:10844): cawbird-DEBUG: 20:38:06.786: REST: GET 1.1/direct_messages/events/list.json
(cawbird:10844): cawbird-DEBUG: 20:38:06.786: Adding timeout for timeline
(cawbird:10844): cawbird-DEBUG: 20:38:06.786: Adding timeout for mentions
(cawbird:10844): cawbird-DEBUG: 20:38:06.786: Adding timeout for favourites
(cawbird:10844): cawbird-DEBUG: 20:38:06.786: Adding timeout for DMs
(cawbird:10844): cawbird-DEBUG: 20:38:07.316: Got 28 mention tweets
(cawbird:10844): cawbird-DEBUG: 20:38:07.316: Message with type 12 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.320: Message with type 12 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.323: Message with type 12 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.329: Message with type 12 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.337: Message with type 12 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.346: Message with type 12 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.352: Message with type 12 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.357: Message with type 12 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.359: Message with type 12 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.362: Message with type 12 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.367: Message with type 12 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.371: Message with type 12 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.374: Message with type 12 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.376: Message with type 12 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.381: Message with type 12 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.385: Message with type 12 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.389: Message with type 12 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.392: Message with type 12 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.396: Message with type 12 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.399: Message with type 12 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.402: Message with type 12 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.405: Message with type 12 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.408: Message with type 12 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.412: Message with type 12 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.416: Message with type 12 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.419: Message with type 12 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.422: Message with type 12 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.425: Message with type 12 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.427: Message with type 33 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.446: Got 28 timeline tweets
(cawbird:10844): cawbird-DEBUG: 20:38:07.446: Message with type 11 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.450: Message with type 11 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.455: Message with type 11 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.458: Message with type 11 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.463: Message with type 11 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.466: Message with type 11 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.470: Message with type 11 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.474: Message with type 11 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.477: Message with type 11 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.481: Message with type 11 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.484: Message with type 11 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.487: Message with type 11 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.491: Message with type 11 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.493: Message with type 11 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.498: Message with type 11 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.502: Message with type 11 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.505: Message with type 11 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.511: Message with type 11 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.514: Message with type 11 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.519: Message with type 11 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.523: Message with type 11 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.528: Message with type 11 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.534: Message with type 11 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.539: Message with type 11 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.543: Message with type 11 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.548: Message with type 11 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.554: Message with type 11 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.561: Message with type 11 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.571: Message with type 32 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.799: Got 0 DMs
(cawbird:10844): cawbird-DEBUG: 20:38:07.799: Message with type 35 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.851: Got 25 favourited tweets
(cawbird:10844): cawbird-DEBUG: 20:38:07.851: Message with type 20 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.854: Message with type 20 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.857: Message with type 20 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.862: Message with type 20 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.865: Message with type 20 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.867: Message with type 20 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.870: Message with type 20 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.872: Message with type 20 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.874: Message with type 20 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.877: Message with type 20 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.880: Message with type 20 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.883: Message with type 20 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.886: Message with type 20 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.889: Message with type 20 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.893: Message with type 20 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.897: Message with type 20 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.899: Message with type 20 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.902: Message with type 20 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.905: Message with type 20 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.909: Message with type 20 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.913: Message with type 20 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.918: Message with type 20 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.922: Message with type 20 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.926: Message with type 20 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.930: Message with type 20 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:07.933: Message with type 34 on stream @medeoTL
(cawbird:10844): cawbird-DEBUG: 20:38:40.694: MainWindow.vala:411: Windows: 1
(cawbird:10844): cawbird-DEBUG: 20:38:40.695: MainWindow.vala:499: Saving geomentry for medeoTL: 541,219,591,700
(cawbird:10844): cawbird-DEBUG: 20:38:40.717: MediaDownloader shutdown

**Comment by IBBoard** [comment]
That's odd. If I run Cawbird and open the compose dialog then I get:
```
…
(cawbird:13571): cawbird-DEBUG: 19:45:40.324: Trying newer emoji data
(cawbird:13571): cawbird-DEBUG: 19:45:40.324: Using emoji/en.data resource
```
which is from the extra debug that I added in 28d698816d3d31eaf01416925f4f4cda49b81d0d. You're not getting that.

I've checked the source code on OBS and that appears to be correct and has the logging in it.

When you say "Official RPM", which 'official' is that? The Cawbird OBS repo or the distro's RPM (because Fedora packages it)? And which exact version (including build number) are you running? (`rpm -q cawbird`)

**Comment by IBBoard** [comment]
Ah… I've just dug around and found the package and its SRPM via [Pkgs.org](https://fedora.pkgs.org/34/fedora-updates-x86_64/cawbird-1.4.2-1.fc34.x86_64.rpm.html) and it looks like Fedora may have managed to grab v1.4.2 in the fifteen minute gap between me publishing the tag and me realising that the emoji fix was still on a branch and re-publishing the tag!

If you're using the Fedora package then you'll have to a) submit a ticket with them and b) ask them nicely not to be quite so eager with grabbing new versions because I occasionally make small mistakes that I fix without making a completely new version 😁

**Comment by medeotl** [comment]
the distro's RPM

--- medeo:[~] rpm -q cawbird
cawbird-1.4.2-1.fc34.x86_64

**Comment by IBBoard** [comment]
Closing on the basis that Fedora managed to sneak in and grab the tag before we were ready 😁
