### ISSUE TITLE
When requesting a new PIN I get a "Forbidden" dialog.

### ISSUE THREAD

**Issue by ProfP30** [IBBoard/cawbird#407]
**Describe the bug**
When requesting a new PIN I get a "Forbidden" dialog.

**To Reproduce**
1. Start cawbird
2. Click on "Request PIN"
3. See error dialog

**Screenshots**
https://ibb.co/XLSHtvx

**System details:**
 - OS: EndeavourOS (Arch Derivate)
 - Kernel: x86_64 Linux 5.15.2-arch1-1
 - Cawbird Version: cawbird-git 1.4.2.r0.g23e5c175-1
 - DE: KDE 5.88.0 / Plasma 5.23.3
 - WM: KWin
 - Display Protocol: happens with X11 as well as Wayland
 - Package type: AUR, see https://aur.archlinux.org/packages/cawbird-git/

**Log messages from CLI via G_MESSAGES_DEBUG=cawbird cawbird:**
```
(cawbird:9877): cawbird-DEBUG: 11:00:30.077: Cawbird.vala:277: startup

** (cawbird:9877): WARNING **: 11:00:30.188: AT-SPI: Could not obtain desktop path or name


** (cawbird:9877): WARNING **: 11:00:30.268: atk-bridge: get_device_events_reply: unknown signature

** (cawbird:9877): WARNING **: 11:00:30.269: atk-bridge: get_device_events_reply: unknown signature

** (cawbird:9877): WARNING **: 11:00:30.282: atk-bridge: GetRegisteredEvents returned message with unknown signature

** (cawbird:9877): WARNING **: 11:00:30.314: AT-SPI: Could not obtain desktop path or name


** (cawbird:9877): WARNING **: 11:00:30.338: AT-SPI: Could not obtain desktop path or name


** (cawbird:9877): WARNING **: 11:00:30.338: AT-SPI: Could not obtain desktop path or name


(cawbird:9877): cawbird-WARNING **: 11:00:34.077: Utils.vala:330: Exception rest-proxy-error-quark:403: Forbidden

(cawbird:9877): cawbird-CRITICAL **: 11:00:34.079: AccountCreateWidget.vala:49: Forbidden
(cawbird:9877): cawbird-DEBUG: 11:00:38.509: MediaDownloader shutdown
```

**Comment by IBBoard** [comment]
Yeah, it's a [known problem](https://twitter.com/CawbirdClient/status/1459255439024173062), although we didn't find out until people started commenting about it on Twitter. We've still not heard anything from Twitter support, but if they've done something to our API keys (or we've hit a user count limit or something that we have no way of identifying) then it will prevent new logins.

**Comment by IBBoard** [comment]
Never got an answer on this. But people are still posting and there haven't been any comments about it for a while, so presumably Twitter undid whatever they did without telling us without telling us 🙄
