### ISSUE TITLE
Missing Replies

### ISSUE THREAD

**Issue by qingxiang-jia** [IBBoard/cawbird#408]
**Describe the bug**
I used to be able to see replies of a tweet. Now they are gone. But the web Twitter still has it.

**To Reproduce**
1. Go to any tweet (that has at least one reply).
2. Go to the same tweet on Cawbird.

**Expected behavior**
Replies are displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/5571586/142484646-23fc7d13-d602-49f8-a2a4-f8ecadc6a305.png)

**System details:**
 - OS: Arch
 - Version: 1.4.2
 - Package type: Arch/Community [Link](https://archlinux.org/packages/community/x86_64/cawbird/)

**Additional context**

Running `G_MESSAGES_DEBUG=cawbird cawbird` shows the following when opening a tweet with replies:
```
(cawbird:10555): cawbird-WARNING **: 14:36:55.696: ../cawbird-1.4.2/src/CbUtils.c(call_done_cb): 0x56285165ea90, 1.1/statuses/lookup.json Forbidden

(cawbird:10555): cawbird-WARNING **: 14:36:55.696: TweetInfoPage.vala:663: Forbidden
```

**Comment by IBBoard** [comment]
The "Forbidden" message makes it look like a variation of #407.

Twitter have told us exactly *nothing* about why we're getting Forbidden messages, and why it's only affecting some users and not others. They must have done something to limit our access.

**Comment by qingxiang-jia** [comment]
Thanks for the timely reply. You mentioned in the linked issue that it might have something to do with the API key used in the app. Is there any chance we could make it configurable so that each user would have her own key?

**Comment by IBBoard** [comment]
We did some work on that for #310 and released it in [v1.4](https://github.com/IBBoard/cawbird/releases/tag/v1.4). It supports different accounts using different keys (I use Cawbird for the project's account, Cawbird Unstable for my test account and Cawbird IBBoard Dev keys for my account). It just doesn't have any UI.

You need to set the `consumer-key` and `consumer-secret` in dconf's `uk.co.ibboard.cawbird` schema to your custom values. Something like `dconf set uk.co.ibboard.cawbird consumer-key your-key` should work, but I'm not on my PC so I can't check.

**Comment by qingxiang-jia** [comment]
Thanks for the help. I got my API key and API key secret. Replies still don't load so I signed out and sign in. It asks me to authorize my app (this time not Cawbird because I got my own set of API access). In the popped up browser windows, I click "authorize" and entered the PIN. The app stuck at that page so I ran it with `G_MESSAGE_DEBUG`. I got the following:

```
Opening in existing browser session.
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[19860:19860:0100/000000.759788:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.

(cawbird:19804): cawbird-WARNING **: 18:20:15.433: ../cawbird-1.4.2/src/CbUtils.c(call_done_cb): 0x55e9394a6bb0, 1.1/account/settings.json Forbidden

(cawbird:19804): cawbird-WARNING **: 18:20:15.433: AccountCreateWidget.vala:115: Could not get json data: Forbidden
```

**Comment by IBBoard** [comment]
Twitter sometimes has a cool-down period on new registrations, so spammers can't just create new apps and start spamming straight away. How long was it between request, approval and using the keys?

Also, is it valid for the v1.1 API (which we still use) or is it a newer key that's only valid for the v2 API until you get "Enhanced" access?

**Comment by qingxiang-jia** [comment]
I checked. I think I am getting the 2.0 API unfortunately. The 1.0 is indeed marketed as "premium". I will look for ways to get 1.0 API without paying Twitter. Also, I noticed since I got this issue, I started seeing "Twitter Blue" ads. Hopefully it's just a coincidence.

**Comment by qingxiang-jia** [comment]
I have searched around but it seems I can only get the new 2.0 API. Therefore there doesn't seem to be a way to solve my issue. You can close it. Maybe we could collectively find a way to use the 1.0 API (there's also a non premium 1.0 API). Or I don't know if it's possible to start using 2.0 APIs.

Thanks.

**Comment by IBBoard** [comment]
The v2 API is already planned under #180 and as part of @CodedOre's "Cawbird 2.0" rebuild that will support Mastodon as well.
