### ISSUE TITLE
Key expired

### ISSUE THREAD

**Issue by heynnema** [IBBoard/cawbird#415]
Ubuntu 21.10

$ sudo apt update

Err:16 http://download.opensuse.org/repositories/home:/IBBoard:/cawbird/xUbuntu_21.10  InRelease
  The following signatures were invalid: EXPKEYSIG A7A55B845DCFCBE2 home:IBBoard OBS Project <home:IBBoard@build.opensuse.org>

W: GPG error: http://download.opensuse.org/repositories/home:/IBBoard:/cawbird/xUbuntu_21.10  InRelease: The following signatures were invalid: EXPKEYSIG A7A55B845DCFCBE2 home:IBBoard OBS Project <home:IBBoard@build.opensuse.org>
E: The repository 'http://download.opensuse.org/repositories/home:/IBBoard:/cawbird/xUbuntu_21.10  InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

**Comment by IBBoard** [comment]
Already reported and fix in #412. You need to download the new key and replace the old one.
