### ISSUE TITLE
Click to play video results in error

### ISSUE THREAD

**Issue by neilzone** [IBBoard/cawbird#417]
**Describe the bug**
Attempting to play a video in Cawbird results in an error:

```
gstdecodebin2.c(4694): gst_decode_bin_expose (): /GstPlayBin:video/GstURIDecodeBin:uridecodebin3/GstDecodeBin:decodebin3:
all streams without buffers
```

**To Reproduce**
I saw [this Tweet](https://twitter.com/TrungTPhan/status/1483486519302127616) in Cawbird.

I clicked the "Play" icon in the middle of the screen.

I get the error message:

```
gstdecodebin2.c(4694): gst_decode_bin_expose (): /GstPlayBin:video/GstURIDecodeBin:uridecodebin3/GstDecodeBin:decodebin3:
all streams without buffers
```

**Expected behavior**
Video to play

**System details:**
 - OS: Debian 11
 - Cawbird version: 1.4.2
 - Package type: Snap

**Comment by CodedOre** [comment]
Could be related to #403...

The problem there was that GStreamer was not up-to-date, updating the runtime fixed this.

Who is maintaining the Snap package anyway, @IBBoard?

**Comment by CodedOre** [comment]
Found the [repository](https://github.com/diddlesnaps/cawbird) for the snap packaging, and as far as I can tell it is still based on Gnome 3.38 with the older GStreamer, exactly the same issue the Flatpak had.

@diddledani, you are (to my knowledge) the maintainer of this repository, so could you take a look on this?

**Comment by IBBoard** [comment]
Yeah, the Snap isn't official ([see Snapcraft](https://snapcraft.io/cawbird)). There's already other [open issues around video](https://github.com/diddlesnaps/cawbird/issues?q=is%3Aissue+is%3Aopen+video).

We have official packages for Debian 11. I'd recommend uninstalling the Snap and using the native package from https://software.opensuse.org//download.html?project=home%3AIBBoard%3Acawbird&package=cawbird. It has the (significant) advantage that any libraries it depends on will be properly maintained by your distribution.

**Comment by neilzone** [comment]
> We have official packages for Debian 11. I'd recommend uninstalling the Snap and using the native package

Even better. I’ll give it a try.

Many thanks, everyone.
