### ISSUE TITLE
Add more metadata for GNOME Software

### ISSUE THREAD

**Issue by MikuOcta** [IBBoard/cawbird#454]
The app does a great job by being adaptive for small devices as well, but beacuse the lack of metadata information for the app, Software it says the app is only for desktops. We would really like if the metadata was added!

![image](https://user-images.githubusercontent.com/81514969/169703634-2b913475-e0fd-436b-ba2d-36bfc2f66e05.png)
_Software not having enough metadata for displaying the adaptivibility features_

Here is more informations:
https://gitlab.gnome.org/GNOME/gnome-software/-/wikis/software-metadata#hardware-support

**Comment by IBBoard** [comment]
Apparently we need
```
  <recommends>
    <control>pointing</control>
    <control>keyboard</control>
    <control>touch</control>
  </recommends>
```
if we want to be listed as "adaptive"? Even though we support but don't recommend touch?

If I move `touch` to a `<supports>` block then we apparently don't support touch.

![Screenshot of Gnome Software "Supports" list](https://user-images.githubusercontent.com/388582/170114313-4977662f-0247-46eb-9993-e1e6d9ae0d96.png)

That seems wrong to me.
