### ISSUE TITLE
Ability to click on the app when it is not in focus, without opening a tweet

### ISSUE THREAD

**Issue by rjray** [IBBoard/cawbird#466]
**Is your feature request related to a problem? Please describe.**
I find it frustrating to click on the app when it isn't in focus, only to have it immediately jump to whichever tweet the mouse landed on.

**Describe the solution you'd like**
It seems that a double-click action to open a tweet would be more intuitive, and would circumvent this issue.

**Comment by IBBoard** [comment]
Double-click to open tweets is already an option (and it's what I use). It's in Settings under "Timeline" in the "Interface" section. But single-click was the old Corebird behaviour, so we kept with the default in case it confused people.
