### ISSUE TITLE
Translate Cawbird properly

### ISSUE THREAD

**Issue by IBBoard** [IBBoard/cawbird#47]
As it says in the Readme, we're currently still using Corebird's Transifex translations. As the UI changes then we will need updated translations.

We need to:
  1) Setup Transifex for this project
  2) Find and update any strings that I've added that haven't been updated
  3) Work out how the translation build works!

**Comment by rahulrajpl** [comment]
Happy to help. Project forked!

**Comment by IBBoard** [comment]
I *think* we now have Transifex working - https://www.transifex.com/cawbird/cawbird/dashboard/

Any feedback/comments (and translations!) welcome.

cc @albanobattistella

**Comment by IBBoard** [comment]
Ukrainian and Lithuanian are currently being rejected because:

>  Invalid plural types for string: %d new Message from %s:%d new Messages from %s. Language supports: ['one', 'few', 'many', 'other'], but found: ['one', 'few', 'many'] instead. 

Turkish is being rejected because:

> Invalid plural types for string: %d new Message from %s:%d new Messages from %s. Language supports: ['one', 'other'], but found: ['one'] instead.

Being an English speaker who is new to internationalisation (and Transifex) I'm still trying to work out what this means, and why it was fine on Corebird's Transifex!

**Comment by IBBoard** [comment]
The inward sync doesn't seem to be working too well (all the changes to Turkish, Serbian etc weren't changing anything) but it's starting to work now that I'm uploading the failed files manually.

**Comment by IBBoard** [comment]
I think I'm going to close this now. Transifex appears to be up and running and connected to GitHub. The Transifex bot has been trying to push translations back (but mainly just reformatting of existing translations - while losing the translator details and attributing it to me!).

If anyone finds any problems then open a ticket. If anyone can translate anything then please go to [Transifex](https://www.transifex.com/cawbird/cawbird/dashboard/).
