### ISSUE TITLE
No Ubuntu 19.10 repo?

### ISSUE THREAD

**Issue by jdrch** [IBBoard/cawbird#48]
I know 19.10 just released so I'm not upset about this, just filing a bug so adding a corresponding repo is on the to-do list. Thanks :)

**Comment by IBBoard** [comment]
19.10 is now available for OBS projects to use. I've added it and the pre-build is in progress.

https://build.opensuse.org/package/show/home:IBBoard:cawbird/cawbird

**Comment by jdrch** [comment]
Thanks! Same key or different one?

**Comment by IBBoard** [comment]
Should be the same key - it appears to be my "home:IBBoard" key rather than one project (home:IBBoard:cawbird) or per-repo.

**Comment by jdrch** [comment]
OK, thanks! I'll try it later :)
