### ISSUE TITLE
Cawbird does not start on Arch Linux

### ISSUE THREAD

**Issue by fakeid30** [IBBoard/cawbird#50]
[This is the whole error log](https://github.com/IBBoard/cawbird/files/3749476/error.txt)

[This is the installation instruction](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=cawbird-git)

**Comment by undevdecatos** [comment]
Use this PKGBUILD instead: https://del.dog/aleqaqariq

**Comment by starvald** [comment]
would build for me until i changed pkgname=cawbird-12 to pkgname=cawbird
this build doesn't crash for me. ty.

**Comment by undevdecatos** [comment]
It's because the version 1.0.3 is broken

**Comment by undevdecatos** [comment]
#51

**Comment by IBBoard** [comment]
I'll close this as a dupe/upstream and use #51 as the main ticket.

(I'd have expected to see a segfault at the end of the log, though).
