### ISSUE TITLE
Crash in the Cawbird constructor: Error opening directory ~/.config/corebird/image-favorites/: No such file or directory

### ISSUE THREAD

**Issue by Kekun** [IBBoard/cawbird#55]
Well of course it doesn't exist, I didn't use Corebird, and I am currently using Cawbird. :man_shrugging:

This was master, just after compiling it on Debian stable and running it.

**Comment by IBBoard** [comment]
Ah, that's my new "migrate favourited images from Corebird" code. Must have missed an "if exists" check.
