### ISSUE TITLE
Make avatars round

### ISSUE THREAD

**Issue by Kekun** [IBBoard/cawbird#56]
That's what GNOME moves to, and what the web version of Twitter does.

**Comment by IBBoard** [comment]
Settings > Tweets > Enable "Round Avatars".

It has been in there since Corebird. We just default to square because round makes so many normal avatars look unnecessarily bad.

![avatars](https://user-images.githubusercontent.com/388582/69008711-a4c52b80-0945-11ea-8145-3ffc6ed274d8.jpg)
