### ISSUE TITLE
Choppy audio and video

### ISSUE THREAD

**Issue by nedludd** [IBBoard/cawbird#58]
Can anything be done to improve the quality of embedded audio?  

I know Cawbird relies on external libraries for that, but it seems really bad.

Cawbird version: v1.0.3.1.r9.g07043c28-1
Archlinux: 5.3.11-arch1-1

```
extra/gst-plugins-ugly 1.16.1-2 (190.0 KiB 666.2 KiB) (Installed)
extra/gst-plugins-good 1.16.1-1 (1.6 MiB 5.9 MiB) (Installed)
extra/gst-plugins-base-libs 1.16.1-1 (2.1 MiB 17.1 MiB) (Installed)
extra/gst-plugins-base 1.16.1-1 (278.1 KiB 932.0 KiB) (Installed)
extra/gst-plugins-bad 1.16.1-4 (1.9 MiB 8.1 MiB) (Installed)
extra/libavc1394 0.5.4-3 (30.5 KiB 108.0 KiB) (Installed)
extra/gst-libav 1.16.1-1 (81.7 KiB 231.0 KiB) (Installed)
extra/ffmpeg 1:4.2.1-4 (8.8 MiB 30.2 MiB) (Installed)
```

**Comment by IBBoard** [comment]
It's apparently [a GStreamer 1.16.1 bug](https://github.com/IBBoard/cawbird/pull/42#issuecomment-539437887). @p1u3o and @TingPing found and discussed it when building the Flatpak a month ago. We can't do anything to fix it in the main Cawbird. I don't know whether it was reported upstream.

Anyone know more?

**Comment by IBBoard** [comment]
As per @p1u3o's [findings](https://github.com/IBBoard/cawbird/pull/42#issuecomment-558073420) - it's apparently [now fixed and backported](https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/commit/cfa0f1858075a3390def50250eafc89d270178d3). We just need to wait for it to be released and for distros to package it.

**Comment by nedludd** [comment]
Finally got the `gst-plugins-bad` update in Arch.  This fixes the issue as you noted.  Thanks.
