### ISSUE TITLE
Tweet length counting miscounts d3.select()

### ISSUE THREAD

**Issue by IBBoard** [IBBoard/cawbird#64]
Sometimes Twitter's length count is different to ours. Sometimes Cawbird thinks a tweet is short enough to post, but Twitter disagrees and refuses to post the tweet.

[This tweet](https://twitter.com/IBBoard/status/1197170807635619840) is one example that wouldn't post and that I had to fix with spaces. Apparently `d3.select(nodes[i].parentNode). data()[0]` was getting partially linkified because [.select is a TLD](https://icannwiki.org/.select) and so the 9 characters `d3.select` were getting turned in to a 23 character URL.

**Comment by IBBoard** [comment]
We should have most things covered with Baedert's libtl library (which is [embedded](https://github.com/IBBoard/cawbird/tree/master/src/libtl)). It lists [lots of the new gTLDs](https://github.com/IBBoard/cawbird/blob/master/src/libtl/data.h) but apparently there are now more.

**Comment by c64whiz** [comment]
Just wanted to add to this issue as I've run into the opposite.  Cawbird's counter shows 13 chars left, but Twitter is already in the red.  When I attempt to send the Tweet, Cawbird _then_ says it's too long (but still showing 13 more chars).  See image:

![error](https://user-images.githubusercontent.com/410595/91595500-7df64580-e918-11ea-9986-d0d44b25292e.png)

**Comment by IBBoard** [comment]
I think that's the same problem - Cawbird doesn't treat it as a URL (so it's only a few characters) but Twitter does (so it's 23 characters). Cawbird lets you submit, but then Twitter rejects it.

What was the full text of the tweet? Was it just dhl.de that became a link? Because that would be an odd one for Baedert to have missed in the libtl library! (Unless I broke something with a later update)
