### ISSUE TITLE
src/libtl/libtweetlength.c:359: bad test ?

### ISSUE THREAD

**Issue by dcb314** [IBBoard/cawbird#65]
src/libtl/libtweetlength.c:359:19: warning: logical 'and' of mutually exclusive tests is always false [-Wlogical-op]

Source code is

     (ch >= 8424 && ch <= 8247)) {

Comment says:

 //   * 8242 - 8247 (Prime marks)

**Comment by IBBoard** [comment]
Decimal 8242 is a [prime mark](https://www.fileformat.info/info/unicode/char/2032/index.htm) while 8424 is ["combining triple underdot"](https://www.fileformat.info/info/unicode/char/20e8/index.htm). Looks like the comment is correct and the code is a typo.
