### ISSUE TITLE
'uk.co.ibboard.cawbird' is not installed

### ISSUE THREAD

**Issue by newincpp** [IBBoard/cawbird#71]
Hi, I just tried to download and compile a release version of cawbird. The compilation went fine but it crashes at startup.
(I'm running gentoo so sources are the way to go).
Here is the whole log: https://gist.github.com/newincpp/615e41b8bff3d6a8d76c427f3d95af22
I tried to investigate why:
The json is there so there is no apparent reason for this message to happen:
```
newin@vega cawbird-1.0.3 % find . | grep ibboard.cawbird.json
./flatpak/uk.co.ibboard.cawbird.json
```
Then I tried to `strace -o /tmp/cawstrace ./build/cawbird`
And here is what I found:
```
newin@vega cawbird-1.0.3 % cat /tmp/cawstrace| grep json
openat(AT_FDCWD, "/home/newin/project/twitter/cawbird-1.0.3/build/libjson-glib-1.0.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib64/libjson-glib-1.0.so.0", O_RDONLY|O_CLOEXEC) = 3
```
I'm not sure how or why but the problem isn't really the json itself rather than libjson.
Did I missed something on the compilation/install/dependencies ?

**Comment by IBBoard** [comment]
My best guess is that you're missing libjson-glib. The Meson build builds a native binary, so the files in the `flatpak` directory won't affect anything and we don't bundle any libraries like that.

Based on the log then you might also be missing the dconf schema:

`GLib-GIO-ERROR **: 15:48:35.458: Settings schema 'uk.co.ibboard.cawbird' is not installed`

That would normally be installed in the "install" phase, but you appear to have just built it and run it from the build directory.

**Comment by newincpp** [comment]
I have a libjson-glib:
```
newin@vega ~ % ls /usr/lib/libjson-glib-1.0.so
/usr/lib/libjson-glib-1.0.so
```
I didn't check if meson should copy mine or build its own (you seems to say it should have build its own?). So there is either a bug or I missed something in the install process.

**Comment by IBBoard** [comment]
Meson/Ninja shouldn't do anything with the library. Cawbird will build with a dynamic link and then it'll load it at run time.

[dconf](https://wiki.gnome.org/Projects/dconf) is Gnome's settings registry. It's a replacement for the older gconf system. Cawbird accesses dconf via GSettings from GLib, so there isn't a direct dependency and it's assumed that it's installed (and that our specific schema is installed).

**Comment by newincpp** [comment]
Okay so I'm not sure what is happening then I have glib, I have dconf and meson list json-glib as found. I don't understand what's wrong then.
Also I did test with copying my own json-glib and strace tells me that cawbird doesn't even try to access the uk.co.ibboard.cawbird.json it just appear nowhere in the log.

**Comment by IBBoard** [comment]
> cawbird doesn't even try to access the uk.co.ibboard.cawbird.json

No, and I wouldn't expect it to. That's for building the Flatpak version. Cawbird doesn't need that JSON file at all.



> Okay so I'm not sure what is happening then I have glib, I have dconf and meson list json-glib as found. I don't understand what's wrong then.

I think the JSON is a red herring and you found an unimportant line in the log file at first.

You've got dconf installed but you don't appear to have installed Cawbird's dconf schema. Installing the schema is part of the install process rather than the build process. If you do a `meson build && ninja -C build` then you've only built it, not installed it. You need to do a `ninja install -C build` (may need other arguments, depending on how Gentoo works).

**Comment by newincpp** [comment]
`ninja install -C build` (in superuser) made it to work. Thank you !
maybe you should drop a line about that in the readme.md ?
