### ISSUE TITLE
Make a window for sending Direct Messages a horizontal Gtk.paned

### ISSUE THREAD

**Issue by gavr123456789** [IBBoard/cawbird#72]
There are inmposible to write long message:  

![image](https://user-images.githubusercontent.com/30507409/72216608-38753b80-3534-11ea-8920-0357cb850e0f.png)

**Comment by IBBoard** [comment]
It does scroll, so you can still write long messages and see them, but oddly the scroll bar doesn't seem to work (so I can scroll with the mouse wheel but not by dragging the scroll bar)
