### ISSUE TITLE
Meson deprecation warning: Duplicated values in array option is deprecated. This will become a hard error in the future.

### ISSUE THREAD

**Issue by schmittlauch** [IBBoard/cawbird#74]
When building Cawbird with Meson 0.51.2 I get the following deprecation warning: `DEPRECATION: Duplicated values in array option is deprecated. This will become a hard error in the future.`

I just want to make sure this is on your radar.

**Comment by IBBoard** [comment]
Got a file and line number for that? I don't know what it means, so it'll be fun to track down without one!

There are several other warnings that we probably need to clear up as well.

**Comment by schmittlauch** [comment]
No, no line numbers.
Maybe you can deduce something from the build output?

```
unpacking sources
unpacking source archive /nix/store/wncaabvrnw7zkga81j8war977vqwipwa-source
source root is source
patching sources
patching script interpreter paths in data/meson_post_install.py
data/meson_post_install.py: interpreter directive changed from "/usr/bin/env python3" to "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/bin/python3"
configuring
meson flags: --buildtype=plain         --libdir=/nix/store/yh7ywmrafwnrzqnbvx1qiqy35p4ygb8k-cawbird-1.0.4/lib --libexecdir=/nix/store/yh7ywmrafwnrzqnbvx1qiqy35p4ygb8k-cawbird-1.0.4/libexec         --bindir=/nix/store/yh7ywmrafwnrzqnbvx1qiqy35p4ygb8k-cawbird-1.0.4/bin --sbindir=/nix/store/yh7ywmrafwnrzqnbvx1qiqy35p4ygb8k-cawbird-1.0.4/sbin         --includedir=/nix/store/yh7ywmrafwnrzqnbvx1qiqy35p4ygb8k-cawbird-1.0.4/include         --mandir=/nix/store/yh7ywmrafwnrzqnbvx1qiqy35p4ygb8k-cawbird-1.0.4/share/man --infodir=/nix/store/yh7ywmrafwnrzqnbvx1qiqy35p4ygb8k-cawbird-1.0.4/share/info         --localedir=/nix/store/yh7ywmrafwnrzqnbvx1qiqy35p4ygb8k-cawbird-1.0.4/share/locale         -Dauto_features=enabled         -Dwrap_mode=nodownload         --prefix=/nix/store/yh7ywmrafwnrzqnbvx1qiqy35p4ygb8k-cawbird-1.0.4  
The Meson build system
Version: 0.51.2
Source dir: /home/spiollinux/tmp/cawbirdtest/source/source
Build dir: /home/spiollinux/tmp/cawbirdtest/source/source/build
Build type: native build
DEPRECATION: Duplicated values in array option is deprecated. This will become a hard error in the future.
DEPRECATION: Duplicated values in array option is deprecated. This will become a hard error in the future.
DEPRECATION: Duplicated values in array option is deprecated. This will become a hard error in the future.
Project name: Cawbird
Project version: 1.0.4
C compiler for the host machine: /nix/store/291ldi6fqsbmkbvbs8is4mcg3jb64ld4-gcc-wrapper-8.3.0/bin/cc (gcc 8.3.0 "gcc (GCC) 8.3.0")
Vala compiler for the host machine: valac (valac 0.44.6)
DEPRECATION: Duplicated values in array option is deprecated. This will become a hard error in the future.
Build machine cpu family: x86_64
Build machine cpu: x86_64
Library m found: YES
Found pkg-config: /nix/store/39cdzh05fzi13f06pa0rly3d5l53vsfk-pkg-config-0.29.2/bin/pkg-config (0.29.2)
Run-time dependency glib-2.0 found: YES 2.60.7
Run-time dependency gtk+-3.0 found: YES 3.24.10
Run-time dependency json-glib-1.0 found: YES 1.4.4
Run-time dependency sqlite3 found: YES 3.28.0
Run-time dependency libsoup-2.4 found: YES 2.66.4
Run-time dependency gstreamer-video-1.0 found: YES 1.16.0
Run-time dependency gspell-1 found: YES 1.8.1
Found pkg-config: /nix/store/39cdzh05fzi13f06pa0rly3d5l53vsfk-pkg-config-0.29.2/bin/pkg-config (0.29.2)
Configuring config.h using configuration
Program meson_post_install.py found: YES (/home/spiollinux/tmp/cawbirdtest/source/source/data/meson_post_install.py)
Configuring uk.co.ibboard.cawbird.service using configuration
Build targets in project: 24
Option buildtype is: plain [default: debug]
Found ninja-1.9.0 at /nix/store/lh64jjlnvmi8yrw3ynwf5nm86b8idp8m-ninja-1.9.0/bin/ninja
meson: enabled parallel building
building
build flags: -j4 -l4
```

**Comment by IBBoard** [comment]
Huh. From a quick Google then it looks like it's the arguments that are being sent to Meson that are duplicated (which isn't obvious from the phrase "array option"). I'll have to dig in to it and see what we're passing twice.

A wild stab in the dark would be "--buildtype", but that's based on nothing more than it being unlikely that we duplicate --libdir etc

**Comment by IBBoard** [comment]
I'm trying to find more info on this. So far all that I've found is a Meson bug: https://github.com/mesonbuild/meson/issues/5736

**Comment by IBBoard** [comment]
Can you tell how Meson is being invoked for it to trigger that error? I'm running 0.51.2 on openSUSE Tumbleweed and I don't see any deprecation/duplication warnings. I can't see it on our OBS builds either.

```
[  258s] + /usr/bin/meson --buildtype=plain --prefix=/usr --libdir=/usr/lib64 --libexecdir=/usr/libexec --bindir=/usr/bin --sbindir=/usr/sbin --includedir=/usr/include --datadir=/usr/share --mandir=/usr/share/man --infodir=/usr/share/info --localedir=/usr/share/locale --sysconfdir=/etc --localstatedir=/var --sharedstatedir=/var/lib --wrap-mode=nodownload --auto-features=enabled . x86_64-redhat-linux-gnu
[  266s] The Meson build system
[  266s] Version: 0.51.2
[  266s] Source dir: /home/abuild/rpmbuild/BUILD/cawbird-1.0.4
[  266s] Build dir: /home/abuild/rpmbuild/BUILD/cawbird-1.0.4/x86_64-redhat-linux-gnu
[  266s] Build type: native build
[  266s] Project name: Cawbird
[  266s] Project version: 1.0.4
```

**Comment by schmittlauch** [comment]
Output caused by `set -x`, so don't mind the `++` signs:

```console
++ mesonFlags='--prefix=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4 '
++ '[' -n '' ']'
++ mesonFlags='        --libdir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/lib --libexecdir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/libexec         --bindir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/bin --sbindir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/sbin         --includedir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/include         --mandir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/share/man --infodir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/share/info         --localedir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/share/locale         -Dauto_features=enabled         -Dwrap_mode=nodownload         --prefix=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4 '
++ mesonFlags='--buildtype=plain         --libdir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/lib --libexecdir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/libexec         --bindir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/bin --sbindir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/sbin         --includedir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/include         --mandir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/share/man --infodir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/share/info         --localedir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/share/locale         -Dauto_features=enabled         -Dwrap_mode=nodownload         --prefix=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4 '
++ echo 'meson flags: --buildtype=plain         --libdir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/lib --libexecdir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/libexec         --bindir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/bin --sbindir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/sbin         --includedir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/include         --mandir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/share/man --infodir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/share/info         --localedir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/share/locale         -Dauto_features=enabled         -Dwrap_mode=nodownload         --prefix=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4  '
meson flags: --buildtype=plain         --libdir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/lib --libexecdir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/libexec         --bindir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/bin --sbindir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/sbin         --includedir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/include         --mandir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/share/man --infodir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/share/info         --localedir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/share/locale         -Dauto_features=enabled         -Dwrap_mode=nodownload         --prefix=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4  
++ CC=/nix/store/snzyfhfnzw6bxp7k73bd2n22rrxm4sjr-gcc-wrapper-9.2.0/bin/cc
++ CXX=/nix/store/snzyfhfnzw6bxp7k73bd2n22rrxm4sjr-gcc-wrapper-9.2.0/bin/c++
++ meson build --buildtype=plain --libdir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/lib --libexecdir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/libexec --bindir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/bin --sbindir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/sbin --includedir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/include --mandir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/share/man --infodir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/share/info --localedir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/share/locale -Dauto_features=enabled -Dwrap_mode=nodownload --prefix=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4
```

**Comment by IBBoard** [comment]
Something odd is happening. I can't even recreate that if I run

```
meson build --buildtype=plain --libdir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/lib --libexecdir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/libexec --bindir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/bin --sbindir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/sbin --includedir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/include --mandir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/share/man --infodir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/share/info --localedir=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4/share/locale -Dauto_features=enabled -Dwrap_mode=nodownload --prefix=/nix/store/nq9wll5ndmi9mm6nh85y5s4kiiqfbdx8-cawbird-1.0.4
```

How brave do you feel in debugging this? Because my next step would be to work out what Meson thinks it has duplicated, and the quickest way that I can see to do that is to edit Meson's `coredata.py` and turn:

```
        else:
            raise MesonException('"{}" should be a string array, but it is not'.format(newvalue))

        if not self.allow_dups and len(set(newvalue)) != len(newvalue):
```

into:

```
        else:
            raise MesonException('"{}" should be a string array, but it is not'.format(newvalue))
        print(new_value)
        print(set(newvalue))
        if not self.allow_dups and len(set(newvalue)) != len(newvalue):
```

But that's hacking in your OS libraries rather than just Cawbird code, **so I'd recommend backups and only doing it if you're happy you can undo it and fix Meson if it breaks!** However, my output all comes out as empty sets, so it'd be informative to see what you've got that's different.

**Comment by schmittlauch** [comment]
That's my (rather long) $PKG_CONFIG_PATH when building cawbird:

`/nix/store/kr7f864agbgjb4qmlr1ji0j5kdhn6d9m-vala-0.46.5/lib/pkgconfig:/nix/store/s7vw8y02cqzx8bnjxl4bkhlnwvz6ws1s-python3-3.7.6/lib/pkgconfig:/nix/store/mn0f14glffxd6qh8kxpl50bzz1rkha5b-gobject-introspection-1.62.0-dev/lib/pkgconfig:/nix/store/jyn34rgd33h0diws5hgdy6ycsqd0v9gh-libffi-3.3-dev/lib/pkgconfig:/nix/store/20jfnqdap9kni2gir3lxb12m4mhrfkx6-glib-2.62.4-dev/lib/pkgconfig:/nix/store/72mklszjlpy55iiici6waz69dm5sphgf-zlib-1.2.11-dev/lib/pkgconfig:/nix/store/79k23ba41sqbr95x32zyb0w0k3smkkwk-gtk+3-3.24.12-dev/lib/pkgconfig:/nix/store/v0vkf12zsbhp2ndr1cwhrd67dnzmrm4w-at-spi2-atk-2.34.1/lib/pkgconfig:/nix/store/az71xbzia8aah1lswg1jwn0jf6gs1ffl-atk-2.34.1-dev/lib/pkgconfig:/nix/store/h6zaxr8kqn4c07v23crd5lq7d709k53v-cairo-1.16.0-dev/lib/pkgconfig:/nix/store/2hwaahrsw0r3ln1qlmlyihp08ds5daaf-fontconfig-2.12.6-dev/lib/pkgconfig:/nix/store/8h3k2kwa8vl2fic6sjn7jp6a6x9asfv0-freetype-2.10.1-dev/lib/pkgconfig:/nix/store/4jlms8pb06x5i267in9fw5qgc5k5sh09-bzip2-1.0.6.0.1-dev/lib/pkgconfig:/nix/store/7vabncllgbbd1k2gh8pazz5605r3zi4a-libpng-apng-1.6.37-dev/lib/pkgconfig:/nix/store/zxfjbpzhklj0vzw1qm836xwi2kd7wghy-expat-2.2.8-dev/lib/pkgconfig:/nix/store/nnazh72i9dhdl43ykkmw70y6lg60mhxw-pixman-0.38.4/lib/pkgconfig:/nix/store/qwqk3526d2avm6fnh1za74zjwn6a9ysz-libXext-1.3.4-dev/lib/pkgconfig:/nix/store/104zjprzidpbjx37l17bffbi6jgc69n1-xorgproto-2019.1/share/pkgconfig:/nix/store/7adia28fzsvv4bghjsdskim2dxh57sih-libXau-1.0.9-dev/lib/pkgconfig:/nix/store/52l8w18lggzynb8pqsjbzwwcjmjmzi1j-libXrender-0.9.10-dev/lib/pkgconfig:/nix/store/8vanm0flvl6c2q2d3sgmw4gx1qmpr78z-libX11-1.6.8-dev/lib/pkgconfig:/nix/store/vv58yhx3vznswgycifqd2h24m51y459q-libxcb-1.13.1-dev/lib/pkgconfig:/nix/store/6zqihahwmwz0w8fiqxw0ria4cvi230ma-xcb-util-0.4.0-dev/lib/pkgconfig:/nix/store/f3g2avcl6lnkxih197afgf2q517qp0gi-libGL-1.2.0-dev/lib/pkgconfig:/nix/store/vgk6q2ppnq1la4q8r1rjjv4v6s586laj-libglvnd-1.2.0-dev/lib/pkgconfig:/nix/store/gmik66cvidwqg6cbvpajk7619q9zlmww-fribidi-1.0.7/lib/pkgconfig:/nix/store/gy1aiqx2rca0nr4rfdd62fw1l4paq858-gdk-pixbuf-2.40.0-dev/lib/pkgconfig:/nix/store/z3k0gqb2i1hyikbji9kjqjdd1rv10w2k-libtiff-4.1.0-dev/lib/pkgconfig:/nix/store/vsas0dyj6ykl2xj8i1gql8l2rdfcnm3r-libjpeg-turbo-2.0.3-dev/lib/pkgconfig:/nix/store/pzz1xyyp18i4ws0isrfbdfpdcpxb290n-xz-5.2.4-dev/lib/pkgconfig:/nix/store/3p8zld8q7lndi1xwmfc6b747wwcfn2v6-gsettings-desktop-schemas-3.34.0/share/pkgconfig:/nix/store/f8za7xmxlas6lsr8xqspqk4hqva5w8im-libICE-1.0.10-dev/lib/pkgconfig:/nix/store/jrmbzpccjd7w9ci9g7m65la21mkjasvq-libSM-1.2.3-dev/lib/pkgconfig:/nix/store/9gnf7aprjkacwrksqdb0rxv6b6hmgzwg-libXcomposite-0.4.5-dev/lib/pkgconfig:/nix/store/yyqkghivryjcimxqscmmsjav4yk6f5wm-libXfixes-5.0.3-dev/lib/pkgconfig:/nix/store/40jc7cbj1jmw0s9n58payahpy3a7h8c7-libXcursor-1.2.0-dev/lib/pkgconfig:/nix/store/dlmjfqgxzgf61n2q1jhcgfgd0sy990sk-libXi-1.7.10-dev/lib/pkgconfig:/nix/store/m528dkc38sh7s14819cldrxp2mg8py6c-libXrandr-1.5.2-dev/lib/pkgconfig:/nix/store/shj6fsslcr630qbwd191sn1j4522v2sj-pango-1.44.7-dev/lib/pkgconfig:/nix/store/gz3vz893xvvqrfw7arw90ysjf3fd1z49-harfbuzz-2.6.4-dev/lib/pkgconfig:/nix/store/ls3pmzf7rrvrsqbyq7gl9h4ci5j9qkhy-graphite2-1.3.13/lib/pkgconfig:/nix/store/1zv9hd97msqrs0iphhy2c5yx0mqh5d8k-libXft-2.3.3-dev/lib/pkgconfig:/nix/store/208f971p8llm75kfgb9qsm7aibip78ns-mesa-19.3.1-dev/lib/pkgconfig:/nix/store/zvzqilx051k5wjpx2w02q4i387v4dbmg-libXdamage-1.1.5-dev/lib/pkgconfig:/nix/store/jbx0mbnqv4w5330gf3dyqc4wq63xccnn-libXxf86vm-1.1.4-dev/lib/pkgconfig:/nix/store/zxc7jqkyxfb10l9s91lx2cgj2nz5mhdk-libdrm-2.4.100-dev/lib/pkgconfig:/nix/store/31wlnp8yn7fk6mgfpqzsfw6jqaj2sg1y-wayland-1.17.0/lib/pkgconfig:/nix/store/sfw3ajgp78hg2gms1pvw7c47i1xsypxf-wayland-protocols-1.18/share/pkgconfig:/nix/store/8d3m6bcykjg6fq582ww5dr2bribidw0y-libXinerama-1.1.4-dev/lib/pkgconfig:/nix/store/bcvkw2rcm2qnfpilif9shw1qvc682lwx-json-glib-1.4.4-dev/lib/pkgconfig:/nix/store/3pjk8akvh4a2qh4swdncha66fmk8x34y-sqlite-3.30.1-dev/lib/pkgconfig:/nix/store/jn0b3ng89j768zkgjax1vwqd6idbs8c6-libsoup-2.68.3-dev/lib/pkgconfig:/nix/store/6bq333xm3lnqgkxkq8yry7n90q8rkh60-libxml2-2.9.10-dev/lib/pkgconfig:/nix/store/l7dyqxvzpxfcb3jk84ncpznk9m4h0iq8-dconf-0.34.0-dev/lib/pkgconfig:/nix/store/d8d4lyabgz970dlhbx2yr73lxkbwsdcc-gspell-1.8.2-dev/lib/pkgconfig:/nix/store/g5vsj14qm8j9036jf0hfbj1f6xzrsiqw-enchant-2.2.5-dev/lib/pkgconfig:/nix/store/8d81lwampy3m6f8rswpjfhc80znfndq0-gstreamer-1.16.2-dev/lib/pkgconfig:/nix/store/zvmxjggp6baq0g6yg12c20wa24qsxclw-gst-plugins-base-1.16.2-dev/lib/pkgconfig:/nix/store/ysqzm9azk2arhhfax88zd7vmjdaksmb8-gst-plugins-bad-1.16.2-dev/lib/pkgconfig:/nix/store/kr7f864agbgjb4qmlr1ji0j5kdhn6d9m-vala-0.46.5/lib/pkgconfig:/nix/store/s7vw8y02cqzx8bnjxl4bkhlnwvz6ws1s-python3-3.7.6/lib/pkgconfig:/nix/store/mn0f14glffxd6qh8kxpl50bzz1rkha5b-gobject-introspection-1.62.0-dev/lib/pkgconfig:/nix/store/jyn34rgd33h0diws5hgdy6ycsqd0v9gh-libffi-3.3-dev/lib/pkgconfig:/nix/store/20jfnqdap9kni2gir3lxb12m4mhrfkx6-glib-2.62.4-dev/lib/pkgconfig:/nix/store/72mklszjlpy55iiici6waz69dm5sphgf-zlib-1.2.11-dev/lib/pkgconfig:/nix/store/79k23ba41sqbr95x32zyb0w0k3smkkwk-gtk+3-3.24.12-dev/lib/pkgconfig:/nix/store/v0vkf12zsbhp2ndr1cwhrd67dnzmrm4w-at-spi2-atk-2.34.1/lib/pkgconfig:/nix/store/az71xbzia8aah1lswg1jwn0jf6gs1ffl-atk-2.34.1-dev/lib/pkgconfig:/nix/store/h6zaxr8kqn4c07v23crd5lq7d709k53v-cairo-1.16.0-dev/lib/pkgconfig:/nix/store/2hwaahrsw0r3ln1qlmlyihp08ds5daaf-fontconfig-2.12.6-dev/lib/pkgconfig:/nix/store/8h3k2kwa8vl2fic6sjn7jp6a6x9asfv0-freetype-2.10.1-dev/lib/pkgconfig:/nix/store/4jlms8pb06x5i267in9fw5qgc5k5sh09-bzip2-1.0.6.0.1-dev/lib/pkgconfig:/nix/store/7vabncllgbbd1k2gh8pazz5605r3zi4a-libpng-apng-1.6.37-dev/lib/pkgconfig:/nix/store/zxfjbpzhklj0vzw1qm836xwi2kd7wghy-expat-2.2.8-dev/lib/pkgconfig:/nix/store/nnazh72i9dhdl43ykkmw70y6lg60mhxw-pixman-0.38.4/lib/pkgconfig:/nix/store/qwqk3526d2avm6fnh1za74zjwn6a9ysz-libXext-1.3.4-dev/lib/pkgconfig:/nix/store/104zjprzidpbjx37l17bffbi6jgc69n1-xorgproto-2019.1/share/pkgconfig:/nix/store/7adia28fzsvv4bghjsdskim2dxh57sih-libXau-1.0.9-dev/lib/pkgconfig:/nix/store/52l8w18lggzynb8pqsjbzwwcjmjmzi1j-libXrender-0.9.10-dev/lib/pkgconfig:/nix/store/8vanm0flvl6c2q2d3sgmw4gx1qmpr78z-libX11-1.6.8-dev/lib/pkgconfig:/nix/store/vv58yhx3vznswgycifqd2h24m51y459q-libxcb-1.13.1-dev/lib/pkgconfig:/nix/store/6zqihahwmwz0w8fiqxw0ria4cvi230ma-xcb-util-0.4.0-dev/lib/pkgconfig:/nix/store/f3g2avcl6lnkxih197afgf2q517qp0gi-libGL-1.2.0-dev/lib/pkgconfig:/nix/store/vgk6q2ppnq1la4q8r1rjjv4v6s586laj-libglvnd-1.2.0-dev/lib/pkgconfig:/nix/store/gmik66cvidwqg6cbvpajk7619q9zlmww-fribidi-1.0.7/lib/pkgconfig:/nix/store/gy1aiqx2rca0nr4rfdd62fw1l4paq858-gdk-pixbuf-2.40.0-dev/lib/pkgconfig:/nix/store/z3k0gqb2i1hyikbji9kjqjdd1rv10w2k-libtiff-4.1.0-dev/lib/pkgconfig:/nix/store/vsas0dyj6ykl2xj8i1gql8l2rdfcnm3r-libjpeg-turbo-2.0.3-dev/lib/pkgconfig:/nix/store/pzz1xyyp18i4ws0isrfbdfpdcpxb290n-xz-5.2.4-dev/lib/pkgconfig:/nix/store/3p8zld8q7lndi1xwmfc6b747wwcfn2v6-gsettings-desktop-schemas-3.34.0/share/pkgconfig:/nix/store/f8za7xmxlas6lsr8xqspqk4hqva5w8im-libICE-1.0.10-dev/lib/pkgconfig:/nix/store/jrmbzpccjd7w9ci9g7m65la21mkjasvq-libSM-1.2.3-dev/lib/pkgconfig:/nix/store/9gnf7aprjkacwrksqdb0rxv6b6hmgzwg-libXcomposite-0.4.5-dev/lib/pkgconfig:/nix/store/yyqkghivryjcimxqscmmsjav4yk6f5wm-libXfixes-5.0.3-dev/lib/pkgconfig:/nix/store/40jc7cbj1jmw0s9n58payahpy3a7h8c7-libXcursor-1.2.0-dev/lib/pkgconfig:/nix/store/dlmjfqgxzgf61n2q1jhcgfgd0sy990sk-libXi-1.7.10-dev/lib/pkgconfig:/nix/store/m528dkc38sh7s14819cldrxp2mg8py6c-libXrandr-1.5.2-dev/lib/pkgconfig:/nix/store/shj6fsslcr630qbwd191sn1j4522v2sj-pango-1.44.7-dev/lib/pkgconfig:/nix/store/gz3vz893xvvqrfw7arw90ysjf3fd1z49-harfbuzz-2.6.4-dev/lib/pkgconfig:/nix/store/ls3pmzf7rrvrsqbyq7gl9h4ci5j9qkhy-graphite2-1.3.13/lib/pkgconfig:/nix/store/1zv9hd97msqrs0iphhy2c5yx0mqh5d8k-libXft-2.3.3-dev/lib/pkgconfig:/nix/store/208f971p8llm75kfgb9qsm7aibip78ns-mesa-19.3.1-dev/lib/pkgconfig:/nix/store/zvzqilx051k5wjpx2w02q4i387v4dbmg-libXdamage-1.1.5-dev/lib/pkgconfig:/nix/store/jbx0mbnqv4w5330gf3dyqc4wq63xccnn-libXxf86vm-1.1.4-dev/lib/pkgconfig:/nix/store/zxc7jqkyxfb10l9s91lx2cgj2nz5mhdk-libdrm-2.4.100-dev/lib/pkgconfig:/nix/store/31wlnp8yn7fk6mgfpqzsfw6jqaj2sg1y-wayland-1.17.0/lib/pkgconfig:/nix/store/sfw3ajgp78hg2gms1pvw7c47i1xsypxf-wayland-protocols-1.18/share/pkgconfig:/nix/store/8d3m6bcykjg6fq582ww5dr2bribidw0y-libXinerama-1.1.4-dev/lib/pkgconfig:/nix/store/bcvkw2rcm2qnfpilif9shw1qvc682lwx-json-glib-1.4.4-dev/lib/pkgconfig:/nix/store/3pjk8akvh4a2qh4swdncha66fmk8x34y-sqlite-3.30.1-dev/lib/pkgconfig:/nix/store/jn0b3ng89j768zkgjax1vwqd6idbs8c6-libsoup-2.68.3-dev/lib/pkgconfig:/nix/store/6bq333xm3lnqgkxkq8yry7n90q8rkh60-libxml2-2.9.10-dev/lib/pkgconfig:/nix/store/l7dyqxvzpxfcb3jk84ncpznk9m4h0iq8-dconf-0.34.0-dev/lib/pkgconfig:/nix/store/d8d4lyabgz970dlhbx2yr73lxkbwsdcc-gspell-1.8.2-dev/lib/pkgconfig:/nix/store/g5vsj14qm8j9036jf0hfbj1f6xzrsiqw-enchant-2.2.5-dev/lib/pkgconfig:/nix/store/8d81lwampy3m6f8rswpjfhc80znfndq0-gstreamer-1.16.2-dev/lib/pkgconfig:/nix/store/zvmxjggp6baq0g6yg12c20wa24qsxclw-gst-plugins-base-1.16.2-dev/lib/pkgconfig:/nix/store/ysqzm9azk2arhhfax88zd7vmjdaksmb8-gst-plugins-bad-1.16.2-dev/lib/pkgconfig`

**Comment by schmittlauch** [comment]
In case that doesn't help you reproduce this issue and it is a distro-specific thing, I suggest to just wait until it breaks.
There are some other NixOS packages throwing the same deprecation warning, so maybe someone else will fix the underlying issue :upside_down_face: .
So feel free to close this until it's relevant or leave it open.

**Comment by IBBoard** [comment]
Everything in your path appears to be listed twice! It looks like Meson doesn't like that any more (although the fix in https://github.com/mesonbuild/meson/issues/5736 should fix it).
