### ISSUE TITLE
Application settings menu icon is missing

### ISSUE THREAD

**Issue by felipehw** [IBBoard/cawbird#75]
In my system, Fedora 31, the Cawbird "application settings menu" icon is missing.

I tested with the flatpak version: `Cawbird  uk.co.ibboard.cawbird  1.0.4  stable  x86_64  flathub  system`
And the fedora repo version: `cawbird-1.0.3.1-1.fc31.x86_64.rpm`

![Screenshot from 2020-01-14 14-36-57](https://user-images.githubusercontent.com/4523897/72368134-3817a480-36dc-11ea-8932-4dd06cfb5e67.png)

**Comment by IBBoard** [comment]
That's… interesting.

I don't know whether there's any way to tell with Flatpak, but which version of GTK is it running? And are there any logs about it?

I'll have to give the native package a try on a VM.

**Comment by felipehw** [comment]
```
$ flatpak info uk.co.ibboard.cawbird

Cawbird - Twitter Client

          ID: uk.co.ibboard.cawbird
         Ref: app/uk.co.ibboard.cawbird/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.0.4
     License: GPL-3.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 1,8 MB
     Runtime: org.gnome.Platform/x86_64/3.34
         Sdk: org.gnome.Sdk/x86_64/3.34

      Commit: bfccf381ebfd9c08b35e820543ac6a646811162230997ef5cf5e54b3e27a23a9
      Parent: 4dd2e1ea46a29b4895e8d59873b39de5eba557af29f4710b5b48df0d1f9d3876
     Subject: Remove unused patch file (b0ef4d80)
        Date: 2020-01-12 20:20:17 +0000
```

**Comment by felipehw** [comment]
GTK in my Fedora machine is 3.24.13: gtk3.x86_64                                       3.24.13-1.fc31

**Comment by felipehw** [comment]
Look the output from shell, there is messages about "Theme parsing error":
Output from shell:

```
$ cawbird 

(cawbird:149868): Gtk-WARNING **: 21:40:35.829: Theme parsing error: style.css:20:13: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(cawbird:149868): Gtk-WARNING **: 21:40:35.829: Theme parsing error: style.css:243:16: The 'outline-radius' property has been renamed to '-gtk-outline-radius'

(cawbird:149868): Gtk-WARNING **: 21:40:35.829: Theme parsing error: style.css:249:19: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(cawbird:149868): Gtk-WARNING **: 21:40:35.829: Theme parsing error: style.css:250:25: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(cawbird:149868): Gtk-WARNING **: 21:40:35.829: Theme parsing error: style.css:255:36: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(cawbird:149868): cawbird-WARNING **: 21:40:36.879: ../src/CbUtils.c(call_done_cb): 0x5611dce48200, Not Found

(cawbird:149868): cawbird-WARNING **: 21:40:36.879: Twitter.vala:233: Not Found

(cawbird:149868): GLib-GObject-CRITICAL **: 21:40:37.553: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(cawbird:149868): GLib-GObject-CRITICAL **: 21:40:37.556: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(cawbird:149868): GLib-GObject-CRITICAL **: 21:40:39.237: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(cawbird:149868): GLib-GObject-CRITICAL **: 21:40:39.237: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(cawbird:149868): GLib-GObject-CRITICAL **: 21:40:39.237: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(cawbird:149868): GLib-GObject-CRITICAL **: 21:40:39.237: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(cawbird:149868): GLib-GObject-CRITICAL **: 21:40:39.238: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(cawbird:149868): GLib-GObject-CRITICAL **: 21:40:39.238: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(cawbird:149868): GLib-GObject-CRITICAL **: 21:40:39.238: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(cawbird:149868): GLib-GObject-CRITICAL **: 21:40:39.238: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(cawbird:149868): GLib-GObject-CRITICAL **: 21:40:39.238: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(cawbird:149868): GLib-GObject-CRITICAL **: 21:40:39.239: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(cawbird:149868): GLib-GObject-CRITICAL **: 21:40:39.239: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(cawbird:149868): GLib-GObject-CRITICAL **: 21:40:39.239: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(cawbird:149868): GLib-GObject-CRITICAL **: 21:40:39.239: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(cawbird:149868): GLib-GObject-CRITICAL **: 21:40:39.239: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(cawbird:149868): GLib-GObject-CRITICAL **: 21:40:39.240: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(cawbird:149868): GLib-GObject-CRITICAL **: 21:40:39.240: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(cawbird:149868): GLib-GObject-CRITICAL **: 21:40:39.240: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(cawbird:149868): GLib-GObject-CRITICAL **: 21:40:39.240: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(cawbird:149868): GLib-GObject-CRITICAL **: 21:40:39.240: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(cawbird:149868): GLib-GObject-CRITICAL **: 21:40:39.240: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(cawbird:149868): GLib-GObject-CRITICAL **: 21:40:39.240: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(cawbird:149868): GLib-GObject-CRITICAL **: 21:40:39.240: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(cawbird:149868): GLib-GObject-CRITICAL **: 21:40:39.241: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(cawbird:149868): GLib-GObject-CRITICAL **: 21:40:39.241: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(cawbird:149868): GLib-GObject-CRITICAL **: 21:40:39.241: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(cawbird:149868): GLib-GObject-CRITICAL **: 21:40:39.241: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(cawbird:149868): GLib-GObject-CRITICAL **: 21:40:39.241: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
$ 
```

**Comment by felipehw** [comment]
My (standard) theme selection:

![Screenshot from 2020-01-14 21-42-29](https://user-images.githubusercontent.com/4523897/72395024-e93b3080-3716-11ea-8d53-9769ba71ef1e.png)

**Comment by IBBoard** [comment]
Odd. I'm running libgtk-3-0-3.24.13+0-2.1.x86_64 on openSUSE Tumbleweed and I get the button!

The CSS warnings are a red-herring. They're a few other bits that need tidying up.

The "Not Found" will be a missing quoted tweet or something.

The `g_object_unref` is something that I need to look in to. Something is doing something bad in the memory handling somewhere, but C isn't helpful enough to tell you what and where. But I get those as well, so I don't believe that's the cause.

I've tried enabling the minimise button in case it overlaps and hides it, but it all seems to be handled correctly.

I'll try a VM with Fedora 31 at some point. It could be that it's a Flatpak issue and I don't see it in native builds, at which point I don't know what to do (other than suggest using native builds 😉)

**Comment by felipehw** [comment]
In my machine, a Fedora 31, this happens with RPM and Flatpak.
In another Fedora 31 machine, this doesn't happen with RPM.

And I erased my user confs of Cawbird. So, considering that I can't reproduce this situation ... I'll close this issue.
Thanks!

**Comment by IBBoard** [comment]
Odd. I don't know why a user config would cause it. If anyone else encounters it then I'll look in to it.

**Comment by felipehw** [comment]
Maybe my text was confusing. English isn't my native language.
I erased my user confs of Cawbird but the problem remains intact.

But, the question is this problem doesn't happen in the other machine.
If this was a common problem of Fedora ... this would happen to both machines.

But, considering that just one machine has this problem ... I closed the issue.

**Comment by IBBoard** [comment]
Sorry, I took "I erased my user conf… I can't reproduce this situation" as it having gone away.

If it is still happening then the [GTK Inspector](https://askubuntu.com/questions/597259/how-do-i-open-gtk-inspector) may help us debug. If you open the inspector, change to "Object" (if it's not already), click the "Select Options" button, then click the label in the Cawbird header bar then you should see something a bit like this:

![Screenshot from 2020-01-17 20-19-21](https://user-images.githubusercontent.com/388582/72643484-abcce200-3966-11ea-9a3d-7d5b335b0248.png)

The "Settings" `button` should be the one in the tree at the same level as the `stack` with classes `image-button popup toggle`.

**Comment by felipehw** [comment]
![Screenshot from 2020-01-17 21-21-06](https://user-images.githubusercontent.com/4523897/72654674-521ce580-396f-11ea-8a6b-2c54746b1ca7.png)

**Comment by IBBoard** [comment]
Okay, so at least we know it's literally not putting the button in there! (Rather than glitching and not showing it)

Not a clue *why* that would happen. I've not had to change any of the header bar code.

**Comment by felipehw** [comment]
Maybe there is some unthinkable arcane config in GNOME about CSD/headers there is removing this button?
