### ISSUE TITLE
There is support to "Bookmarks" in Cawbird?

### ISSUE THREAD

**Issue by felipehw** [IBBoard/cawbird#76]
There is support to "Bookmarks" in Cawbird?

I can't find anything about seeing bookmarked tweets in Cawbird ....
And the **"Limitations"** subtitle at <https://github.com/IBBoard/cawbird> doesn't talk about this ...

This is annoying because I have to access my Twitter account through a browser just to see my bookmarked tweets.

**Comment by IBBoard** [comment]
TBH, I wasn't even aware that this was a feature! Why would I look under "Share" for a bookmark? (Not that "share" even looks like a sharing icon)

Anyway, based on the [API index](https://developer.twitter.com/en/docs/api-reference-index) then Twitter hates users and developers and there's no way for third-party apps to access bookmarks.

I'll close this ticket once I update the docs, and then create a separate "do local Cawbird-only bookmarking" feature request.
