### ISSUE TITLE
RPM installation fails on CentOS 8 

### ISSUE THREAD

**Issue by tukusejssirs** [IBBoard/cawbird#79]
I have tried to install Cawbird on CentOS 8 using [RPM](https://software.opensuse.org//download.html?project=home%3AIBBoard%3Acawbird&package=cawbird) with the following commands.

```bash
sudo dnf -y install yum-utils
sudo dnf config-manager --add-repo https://download.opensuse.org/repositories/home:IBBoard:cawbird/CentOS_7/home:IBBoard:cawbird.repo
sudo dnf -y install cawbird
```

The final command fails:

```bash
Error: 
 Problem: conflicting requests
  - nothing provides libgspell-1.so.1()(64bit) needed by cawbird-1.0.4-3.1.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

I know that the package is for CentOS 7, but I hoped it would work. I have tried to install both `gspell.x86_64` (`gspell-1.8.1-1.el8.src.rpm`) and `gspell-devel.x86_64` (`gspell-1.8.1-1.el8.src.rpm`), but I won’t work.

The problem lays in the updated library. The new version of `gspell` provides `/usr/lib64/libgspell-1.so.2.3.0` library including its symlink to `/usr/lib64/libgspell-1.so.2`. I tried to create another symlink to `/usr/lib64/libgspell-1.so.1`, but it didn’t help either.

Is there any way to either work this around or fix this issue? :smiley:

**Update:** I’ve forgotten to note that I had already have installed RPM Fusion repos, both free and non-free.

**Comment by IBBoard** [comment]
The CentOS 7 package is built for CentOS 7. Given that they're Enterprise-grade distros then there's going to be a lot of movement between versions and it's not surprising that the dependencies aren't all there.

I'm looking in to why CentOS 8 isn't building. It should be, but there's a dependency (outside of my control) that it says doesn't exist even though it's a CentOS package depending on another CentOS package.

**Comment by tukusejssirs** [comment]
I understand. :)

Is there anything I can help with? I am not a professional programmer, but I could test, review, report and probably debug some stuff.

**Comment by IBBoard** [comment]
You can test once it is packaged, but the packaging issues are just an oddity of the build service. I'm hoping I've got a workaround in place now. We just need to wait for it to all work its way through the system.

**Comment by IBBoard** [comment]
It seems I've FINALLY got all of the magic runs working to make CentOS 8 happy. It has been by far the most awkward RPM-based distro that I've encountered so far! I'm sure they have their reasons, but several things seem to behave in slightly different ways to other distros (special tag to 'enable' Python, extra arguments for meson/GCC).

The build should appear in the repo soon.

**Comment by tukusejssirs** [comment]
Thank you for taking your time into fixing this issue. :smile:

**Comment by tukusejssirs** [comment]
I confirm that it works!

Anyway, I think you should update the [repo website](https://software.opensuse.org//download.html?project=home%3AIBBoard%3Acawbird&package=cawbird) installation instructions for CentOS.

You could either keep the form and modify the instuctions to this:

```bash
cd /etc/yum.repos.d/
wget https://download.opensuse.org/repositories/home:IBBoard:cawbird/CentOS_$(rpm -E %centos)/home:IBBoard:cawbird.repo
yum install cawbird
```

… or list `yum-utils` as an optional dependency (`dnf-utils` on CentOS 8 is / will be symlinked to `yum-utils`) and you could change the instructions as follows.

```bash
# CentOS 7 and 8 (this works on both versions)
yum-config-manager --add-repo https://download.opensuse.org/repositories/home:IBBoard:cawbird/CentOS_$(rpm -$ %centos)/home:IBBoard:cawbird.repo
yum install cawbird

# CentOS 8
dnf config-manager --add-repo https://download.opensuse.org/repositories/home:IBBoard:cawbird/CentOS_$(rpm -E %centos)/home:IBBoard:cawbird.repo
dnf install cawbird
```

**Comment by IBBoard** [comment]
Those are automated Open Build Service instructions. I have no control over them.

**Comment by tukusejssirs** [comment]
Okay. Anyway, I was too quick to conclude it works. I can open `cawbird`, it shows a message that I need a PIN, but when I click on the _Request PIN_ button, it segfaults (core dumped).

**Comment by IBBoard** [comment]
Please run `G_MESSAGES_DEBUG=cawbird cawbird` and post a new bug report with the log from when you click "Request PIN".
