### ISSUE TITLE
Copy link to twit?

### ISSUE THREAD

**Issue by fauno** [IBBoard/cawbird#80]
Hi, I couldn't find anything related to this on the contextual menus or shortcuts, is there a way to copy the link to a twit so it can be opened on a browser or shared?

**Comment by fauno** [comment]
Found it, it was kinda hidden by the dark theme:

![cawbird](https://user-images.githubusercontent.com/468204/73099859-1d5ae200-3ecb-11ea-86c2-b0a83e0b8a64.png)

**Comment by IBBoard** [comment]
Yeah, single tweet view (normally double-clicking a tweet from a timeline) has a "Source" link on the right-hand side. You can click to open a browser or right-click to copy.

I hadn't noticed that it was so pale before, though.
