### ISSUE TITLE
Back button should be the most left element in the top bar

### ISSUE THREAD

**Issue by daquinons** [IBBoard/cawbird#83]
As a user, when I use a button based navigation and I want to go back, I expect the 'back' button to be the first element of the bar.

Currently, the back batton is the third element, after the avatar and new tweet button.

I believe it would be a great UX improvement to move the back button to the first position.

**Comment by IBBoard** [comment]
Good point. I'd have to work out what to do with the "Account" button, though. I suspect the interface layout came from the "old" pattern (up to Gnome 3.30) where the app icon was the left-most button (e.g. most of the screenshots in this [OMGUbuntu article](https://www.omgubuntu.co.uk/2018/07/nautilus-3-30-improvements-new-path-bar))

We could combine the accounts and the settings buttons. But then you need to show "Settings" while also showing the current account avatar (for people using multiple accounts). And just moving the avatar next to the settings button would probably look odd.

Or, given that the window title is your handle, maybe we can merge the settings, drop the avatar image and just keep the title (and then make "Mentions" into "@<your-handle> - Mentions")?

I think this needs a few suggestions and mockups.

**Comment by IBBoard** [comment]
Now incorporated into #177
