### ISSUE TITLE
No avatars or pictures - how to reload?

### ISSUE THREAD

**Issue by cyberl33t** [IBBoard/cawbird#85]
I've been using Cawbird (1.0.4/Arch Linux) for some months now, and I've been very pleased with it. But in the last few days I've started to have severe problems with it. Most of the times the avatars does not load, but are replaced with a smiley, and most of the pictures are missing. Sometimes restarting Cawbird helps, sometimes not. Sometimes removing .config/cawbird and starting anew helps, sometimes not...

I realize that the problem may be in the Twitter end, but so far I've had no issues with other Twitter clients (Android/web). 

Cawbird shouldn't give up loading those avatars and pics, but try and try again until all are loaded. Either that, or there should be a way to manually force reloading/refreshing of the whole stream. As it is now, Cawbird has become almost unusable.

**Comment by IBBoard** [comment]
> Cawbird shouldn't give up loading those avatars and pics, but try and try again until all are loaded. 

That's generally a Bad Idea™. We have no idea why the images are failing to load, and for all we know then it's a permanent issue, so retry-until-success normally just wastes cycles and network connections (and potentially has an impact on performance).

As it's Arch then you're presumably already patched to solve the GnuTLS problems that were behind #9?

What logging do you get when you run `G_MESSAGES_DEBUG=cawbird cawbird`?

**Comment by cyberl33t** [comment]
While starting cawbird from terminal (or running your command) I'm getting lots and lots of entries like
`(cawbird:6305): cawbird-DEBUG: 21:38:24.935: Request on 'https://pbs.twimg.com/media/EPxk0NxX4AAccCS.jpg' returned status 'Cannot resolve hostname'`
`(cawbird:6411): cawbird-DEBUG: 21:44:49.268: Request on 'https://pbs.twimg.com/media/EPxBTwwW4AAWEwf.jpg' returned status 'Cannot connect to destination'`
If I pick any of those addresses and copy/paste it into a browser, the picture loads immediately.

Do you want the whole debug output?

This afternoon Cawbird/Twitter behaved almost normally, but now it is again text/smilies only. Seems that there really is something wrong with Twitter servers. Strange thing is that Cawbird is the only client that is affected, Talon (the Twitter client I'm using on Android) and web interface works normally

**Comment by IBBoard** [comment]
Those are the important parts of the log.

If it's getting "cannot resolve hostname" then it suggests that Cawbird is making the request to the library but the DNS lookup is failing.

If you run `dig` repeatedly to do DNS lookups, do you get some errors?

```
for i in `seq 1 50`; do dig +short pbs.twimg.com; done
```

I get mainly cs2-wac.apr-8315.edgecastdns.net (192.229.233.50) but occasionally twimg.twitter.map.fastly.net (151.101.16.159) and just one or two pbs.twimg.com.eip.akadns.net (23.1.106.237) but no errors.

**Comment by cyberl33t** [comment]
`cs196.wac.edgecastcdn.net.`
`cs2-wac.apr-8315.edgecastdns.net.`
`cs2-wac-eu.8315.ecdns.net.`
`cs672.wac.edgecastcdn.net.`
`192.229.233.50`

Mostly those, no errors or references to twitter or twimg

**Comment by IBBoard** [comment]
There won't be any references to twitter or twimg. the pbs.twimg.com domain is an alias, which Twitter use to distribute things around content delivery networks (like Edgecast and Akamai). `dig` is reporting those aliases.

Something somewhere in the stack below Cawbird is having issues with DNS, and I'm not convinced that I can do much about it.

Which package are you using? AUR, Snap or Flatpak?

**Comment by cyberl33t** [comment]
AUR

**Comment by IBBoard** [comment]
I think we've got some other Arch users using the AUR. I don't know if they've seen the problems (or if the Arch forums have any other reports of DNS lookup failing, but seemingly only for some apps/libraries)

**Comment by cyberl33t** [comment]
I finally figured out what was wrong: the dnsmasq implementation within my Ubiquiti EdgeRouter was somehow broken or misconfigured. I disabled it in the router and set up dnsmasq on another machine in my nerwork. Now, after some days of testing, cawbird behaves as it should. When there is a lot of other network traffic, occasionally some picture or avatar does not load right away. The missing pictures _eventually_ load, but it may sometimes take quite a long time. So, a manual 'refresh' option could still be useful...
What still puzzles me a bit is why cawbird was the only app to suffer? If it wasn't for the cawbird issues, I would have happily continued to use the router as it was and probably never noticed anything.

**Comment by IBBoard** [comment]
Odd. As far as I can tell then the avatars come from the same domain, so unless GLib/libsoup is doing a DNS lookup each time and not caching it (or happened to hit your DNS server repeatedly during a problem patch and then kept retrying because it failed the last time, while everything else had it cached) then I don't know what's happening and it's all in libraries that we have no control over.

I think it'll be best to put "manual refresh" in as a separate feature request. It should be possible, but I don't know whether it'll need some rearchitecting off the top of my head.
