### ISSUE TITLE
Could not create gtksink. Need gst-plugins-bad >= 1.6

### ISSUE THREAD

**Issue by JuanCarlosHerreraBlandon** [IBBoard/cawbird#86]
When I try to play a video from the application, an error is always shown.
I installed the latest version of gstreamer, but nothing works yet.

I currently have the Linux Fedora 31 operating system

attached error image:

[https://imgur.com/Aptw2Ug.png](url)

**Comment by JuanCarlosHerreraBlandon** [comment]
the solution is install the following packages since terminal comand

sudo dnf install gstreamer gstreamer1-plugins-good-gtk

**Comment by IBBoard** [comment]
Are you installing from the OBS repo or from Fedora? That sounds like a package dependency issue.

**Comment by edarblanco** [comment]
Distribution: ArchLinux
Kernel: 5.9.14
Cawbird version: 1.2.1
Hello, I am wanting to see videos in cawbird, but I always get this error, I have installed gst-plugins-bad 1.8.2 and even then it continues to exit, I have returned to the version that indicates 1.6 and everything returns to normal but nothing above of that version let me play videos

**Comment by IBBoard** [comment]
I'm running GStreamer 1.18 on openSUSE Tumbleweed, so it shouldn't be a "new version" incompatibility.

What GStreamer packages are available? The previous reporter said they had a GStreamer-GTK package that they could install that fixed it.

I'm trying to get GStreamer to tell me what plugins are required, but not getting too far. Twitter appears to use `video/x-h264`/`H.264 / AVC`/`H.264 (Main Profile)`. I think that's often gst-plugins-bad, but may also need libav* packages (e.g. libavcodec)

**Comment by edarblanco** [comment]
> la solución es instalar los siguientes paquetes desde terminal comand
> 
> `sudo dnf install gstreamer gstreamer1-plugins-good-gtk `

![image](https://user-images.githubusercontent.com/3819778/103440990-850bc800-4c18-11eb-8b1e-21eddb3a186c.png)

I have install all libav and not work, but searching on google, found a article, and result is excelent, on resume, some extra packages being are installing, gst-plugin-opencv and gst-plugin-gtk, for archlinux, works, like a charms, Happy New Year

![image](https://user-images.githubusercontent.com/3819778/103441136-dcf6fe80-4c19-11eb-9602-fed665f015cd.png)

**Comment by IBBoard** [comment]
We don't use OpenCV (which is for object detection and other computer vision tasks) so it must be the `gst-plugin-gtk` package that you were missing.

**Comment by edarblanco** [comment]
OK, only follow de article, it seems that all the functionality was moved to a separate package from old gstreamers-0.10-base to new gst-plugin-gtk on Archlinux

**Comment by IBBoard** [comment]
That's already described in a sub-bullet of our [build dependencies](https://github.com/IBBoard/cawbird#build-dependencies). If it wasn't getting installed automatically then whoever builds your Arch package didn't have it specified.

**Comment by edarblanco** [comment]
> That's already described in a sub-bullet of our [build dependencies](https://github.com/IBBoard/cawbird#build-dependencies). If it wasn't getting installed automatically then whoever builds your Arch package didn't have it specified. 
Yes, maybe dont consider that, but now is fixed, and close again the thread
